### ISSUE TITLE
clarify remote/local errors

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1047]
### Background

Please clarify where an error is originating from.
It is not easy to know sometimes. I actually thought the limitation of multiple channels was in lnd, not the remote node, until i was finally convinced by an persistent community member that i was wrong.

Some examples:

#### Local error:
```
$ lncli openchannel 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 10000
[lncli] rpc error: code = Unknown desc = channel is too small, the minimum channel size is: 20000 SAT
```

#### Remote error:
```
$ lncli openchannel 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 100000
[lncli] rpc error: code = Code(177) desc = Multiple channels unsupported
```

#### ¯\\_(ツ)_/¯ error:
```
$ lncli connect 02952cc6b7f92226e490d6354636604a26484a396627c97661c932ffc55042a500@62.210.36.142:9735
[lncli] rpc error: code = OutOfRange desc = EOF
```

**Comment by Roasbeef** [comment]
First error is that you tried to make a channel with 10k satoshis, but the min is 20k satoshis. 

Second error is that you tried to open up another channel with a `clightning` node, but they don't support multiple channels. 

Final error is due to the connection being forcibly closed by the remote party. In this case we have no context, so we can't really deliver a reason, though the EOF message can be improved.

**Comment by robtex** [comment]
what i mean is that the error should be more clearer in *all* cases, to say if the error comes from the remote side, or is generated locally.

how do you distinguish if this is a limit of the node you are on, or the other side
imho it should say something like

`local error: channel is too small, the minimum channel size is: 20000 SAT`

`remote error: channel is too small, the minimum channel size is: 20000 SAT`

so it is clearer if the limitation is on your side or the other side

and the same thing for other cases, like limitations of multiple channels or whatnot
