### ISSUE TITLE
Unable to locate link

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#126]
http://pastebin.com/MPuXAQEk
I've included: getinfo, current channels, queryroute, and attempting to send to a few nodes.

I think this has been a common issue we've all been seeing. Is it graph related or any zombie channels?

**Comment by juscamarena** [comment]
Ah.. Just noticed I'm seeing zero active channels. 
"num_active_channels": 0,
Weird. I was able to send to 034106ba0a6ffdb98f345b2d39173d236575aa9b18f68542db7c5dc7d561ff68da which I have a channel open. Maybe something went wrong on his end.

**Comment by Roasbeef** [comment]
I have a local commit for multi-path path finding which should be pushed out some time later this week. This new feature will make sending payments more reliable as a variety of paths will be considered and tries serially when attempting to dispatch a payment rather than the first complete path encountered. 

The `num_active_channels` field doesn't indicate the total number of _open_ channel, just active where active means that the peer is currently online.  

Seeing an "unable to locate link" error when attempting to send a payment indicates that somewhere along the route the next-hop was either not found, or not currently _online_.

**Comment by juscamarena** [comment]
Here's another crash: 

http://pastebin.com/bi9GFuxy

**Comment by juscamarena** [comment]
Here's another crash: http://pastebin.com/hghXR2jP

**Comment by juscamarena** [comment]
Not to bombard with more comments here's another one but from my raspberry pi: http://pastebin.com/sQ9UvbDm

**Comment by AndrewSamokhvalov** [comment]
Hey @juscamarena, thanks for your feedback! I will try to elaborate the reason of this panics and will be soon with response.

**Comment by juscamarena** [comment]
Thanks! For further reference, do you prefer I create a new issue each time or just post here or on irc?

**Comment by AndrewSamokhvalov** [comment]
Was fixed in [this](https://github.com/lightningnetwork/lnd/commit/178f561a2a11c49bad9e07501866f650ff29df33) commit

**Comment by Roasbeef** [comment]
As Andrew pointed out, this was fixed by 178f561a2a11c49bad9e07501866f650ff29df33, and a few other commits. 

Closing.
