### ISSUE TITLE
[ERR] SRVR: unable to start server: -26: min relay fee not met, 165 < 166 (code 66)

### ISSUE THREAD

**Issue by molxyz** [lightningnetwork/lnd#1271]
LND can't start after updated to the latest version. I have tried to restart the node several times but got the same error every time. 
The log is here:  https://paste.ee/p/wjChP#inMUwgEPAP7McbJuiEG9KF5HukZ5cNrF .

### Your environment

* version of `lnd`:  Version 0.4.1-beta commit=95293f510298250a1f9ff8a0e43975e6c6fec72d
* operating system :  Ubuntu 16.04.4 LTS - Xenial
* backend:  bitcoind
* I'm running this node on the same server with another LND node and sharing the same bitcoind.  In bitcoin.conf I have `rpcthreads=12`  (This other lnd node can start fine after updated to the same commit.)

**Comment by guggero** [comment]
This could be related to #988 or #1054.

Can you please check if it helps to set `minrelaytxfee=0.00000001` on `bitcoind`?

**Comment by molxyz** [comment]
@guggero  It works!  Thank you.  Could I ask what does the error mean and why is it that my other node could restart but this one couldn't?

**Comment by guggero** [comment]
Nice :) You're welcome.

The error means that `lnd` was trying to broadcast a transaction that had lower fees than what was configured in your `bitcoind` to accept (minrelaytxfee=x means that every transaction that has lower fees than x would be ignored/dropped).
This means that only one of your nodes has a channel that needed an on-chain update, which it could not apply.

I thought I already saw a Pull Request that fixed this problem, but now I'm not sure any more since I can't seem to find it...

**Comment by molxyz** [comment]
@guggero  I'm guessing this PR?  https://github.com/lightningnetwork/lnd/commit/3c33a8cb6722fc8dbd7cce1e3a8751ab8f09dd5d

**Comment by wpaulino** [comment]
It could be that the timeout transaction was created before updating to the latest master and so the fix wasn't in place.

**Comment by Roasbeef** [comment]
Closing for now based on @wpaulino's conclusion, will re-open if it re-emerges after 0.4.2 is released.

**Comment by engenegr** [comment]
Hi.

The problem still persists.

http://paste.debian.net/1029646

Why I post it: my node operates for a long time (several weeks) without setting up `minrelaytxfee` so I'm not sure that it is correct behavior. 

Now I will check it with this option enabled.
