### ISSUE TITLE
No ability to do CORS

### ISSUE THREAD

**Issue by phillyfan1138** [lightningnetwork/lnd#1405]
### Background

I'm trying to enable a website (that I've built, ergo trusted) to access my lightning node from a separate domain.  However, I have cross domain issues.  As far as I can tell there are no options to enable CORS in lnd. 

I've tried to edit the code to allow CORS in much the same way as tlsextraip is added in the config but I receive "unknown option cors" from the log.  Using https://github.com/lightningnetwork/lnd/pull/634/files as a reference.

**Comment by Roasbeef** [comment]
Are you familiar with the way the golang http middleware is usually implemented? There're buncha libs that allow you to add them on as higher level functions on the regular `http.Handler` essentially.

**Comment by phillyfan1138** [comment]
Yeah, I've done some work with golang.  Getting CORS to work is not really the problem.  Its that I can't seem to get the extra options passed into the program.

**Comment by Roasbeef** [comment]
Do you have a sample PR to throw up?

On Jun 20, 2018 12:44 AM, "Daniel Stahl" <notifications@github.com> wrote:

Yeah, I've done some work with golang. Getting CORS to work is not really
the problem. Its that I can't seem to get the extra options passed into the
program.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/1405#issuecomment-398579641>,
or mute the thread

**Comment by phillyfan1138** [comment]
I have forked: https://github.com/phillyfan1138/lnd

**Comment by Roasbeef** [comment]
So I'm going to close this issue for now, as issues aren't for debugging new code you've added to a fork of `lnd`. If you wish to add this feature, then create a PR and perhaps someone else that also needs the feature will help to review and test it.
