### ISSUE TITLE
lncli should ask to repeat passphrase

### ISSUE THREAD

**Issue by abrkn** [lightningnetwork/lnd#1507]
### Background

`lncli` should ask to repeat passphrase for improved user experience/security

### Your environment

`lnd version 0.4.2-beta commit=a0b2fadea35fa4642daf4e9f56e6ecfe31d22ce1`

### Steps to reproduce

`lncli create`

Use existing seed. Add passphrase.

### Expected behaviour

Should ask to repeat passphrase

### Actual behaviour

Only asks once.

**Comment by Roasbeef** [comment]
> bip38

We don't use bip38.

**Comment by abrkn** [comment]
> We don't use bip38.

Updated to reflect that

**Comment by cbarraford** [comment]
I've created a PR for this issue, https://github.com/lightningnetwork/lnd/pull/1540

**Comment by carlaKC** [comment]
Going to pick this up since it seems like the existing PRs have stalled? 

Just wondering about UX for this change, in terms of how many times a user should be allowed to re-attempt their password if they get it wrong, and whether to start from scratch with a new password if they fail to match their original entry. 

Something like this, allowing the use to go through this flow twice then terminate because you don't want people to get confused over which password they've entered?
1.     Enter Password: 
2.     Repeat password: does not match
3.     Repeat attempt 2: does not match

**Comment by cfromknecht** [comment]
> Use existing seed. Add passphrase.

@abrkn if you have an existing seed, it already has a passphrase. you're only entering it to decrypt the seed.

**Comment by wpaulino** [comment]
> Just wondering about UX for this change, in terms of how many times a user should be allowed to re-attempt their password if they get it wrong, and whether to start from scratch with a new password if they fail to match their original entry.

@carlaKC to me the best approach seems like prompting the user in an infinite loop for the password if the confirmation doesn't match, though there may be differing opinions. So something like:

1. `Enter password:`
2. `Repeat password: does not match`
3. `Enter password:`

I believe this would match the behavior of creating new users in a UNIX system.
