### ISSUE TITLE
"FeeInsufficient(fee=" shows amt_to_forward_msat instead of fee

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1548]
unable to route payment to destination: FeeInsufficient(fee=43534435 mSAT, update=(lnwire.ChannelUpdate)

### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
Not a bug as this is the routing message: https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md

**Comment by Roasbeef** [comment]
It's actually the fee though.

On Jul 12, 2018 12:28 PM, "robtex" <notifications@github.com> wrote:

data:
[8:htlc_msat]
[2:len]
[len:channel_update]

this one? i really think it would make more sense to display it ashtlc_msat=
rather than fee=, to make it clear that the value shown is not actually the
fee.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/1548#issuecomment-404624327>,
or mute the thread

**Comment by Roasbeef** [comment]
Ahh, I see what you're getting at, yeh the log message is wrong, will fix!
