### ISSUE TITLE
panic: htlc index mismatch: 1 vs 0

### ISSUE THREAD

**Issue by slush0** [lightningnetwork/lnd#1575]
### Background

lnd panicked and process stopped shortly after casual service reload:

```
2018-07-17 11:30:28.694 [INF] CRTR: New channel discovered! Link connects 0235447c7485ff2b945bac5fbc366d54a87389bab8cacf1b64b26ec01e96bd165a and 0371bcbde71d6cc591134e6d95592a9e8baac232a1e975ccd67c111864a5e8d373 with ChannelPoint(837b11a93cf2562738d7ab17560a74cec01b265a30695c2000fc07cc7c50cd46:1): chan_id=557023585794457601, capacity=0.0001 BTC
panic: htlc index mismatch: 1 vs 0

goroutine 95027 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreStateLogs(0xc423720120, 0xc4223e32c0, 0xc4223e3500, 0xc4223e35c0, 0xc42016c600, 0xc4222064e0, 0x0, 0x0)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1807 +0xada
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreCommitState(0xc423720120, 0xc42a4f3af8, 0xc42a4f3a78, 0x0, 0xc422e9df80)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1687 +0x4a1
github.com/lightningnetwork/lnd/lnwallet.NewLightningChannel(0x170dbe0, 0xc420526a80, 0x7f2e7b8d17a0, 0xc42052a1c0, 0xc42e713500, 0x0, 0x0, 0x17e5410)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1380 +0x7ea
main.lndMain.func7(0x5471749bfd1dac89, 0x9ea010e9961c2cd7, 0x316fd78e4bb7c5fe, 0xceb3454beee0b607, 0x0, 0x2, 0xc423b19338)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/lnd.go:376 +0x348
main.(*fundingManager).handleFundingLocked(0xc42016c500, 0xc423599760)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:2201 +0x455
created by main.(*fundingManager).reservationCoordinator
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:871 +0x524
```

After the restart, it booted up normally.

### Your environment

* 0.4.2-beta commit=b0288d46773ac6d45e5dc4d5e6a80dd3034d0b9f
* Linux server01 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
* bitcoind 0.16.1

### Steps to reproduce

I cannot reproduce.

### Expected behaviour

Node should not crash.

### Actual behaviour

Node stopped working, I had to start it manually again.

**Comment by Roasbeef** [comment]
Was this a new node, or an existing node? As in did it have some channels existing from maybe before 0.4.2 or right after it? In the past we've tackled this issue and assumed that the series of PR's linked in this issue did the trick: https://github.com/lightningnetwork/lnd/pull/1255

**Comment by halseth** [comment]
@slush0 Thanks for reporting this! 

This is a quite serious bug we have been investigating before. I thought we were able to fix it in v0.4.2 though... Did you upgrade from v0.4.1, and the channel was opened from the old version? 

Something to note is that the HTLC restoration in this case is a result of receiving a `fundingLocked`, meaning that either 1) the channel shouldn't have been active yet, and therefore shouldn't have had any HTLCs to restore, or 2) the peer is resending a `fundingLocked` for an already active channel.

**Comment by slush0** [comment]
> Was this a new node, or an existing node? 

Existing node, created from 0.4.2-beta codebase.

Unfortunately, logs are already gone :(. I'll take a snapshot if this happen again after some restart.

**Comment by alexbosworth** [comment]
I saw the same issue on a fresh testnet node

```
2018-09-12 11:26:29.336 [INF] DISC: gossipSyncer(02c9c1c713bfde2b9e5116ced4eb7d26cc8df003f62e0cc2f923212552a311f1b4): applying new update horizon: start=2018-09-12 10:28:38 +0000 UTC, end=2154-10-19 16:56:53 +0000 UTC, backlog_size=334
panic: htlc index mismatch: 1 vs 0

goroutine 53960225 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreStateLogs(0xc44869c480, 0xc428ccf440, 0xc428ccf500, 0xc428ccf5c0, 0xc434b9b100, 0xc426df4960, 0x0, 0x0)
	/root/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1827 +0xa49
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreCommitState(0xc44869c480, 0xc441cefce0, 0xc441cefc60, 0x110cd18, 0x0)
	/root/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1707 +0x49d
github.com/lightningnetwork/lnd/lnwallet.NewLightningChannel(0x11adb60, 0xc420084d80, 0x7f104c421590, 0xc42065a080, 0xc427b78300, 0x1, 0x3b718aa669c71407, 0xc43019a5f0)
	/root/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1400 +0x6a3
main.newServer.func18(0x4287b00f99d0c9b4, 0x4ff3d766cac73d69, 0x9da23efbaec3a98b, 0x7b29cfdaec320fab, 0x0, 0x2, 0xc42216e8c8)
	/root/go/src/github.com/lightningnetwork/lnd/server.go:757 +0x154
main.(*fundingManager).handleFundingLocked(0xc4201e6500, 0xc423749780)
	/root/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:2317 +0x451
created by main.(*fundingManager).reservationCoordinator
	/root/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:892 +0x4f3
```

**Comment by halseth** [comment]
Reopening per https://github.com/lightningnetwork/lnd/issues/1575#issuecomment-420700159

**Comment by halseth** [comment]
I think I tracked down the reason for this bug (at least this is  a theory):

When we receive a `fundingLocked`, we go on to fetch the channel state from the database: 
https://github.com/lightningnetwork/lnd/blob/1c4bd04c556f94e64b73ce20fd8c68dc8bf1b37d/server.go#L747

We then use the channel state to create a `LightningChannel`:
https://github.com/lightningnetwork/lnd/blob/1c4bd04c556f94e64b73ce20fd8c68dc8bf1b37d/server.go#L754

Calling `NewLightningChannel` will initiate the state logs restoration, and at some point we will attempt to fetch the pending remote commit from the database: https://github.com/lightningnetwork/lnd/blob/1c4bd04c556f94e64b73ce20fd8c68dc8bf1b37d/lnwallet/channel.go#L1668

We don't have any guarantees that this pending commitment wasn't rewritten between the time we fetched the channels state from the db, and when we retrieved the pending commitment, so I think this scenario can happen:

* The channel is active, but has no active HTLCs.
* `fundingLocked` comes in for the channel, and we fetch the state from the DB.
* We add two HTLCs to the channel, one gets locked in on the remote commitment (index `0`), and one is added to the pending remote commitment (index `1`). This is written this to the DB.
* We call `NewLightningChannel` with the state retrieved earlier, which will retrieve the pending commit.
* The pending commit will contain the HTLC with index `1`, which will be out of sync with the channel state we retrieved earlier, and we'll see the panic.

I can think of a few possible solutions:
1. Make sure we always retrieve the pending commitment together with the rest of the channels state.
2. Ignore `fundingLocked` for channels that are active. 
3. Don't restore the state logs for channels before actually adding them to the link. (Add a new `Start()` method to avoid starting the channel unnecessarily).

I would actually implement a combination of these since it might harden the channel state machine in other places as well, but 1 should be enough to fix this.
