### ISSUE TITLE
payment_error: "address type cannot be resolved"

### ISSUE THREAD

**Issue by grunch** [lightningnetwork/lnd#1671]
### Background
I've been running a mainnet node on a Odroid HC2 since a while and until now it was working fine, recently I realize that I can't send payments.

I tried to pay a BLW invoice from the node and I get this error

```"payment_error": "address type cannot be resolved"```

I'm looking into lnd code and the message is exacly what it says, lnd couldn't resolve the tcp address, but **payment request contains no TCP addresses**, the node is perfectly working with internet connection, `"synced_to_chain": true`, and the wallet is fully operational.

### Environment

* lnd version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
* Linux grunch 4.14.26-120 #1 SMP PREEMPT Wed Mar 14 00:21:56 UTC 2018 armv7l armv7l armv7l GNU/Linux
* Bitcoin Core RPC client version v0.16.0

### Steps to reproduce
```lncli payinvoice lnbc...invoice```
or
```lncli sendpayment --pay_req lnbc1...invoice```
### Expected behaviour
Pay the invoice
### Actual behaviour
I get this error
```
{
	"payment_error": "address type cannot be resolved",
	"payment_preimage": "",
	"payment_route": null
}
```
The error response is inmediatetly

**Comment by wpaulino** [comment]
Have you upgraded to anything past commit `7cf5ebe2650b6798182e10be198c7ffc1f1d6e19 ` and reverted back? We introduced a new address type for Tor, so it's possible that you have a node in your graph advertising one. If you haven't upgraded though, I believe the node announcement advertising the Tor address should've been rejected so this ideally shouldn't happen.

The reason for the error is because we look at the whole graph in order to determine the best path.

**Comment by grunch** [comment]
Yeah I upgraded few weeks after commit `7cf5ebe2650b6798182e10be198c7ffc1f1d6e19` and reverted because I was having a lot of issues, how can solve this issue? can I refresh that graph data?

**Comment by grunch** [comment]
thanks @cfromknecht  

closing it!
