### ISSUE TITLE
Q: listinvoices after 0.5 update returns old not newly created invoices

### ISSUE THREAD

**Issue by redstorm1** [lightningnetwork/lnd#1852]
### Background

lncli --network=testnet listinvoices

returns old invoices, does not show a newly created invoice 

Looks like something was changed and i need to remove / update something.

### Your environment

 version 0.5 commit=a1f549754b61c1ba84466f0226997687127f7fc0
 4.15.0-24-generic #26~16.04.1-Ubuntu
Bitcoin Core RPC client version v0.16.2.0-g2848aa808f

### Steps to reproduce

create a new invoice
lncli --network=testnet addinvoice --amt 40000 --memo testinv

list invoices
 lncli --network=testnet listinvoices

### Expected behaviour

Expect to see new invoice at the end of listinvoices

### Actual behaviour

only old invoices shown

edit: added version and environment info

**Comment by Roasbeef** [comment]
So it does pagination by default now. You'll need to set either of these two flags: 
```
   --index_offset value  the number of invoices to skip (default: 0)
   --max_invoices value  the max number of invoices to return (default: 0)
```

**Comment by mably** [comment]
Yep that's a bit annoying to handle now, don't know how to do that in my lnd web client.

Hoping a sort order will be added in a future version.

**Comment by Roasbeef** [comment]
I think we may flip the order before the final version of 0.5 is out,
agreed it's an unintuitive change.

On Sep 5, 2018 10:14 PM, "François" <notifications@github.com> wrote:

Yep that's a bit annoying to handle now, don't know how to do that in my
lnd web client.

Hoping a sort order will be added in a future version.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/1852#issuecomment-418967106>,
or mute the thread

**Comment by redstorm1** [comment]
adding --max_invoices 1000 returned the full list.
lncli --network=testnet listinvoices --max_invoices 1000

I use the rhash value for checking invoice settlement so just a minor issue when trying to view for me. but keeping track of how many invoices are in the system will be problematic. to know what to set max_invoices too 

When set to --max_invoices 0 (latest invoices are missing) i would have thought setting 0 would return all invoices...
