### ISSUE TITLE
Macaroon bug upgrading to .5

### ISSUE THREAD

**Issue by ZapUser77** [lightningnetwork/lnd#1903]
Just upgraded to version 0.5.

I read the patch notes that sim/test net macaroon locations were being changed, however I'm on mainnet.  "/home/pi/.lnd/admin.macaroon" is the current location of the macaroons.
The macaroons seem to be in the same place, however, now when I try to run ZAP, I get the error:

"Unable to connect to host: verification failed: signature mismatch after caveat verification" 

Which leads me to "If you delete the data directory which contains the macaroons.db file, this invalidates the admin.macaroon, readonly.macaroon and invoice.macaroon files. Invalid macaroon files give you errors like cannot get macaroon: root key with id 0 doesn't exist or verification failed: signature mismatch after caveat verification."

What is the proper way to recover from this?

**Comment by cfromknecht** [comment]
@ZapUser77 the default location of all macaroons has been updated to be in the chain specific directories w/in the data dir. The old macaroons in the top level data directory, e.g. `data/*.macaroon`, can be removed if you no longer need them.

Because `lncli` defaults to mainnet, only users of testnet and simnet will notice the difference _when no custom macaroon path is set_. If you use a custom macaroon path for `lncli` or Zap, it will need to be updated to point to the macaroons in `data/chain/mainnet`.

Was difficult to tell from the issue, but your data directory is still intact? I hope 😬

**Comment by ZapUser77** [comment]
Ok.  I found it.  .lnd/data/chain/bitcoin/mainnet.  
I specifically looked for a "data" directory under .lnd... but it somehow managed to evade me. 
Everything else looks intact.

Zap immediately crashes LND now "panic: runtime error: invalid memory address or nil pointer dereference"
But I'm sure that has to be a problem in Zap, not LND.

**Comment by cfromknecht** [comment]
Glad to hear! Keep us posted if any issues persist
