### ISSUE TITLE
[feature request] Discount for a specific channel

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#1995]
Is it possible to somehow discount specific channel when routing? E.g. if one connects his own mobile wallet to his node, then the node could avoid charging fees (100% discount) when the mobile wallet sends payments through the node.

**Comment by Roasbeef** [comment]
It's definitely possible, but not implemented yet. The tricky part is that the routing node would need to know that this is the mobile node routing through it. This can be done by giving it a sort of "cookie" within the onion blob for that hop. Adding an API to write to and read from the onion blobs is something that we'll be doing in order to implement AMP, so once that's done, someone can extend that and implement a feature like this.

**Comment by Kixunil** [comment]
Thanks for quick answer! Good point about onion. Maybe in case of direct connection, this would be easier? I'm mostly interested in that, but of course, a general solution might be cleaner.

**Comment by Roasbeef** [comment]
This is more of a protocol level thing, so closing.

**Comment by Kixunil** [comment]
I forgot about this completely, sending back is no longer a problem because Eclair mobile supports it and also I don't use Eclair mobile-LND setup anymore. :)
