### ISSUE TITLE
Connecting to lnd from docker-compose

### ISSUE THREAD

**Issue by ImmanuelSegol** [lightningnetwork/lnd#2100]
### Background
We are attempting to run integration tests with docker-compose.
On Linux, we successfully connect to lnd instances running in docker, but for some reason, the test on windows unsuccessfully connect to LND.

### Your environment

* Latest LND version.
* Windows 10 64bit, home.
* Latest btcd and ltcd nodes. 
* Docker toolbox latest version.

### Steps to reproduce
doceker-compose: [docker-compose file](https://github.com/dopetard/xchange/blob/master/test/integration/docker-compose.yml)
This sciprt runs the docker-compose : [script](https://github.com/dopetard/xchange/blob/master/docker/build-images.sh)
run: `npm run test:int`
these are the tests: [lnd test](https://github.com/dopetard/xchange/blob/master/test/integration/lightning/LndClient.spec.ts)
### Expected behaviour
Test should pass, test should be abble to conenct to LND

### Actual behavior
I get these errors:

`1) LndClient
       LndClients should connect:
     Error: Timeout of 30000ms exceeded. For async tests
and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\*****\Documents\Projects\walli-server\test\integration\lightning\LndClient.spec.ts)`

 `2) LndClient
       LndClients should fund get funds:
     Error: Timeout of 10000ms exceeded. For async tests
and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\****\Documents\Projects\walli-server\test\integration\lightning\LndClient.spec.ts)`

 `3) LndClient
       LndClients should open a channel to eachother:
     AssertionError: expected undefined not to be undefined`

**Comment by wpaulino** [comment]
I don't think this is the right place to report this as we don't support any of these files. If the test succeeds on other platforms, that would point to an issue with the test/docker setup on Windows itself. `lnd` should work just fine on all of the platforms that we provide releases for.

If you do happen to find that the culprit is some edge case _within_ `lnd` that only happens when running under Windows, we'd be more than happy to re-open this.
