### ISSUE TITLE
Make `RPCServer` gRPC methods context aware

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#2134]
The `RPCServer` within `lnd` acts as a `gRPC` server that serves clients such as `lncli`. Currently some of the long running methods in the `RPCServer` will keep executing until they finish or encounter an error, even though the client has canceled the API call.

We should make the `RPCServer` context aware, ceasing execution when the `gRPC` context is canceled.

## Steps to completion
1. Make the server properly listen for stream closes in case of streaming APIs, or context cancelation in case of non-streaming. 
2. Stop any long running task in case of cancelation, and clean up (more information: https://grpc.io/docs/tutorials/basic/go.html).

Companion issue: https://github.com/lightningnetwork/lnd/issues/2133

**Comment by mrwhythat** [comment]
@halseth should listening to stream closes/context cancellation be done manually on a per-handler basis (i.e. just add `case <-ctx.Done` for all `select` statements in RPC handlers)? Another option is to implement a generic task killing mechanism but since we can't normally kill goroutines in Golang, this will be too hacky and dangerous. Maybe there are other options I'm not aware of?

**Comment by halseth** [comment]
I was thinking more like the first option. For select statements within the `rpcServer` we should listen on `ctx.Done()`, while if we call into other (long-running) parts of LND, we should supply a `quit` channel.
