### ISSUE TITLE
No `FundingLocked` is sent from LND funded private channel

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#2273]
### Background

LND does not send a `FundingLocked` in a private channel where it is a funder, so channel never enters operational state. This does not happen when LND is a fundee.

When looking at message log while having an opening channel I see this (funding tx has 8 confirmations at this point):

```
<-- Init(,82)

--> ChannelReestablish(34d6ca2e25265c70abee4af7ad96f4d99d4804e9138586b33878805a1949cdd8,1,0,Some(0000000000000000000000000000000000000000000000000000000000000000),Some(02055c7176524bffc348d496980306d8687a1f2c3ca8e40498039421aae6c264ef))

<-- ChannelReestablish(34d6ca2e25265c70abee4af7ad96f4d99d4804e9138586b33878805a1949cdd8,1,0,Some(0000000000000000000000000000000000000000000000000000000000000000),Some(02967d09d22fdea3cdc26e1b34bd1ce6887bb91963be08299f522b67e18bf8b921))

--> FundingLocked(34d6ca2e25265c70abee4af7ad96f4d99d4804e9138586b33878805a1949cdd8,02348b6183f96595ab74364622c4553a0d6e30138cad80598e20be68c5c293626b)

<pings, gossip but no FundingLocked from LND>
```

### Your environment

0.5.1-beta commit=v0.5.1-beta-42-g668bd4db33b4c1ceb3b86836061e7faf99b3d080

### Steps to reproduce

Fund a private channel using LND.

### Expected behaviour

`FundingLocked` is sent by LND once funding tx gets enough confirmations.

### Actual behaviour

No `FundingLocked` is sent.

**Comment by juscamarena** [comment]
Here are the relevant logs on my end: http://paste.ubuntu.com/p/nZCms3RgQP/

**Comment by juscamarena** [comment]
Here's another similar channel with logs set to TRC near the end http://paste.ubuntu.com/p/sJ7GDHx53z/

**Comment by wpaulino** [comment]
Thanks @juscamarena!

> 2018-12-04 16:02:26.790 [INF] NTFN: New confirmation subscription: txid=d8cd49195a807838b3868513e904489dd9f496adf74aeeab705c26252ecad634, numconfs=1000
2018-12-04 16:02:26.790 [ERR] FNDG: Unable to register for confirmation of ChannelPoint(d8cd49195a807838b3868513e904489dd9f496adf74aeeab705c26252ecad634:0)
2018-12-04 16:02:26.790 [ERR] FNDG: waiting for funding confirmation failed

The reason for this is because `lnd` failed to register for a confirmation of the channel point due to attempting to register for 1000 confirmations. At the moment, `lnd` only allows registering for a maximum of 144. 

> 2018-12-04 16:02:26.138 [INF] FNDG: pendingChan(ec81dc9a10ca44993c815f0a894a93d91dfc2a21386a525a7ef18033f61138eb): remote party proposes num_confs=1000, csv_delay=1440

@btcontract is there a reason for BLW (I'm assuming this is the node on the other end) proposing 1000 confirmations to us? Seems a bit absurd IMO. Maybe just a bug?

We'll only resend `FundingLocked` once we know of the channel being confirmed, which explains why it's not being sent.

I believe if you restart the `lnd` node then everything should be fine.

**Comment by wpaulino** [comment]
#2275 will  prevent this from happening in the future.

@juscamarena if you'd like to keep this channel, I believe the following diff should be enough. Let me know otherwise.
```diff --git a/fundingmanager.go b/fundingmanager.go
index 2bf15789..9a729d14 100644
--- a/fundingmanager.go
+++ b/fundingmanager.go
@@ -1856,6 +1856,9 @@ func (f *fundingManager) waitForFundingConfirmation(completeChan *channeldb.Open
 		return
 	}
 	numConfs := uint32(completeChan.NumConfsRequired)
+	if numConfs > 100 {
+		numConfs = 3
+	}
 	confNtfn, err := f.cfg.Notifier.RegisterConfirmationsNtfn(
 		&txid, fundingScript, numConfs, completeChan.FundingBroadcastHeight,
 	)
```

**Comment by juscamarena** [comment]
Great, will try it out, thanks

**Comment by btcontract** [comment]
hurr durr yes it's a BLW bug. I've mixed up `htlcMinimumMsat` and `minimumDepth` in `AcceptChannel` which are `1000` and `1`.
