### ISSUE TITLE
sendcoins fails with amount in confirmed wallet balance

### ISSUE THREAD

**Issue by beedub** [lightningnetwork/lnd#2294]
### Background

```
ubuntu@ip-10-0-0-165:~$ lncli walletbalance
{
    "total_balance": "11257974",
    "confirmed_balance": "11257974",
    "unconfirmed_balance": "0"
}
ubuntu@ip-10-0-0-165:~$ lncli sendcoins <DEST> --amt 11257974
[lncli] rpc error: code = Unknown desc = insufficient funds available to construct transaction
```

### Your environment

* version of `lnd`
`a2c754a225a6e62cfca99a50a431e93e687bba74` from https://github.com/lightningnetwork/lnd/pull/2279
* which operating system (`uname -a` on *Nix)
`Linux ip-10-0-0-165 4.15.0-1010-aws #10-Ubuntu SMP Thu May 24 08:41:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend
`Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255`
* any other relevant environment details

### Expected behaviour

I can send all the coins in my wallet balance

### Actual behaviour

IT failed

**Comment by Roasbeef** [comment]
You need to factor in the fees, we'll soon have a `--all` flag to allow you to sweep all the UTXOs in a single transaction. See #2198.

**Comment by beedub** [comment]
That's what I figured. Where do I find the value of the fee so that I can subtract it from the amount to transfer?

**Comment by Roasbeef** [comment]
Atm, you essentially need to subtract an amount from the total until it all
sends. That PR I linked will take out the guess work.

On Dec 7, 2018 1:03 PM, "Brian Hahn" <notifications@github.com> wrote:

That's what I figured. Where do I find the value of the fee so that I can
subtract it from the amount to transfer?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/2294#issuecomment-445364764>,
or mute the thread
