### ISSUE TITLE
lnd --version returns no commit hash

### ISSUE THREAD

**Issue by Septem151** [lightningnetwork/lnd#2389]
### Background

running command `lnd --version` returns `lnd version 0.5.1-beta commit=`
commit hash is empty.

### Your environment

* version of `lnd` : 0.5.1-beta
* which operating system (`uname -a` on *Nix) : Linux 4.14.79-v7+ armv71 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend : Bitcoin Core Daemon version v0.17.1
* any other relevant environment details : Testnet blockchain not completely downloaded, have not started `lnd` service. Fresh install.

### Steps to reproduce

```
$ wget https://github.com/lightningnetwork/lnd/releases/download/v0.5.1-beta/lnd-linux-armv7-v0.5.1-beta.tar.gz
$ wget https://github.com/lightningnetwork/lnd/releases/download/v0.5.1-beta/manifest-v0.5.1-beta.txt
$ wget https://github.com/lightningnetwork/lnd/releases/download/v0.5.1-beta/manifest-v0.5.1-beta.txt.sig
$ wget https://keybase.io/roasbeef/pgp_keys.asc

$ sha256sum --check manifest-v0.5.1-beta.txt --ignore-missing

$ gpg ./pgp_keys.asc

$ gpg --import ./pgp_keys.asc
$ gpg --verify manifest-v0.5.1-beta.txt.sig

$ tar -xzf lnd-linux-armv7-v0.5-beta.tar.gz
$ sudo install -m 0755 -o root -g root -t /usr/local/bin lnd-linux-armv7-v0.5.1-beta/*
$ lnd --version
> lnd version 0.5.1-beta commit=
```

### Expected behaviour

running `lnd --version` should display commit hash.

### Actual behaviour

running `lnd --version` displays no commit hash.

**Comment by halseth** [comment]
Thanks for bringing this to our attention! 

This happens because the commit flag changed recently: https://github.com/lightningnetwork/lnd/blob/089d461552ffc05d7b1c22d603af0fa82e788e85/Makefile#L16

while the build script uses the old version: https://github.com/lightningnetwork/lnd/blob/089d461552ffc05d7b1c22d603af0fa82e788e85/release.sh#L31

An easy fix would be to update the build script to reflect what is done in the Makefile, but maybe we should instead use `make` commands when building releases?

**Comment by Septem151** [comment]
I’ll attempt to work on this issue but I should let you know that I’m very much a beginner in shell scripts, wish me luck!

**Comment by Septem151** [comment]
`COMMITFLAGS="-X main.Commit=$(git rev-parse HEAD)"`
Would changing to 
`COMMITFLAGS="-X build.Commit=$(git rev-parse HEAD)"`
fix this?

**Comment by Septem151** [comment]
Awww, I wanted to have my first contribution @Roasbeef  😞 Thanks though, awesome job !
