### ISSUE TITLE
Feature Request: Make on-chain transactions and addresses first class citizens

### ISSUE THREAD

**Issue by plwalters** [lightningnetwork/lnd#2498]
### Background

As an application developer if I want to integrate with Bitcoin but take advantage of the Lightning Network I can choose to build my application using LND only instead of a combination of the node implementation (btcd or bitcoind for ex.) and a Layer 2 client.  The problem is that there are a handful of RPCs and pieces of functionality that are missing in the LND implementation in regards to on-chain that make things a bit difficult -

1. Get list of wallet addresses - can be sourced through `listchaintxns` but includes change addresses, does not include inputs, etc...
2. Balance by Address - In bitcoind you can request for a balance of a managed or 'watched' address.  This is helpful when tying things like an address to an entity or integrating an accounting system.  This cannot be accurately determined in anyway that I can find thus far.

Potential other improvements

3. `SendCoins` or `SendMany` could allow constructing more details of the transaction (inputs possibly?)
4. `listchaintxns` could return inputs and tie the tokens to the outputs to better allow an accounting system to audit.

### Your environment

All environments

### Steps to reproduce

Not a bug, a feature request.

### Expected behaviour

Listed above

### Actual behaviour

Nothing

**Comment by priyanshiiit** [comment]
Hi @guggero @Roasbeef!

I would like to work on this issue.
I have gone through the related files - `rpcserver.go`, `btcwallet.go`, `walletkit_server.go` and understood the working of `listchaintxns` command.

I got to know that `ListTransactionDetails` is the main function where we are making a call to an instance of [btcwallet](https://github.com/lightningnetwork/lnd/blob/791411cdb85941001cb2af5f3ec5d47e97a5d19c/lnwallet/btcwallet/btcwallet.go#L1116) to get the transactions through the `GetTransactions` function. 

The [GetTransactions](https://github.com/btcsuite/btcwallet/blob/50ea8d1125561279f9c9af1e46bea16ca414b4a5/wallet/wallet.go#L2260) function returns transaction results between a starting and ending block. The return type - `GetTransactionsResult` contains fields `MinedTransactions` & `UnminedTransactions`. The field `MinedTransactions` is of the type `Block` which would return all the transactions of a block. It also contains transaction [summary](https://pkg.go.dev/github.com/btcsuite/btcwallet/wallet#TransactionSummaryInput) which could provide us **Inputs** & **Outputs** of different transactions.

Thus we could use these **inputs** and provide it to the users through an additional field - `InputAddresses`. 

Flow of changes in code - 

- Add field `InputAddresses` in `lnwallet.TransactionDetail` which is used as a return type of `ListTransactionDetails`
- Update functions(if any) affected due to addition of new field
- Update `minedTransactionsToDetails`, `unminedTransactionsToDetail` functions and fetch the input addresses as we did for [output](https://github.com/lightningnetwork/lnd/blob/791411cdb85941001cb2af5f3ec5d47e97a5d19c/lnwallet/btcwallet/btcwallet.go#L1013-L1024) addresses(DestinationAddresses)

Once this is done I'll look into getting the Balance by Address. :relaxed:

Looking forward to your suggestions.

Thanks!

**Comment by guggero** [comment]
Sounds good!

Though I think with `inputs` the original issue author didn't mean `InputAddresses` but the inputs that were spent. Those are usually referred to `PreviousOutPoints` in other contexts and should be an (ordered) list of `lnrpc.OutPoint`.
That information will then make it possible for an RPC user to chain together all wallet transactions.

**Comment by saubyk** [comment]
Hi @guggero give that this pr https://github.com/lightningnetwork/lnd/pull/6596 is merged, can we close this issue?
Also, this issue should be tagged with release 0.15.1 milestone
