### ISSUE TITLE
lncli newaddress is hanged

### ISSUE THREAD

**Issue by yaanhyy** [lightningnetwork/lnd#2645]
Hi:
Follow this article:
https://dev.lightning.community/tutorial/01-lncli/index.html

I run to  this step:
lncli-alice newaddress np2wkh
The cmd is hanged and cannot generate address.

**Comment by Roasbeef** [comment]
You need to ensure you mine enough blocks before that.

**Comment by MDrollette** [comment]
I've seen a couple people run into this problem (and ran into it myself). I believe the issue is that the tutorial asks you to generate an address before generating blocks (since you need a mining address) but you can't generate an address until there is at least 1 block because of this issue https://github.com/btcsuite/btcwallet/issues/594

I don't know what the correct solution is - either updating the docs to show how to generate blocks in a different way, or [fix the issue in btcwallet](https://github.com/btcsuite/btcwallet/pull/599) that's blocking NewAddress from returning when the blockHeight is 0.
