### ISSUE TITLE
routing: return nicer error message when routes fail due to the fee limit

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#2660]
Today when making a payment or requesting a route, a payment can fail if hits the specified _fee limit_. The default value is 100% (should definitely be lowered), so a routine payment of 1 satoshi can at times fail since many nodes (on testnet at least) enforce a 1 satoshi _base fee_. In order to make this error more actionable for users and also GUIs, [we should return a concrete error if path finding fails due to the fee limit](https://github.com/lightningnetwork/lnd/blob/master/routing/pathfind.go#L313). Atm, we just [let that error go, and attempt to move unto the next route](https://github.com/lightningnetwork/lnd/blob/master/routing/pathfind.go#L603). 

Related to #1662. 

# Steps To Completion 

- [ ] [In `findPath`](https://github.com/lightningnetwork/lnd/blob/master/routing/pathfind.go#L428), keep track of unexplored routes due to fee limit errors. 

- [ ] [If no route is found](https://github.com/lightningnetwork/lnd/blob/master/routing/pathfind.go#L736), then if all of our past errors were due to violating the fee limit, then return a new concrete error. 

- [ ] Amend the relevant RPC servers (and possibly sub-servers) to expose this new error to the caller.

**Comment by orbitalturtle** [comment]
Taking this

**Comment by joostjager** [comment]
@roasbeef I don't think it is as easy as the steps to completion suggest.
* Even if not all of our past errors were due to violating the fee limit, it could be that increasing the fee limit fixes the problem. There could for example be a channel temporarily unavailable error among them. 
* It could be that a route is unexplored because of the fee limit, but that increasing the fee limit would still yield no route, because there is for example no connection at all further down the route.

I think we need to think carefully about our options to provide better feedback.

**Comment by joostjager** [comment]
Also there may be multiple errors causing routing to fail. For example some routes failing because of the fee limit, others because of the cltv limit and a third set because of an outgoing channel restriction. Returning a single error wouldn't cover that situation.

**Comment by saubyk** [comment]
Can this issue be closed in-lieu of Attributable errors proposal (https://github.com/lightning/bolts/pull/1044)?

**Comment by saubyk** [comment]
Closing this issue, as it's better to build it based on feedback received from wallet and app developers
