### ISSUE TITLE
Configure NumConfs For SubscribeTransactions RPC

### ISSUE THREAD

**Issue by sbsends** [lightningnetwork/lnd#2688]
### Background

The SubscribeTransaction RPC currently returns two notifications per transaction. The first notification notifies the client of a pending transaction. The second notification notifies the client that the transaction has been confirmed. However, the current default for a confirmed transaction is just a single block instead of the standard six. 

### Your environment

lnd v0.5.1-beta
alpine linux
bitcoind v0.17.1

### Steps to reproduce

Connect to LND SubscribeTransaction RPC and submit a tx.

### Expected behaviour

Ideally the number of confirmations would be user configured and default to 6.

### Actual behaviour

LND defaults to a single block confirmation. I believe the confirmation value is hard coded.

### Additional Details

I tried setting "--bitcoin.defaultchanconfs", but that only effects channel confirmations.

**Comment by Roasbeef** [comment]
> instead of the standard six.

Six isn't the standard and instead is mostly arbitrary. You should scale the number of confirmations depending on your use case and the amount of BTC you're moving. I don't think we'll ever implement this as you can just query `ListTransactions` again for the number of confirmations, or yourself track the number of blocks since the initial notification.

**Comment by sbsends** [comment]
Okay, thanks for weighing in.

Closing.
