### ISSUE TITLE
`ReeRate` disparity in `ChannelUpdate` for private channel

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lnd#2771]
There's an LND <-> BLW private channel, LND sends a `ChannelUpdate(... BaseFee = 1000, FeeRate = 1)` on reconnect while LND node owner has confimred `FeeRate` is set to `10` locally.

When attempting to send a payment from tippin.me to BLW a site replies with `FeeInsufficient(... BaseFee = 1000, FeeRate = 10)` which is expected. But oddly enough, when I try to send a payment from another node it goes through fine with `FeeRate` set to `1` in payment request hint.

LND version: "version": "0.5.2-99-beta commit=v0.5.1-beta-805-ga6cf6f4237ef53b1f0c51c2fcfb9c1ce73cf9e06"

**Comment by wpaulino** [comment]
> When attempting to send a payment from tippin.me to BLW a site replies with FeeInsufficient(... BaseFee = 1000, FeeRate = 10) which is expected. But oddly enough, when I try to send a payment from another node it goes through fine with FeeRate set to 1 in payment request hint.

This is expected. In the first case, the node found and tried all possible routes to the destination, and ended up with a terminal error of `FeeInsufficient`. In the second case, it received the `FeeInsufficient` error, applied it to their graph, and tried again to succeed.

> There's an LND <-> BLW private channel, LND sends a ChannelUpdate(... BaseFee = 1000, FeeRate = 1) on reconnect while LND node owner has confimred FeeRate is set to 10 locally.

This is a bug that will be fixed by https://github.com/lightningnetwork/lnd/pull/2775.
