### ISSUE TITLE
Add fee-based cut-off within SendPayment of the ChannelRouter

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#278]
# Issue

Any attempts to send payments within the daemon is eventually routed through the [`SendPayment`](https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L976) method of the `ChannelRouter`. As it stands now, there are no fee-based cut offs during the path finding process. This means that it's possible, given a particular path and payment amount for the fees paid to exceed 100%. To guard against this, the user should be able to specify a fee-cut off, above which the send attempt is either suspend completely, or path finding short circuited. 

The fee cut-off can either be expressed in one or all of the following thresholds: 
  * Percentage based: "I will pay at most 2% to send payments.
  * Absolute cut-off: "Abandon the route if I would pay more in fees than the amount of the payment" 
  * Absolute with constant: "Abandon a route if it would pay more than X satoshis in fees"

# Steps to Completion 

- [ ] Extend the [`SendRequest`](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L442) proto to allow users to specify one of the cut-offs described above, or all of them. If the latter option is chosen, a `oneof` field might be of use. 

- [ ] Modify `SendPayment` to accept one of the three cut off types.

- [ ] The `newRoute` function should be modified to take in the new fee cut-off type. During route construction, the `TotalFees` fields should be checked at each iteration of the walk backwards within the path. If the threshold is exceeded, then the route should be abandoned.

**Comment by djseeds** [comment]
As long as someone else hasn't been working on this, I'd love to take this issue. I was using this issue as a self-study, but now I think I'm pretty close to finishing the implementation. I definitely need to write some tests, though, before PR.

**Comment by halseth** [comment]
Cool! Feel free to put up a pull request of your work (even though it is not ready for merge yet), to get some initial feedback 😄

**Comment by djseeds** [comment]
I believe I have found an issue in the current formulation of this proposed feature. Essentially, if a set of routes is [cached](https://github.com/lightningnetwork/lnd/blob/f20cb89982e0d9a66cf797383693241bf6c4acb5/routing/router.go#L951), `newRoute` is never called, so once again anything goes. This makes it possible for a route to succeed even if fees > maxFee.

For example, consider the route: Alice->Charlie->Bob, where Charlie charges a 5 sat fee.
Alice first attempts to pay Charlie 1000 sat with maxFee=10 sat. This obviously succeeds.
Alice then attempts to pay Charlie 1000 sat with maxFee=2 sat. Since the previous route is cached, this payment succeeds, even though fee > maxFee.

Is this the intended result?

**Comment by sebastiandelgado** [comment]
The last work on this issue is PR #320 which has been abandoned since Oct 20. This looks like a fun one and it doesn't seem to be implemented on master yet. I'm gonna give this a try if thats ok with everyone.

**Comment by djseeds** [comment]
Hey @sabastiandelgado, feel free to take this one. I think most of it is probably out of date, but the protos and tests may still be relevant. I had some concerns about how to handle the route cache, since it was not described in the issue. Things have probably changed since I’ve last looked at it though. Good luck!
