### ISSUE TITLE
peer: cache and display the last error(s) sent by a peer in listpeers

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3000]
Whenever a peer encounters an error, the [`Error` message](https://github.com/lightningnetwork/lnd/blob/master/lnwire/error.go#L64) is sent across. Today we lack any sort of error type, but in the future once we gain an error type, it may be a valuable source of information to diagnose cross implementation issues. We should start to show the last few errors sent/recv'd via the `ListPeers` RPC call so we can collect this data preemptively. 

# Steps To Completion 

- [ ] Store the last N errors sent/received to/from the peer within [the main peer struct](https://github.com/lightningnetwork/lnd/blob/master/peer.go#L106). 

- [ ] Extend the [`ListPeers` RPC call to also](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L1283) expose this new data. 

- [ ] Update the RPC server implementation to locate and populate this new error information.

**Comment by orbitalturtle** [comment]
Looking into this

**Comment by 1043465747** [comment]
https://github.com/lightningnetwork/lnd/issues/3000#issuecomment-488530417

**Comment by cfromknecht** [comment]
Note that I think to have this be effective, we'll want to carry the error across the lifecycles of different `peer` objects. In the `peerTeriminationWatcher`, we can then extract the errors from the prior `peer` and cache them in a map w/in the server. Once a new peer connects with the same pubkey, we can pass it the errors from the prior `peer` (and transitively all those before it). this will allow us to inspect errors of unstable peers. o/c, we will still want to have some FIFO policy on the errors retained so that the list doesn't become unbounded
