### ISSUE TITLE
[Question] lnwallet, btcwallet, key derivation mechanism. 

### ISSUE THREAD

**Issue by durkmurder** [lightningnetwork/lnd#3260]
I am checking lnwallet interface and I can see that it heavily depends on btcwallet. Looking through design of interface it seems that it's possible to implement another backend for lnwallet. I've seen that some initialization code for btcwallet is written in lnd.go, chainregistrey.go which breaks lnwallet interface usage, do you have some advice here? Will it be refactored in future? 

Also Problems arise with keychain/derivation.go, from observing the interface I can see that lnd expects raw private key. Is there any way to get rid of it? It breaks the idea of replacing btcwallet since you will need to expose private keys in keychain/derivation.go

If you see some inaccuracies in my questions I would be more then happy if you can correct those. Thanks in advance.

**Comment by halseth** [comment]
You are right that that parts of `lnd` is currently tightly coupled to `btcwallet` atm, but it should be possible to use another backend with some extra work... 

It might be refactored to more easily use with other wallets in the future indeed!

**Comment by matheusd** [comment]
One of the things I've done for our (decred's) lnd port and that I intend to follow up and improve upon is further abstracting of wallet and coin-specific stuff into packages/functions/whatever, so that it's easier to keep up with lnd's changes and so that code that needs to be decred-specific can live in a single location (with a possible long-term goal being just using lnd modules and plugging our specific drivers).

For example, see: https://github.com/decred/dcrlnd/pull/29 which moves wallet-specific stuff from `keychain` back into the wallet driver package.

If you guys are up for it, we can talk about back-porting these kinds refactors so we can make the core lnd more coin/wallet agnostic.

**Comment by durkmurder** [comment]
I am working on very similar stuff right now, once I will finish with different wallet backend, I will submit a PR that will contain initialization inside of modules not in a way that it's all over lnd.
