### ISSUE TITLE
ChannelBackup file changes on restart

### ISSUE THREAD

**Issue by gustavonalle** [lightningnetwork/lnd#3392]
I noticed that when stopping ```lnd``` for a few minutes and starting it again, the contents of
```~/.lnd/data/chain/bitcoin/mainnet/channel.backup ``` changes. 

Isn't it supposed to remain the same if the channels did not change? Why does it need to be written on restart?

**Comment by wpaulino** [comment]
It's written again in case there are any new addresses for our peers.

**Comment by gustavonalle** [comment]
So let's assume I have a week old backup file where one of the peers changed address but the channels haven't changed. How would that affect the recovery? Is the addresses saved in the static channel backup just a hint to speed-up things or is it essential?

**Comment by valentinewallace** [comment]
Recovery will still work because we get a peer's "fresh" advertised addresses before signaling them to force close the channel for SCB recovery.

**Comment by Roasbeef** [comment]
If they've changed addresses all together, then the initial attempt will pause until we obtain the more recent addressing information. You can speed this up at bit by restarting `lnd`, assuming you know _when_ the other peer has updated their info. The rest of the information provided in this issue is correct to some degree.
