### ISSUE TITLE
[Q]'pubkey string is empty' on openChannelSync of gRPC

### ISSUE THREAD

**Issue by char1yxok** [lightningnetwork/lnd#3404]
## Background
Hi. Thanks for looking my issue.
Using gRPC, the method 'openChannelSync' got an error.  
It says 'pubkey string is empty'.  
Below array is request content and I think 'pubkey string' means 'node_pubkey_string'.
What is the problem about this error?

{
  node_pubkey: 1,
  node_pubkey_string: '023a8dfe081c6bbd0504e599f33d39d17687de63023a8b20afcb59147d9d77c19d',
  local_funding_amount: 10000,
  push_sat: 0,
  target_conf: '',
  sat_per_byte: '',
  private: '',
  min_htlc_msat: '',
  remote_csv_delay: '',
  min_confs: '',
  spend_unconfirmed: ''
}

## Your environment

* LTND: Version: 0.7.1-beta
* MacOS X
* bitcoin.node=neutrino
* bitcoin.network=testnet

**Comment by Roasbeef** [comment]
The `OpenChannelSync` method was created only so users would be able to open channels using the REST interface. As a result, it only reads the hex-encoded pubkey strings. If you want to use `OpenChannelSync`, instead of `OpenChannel` (the streaming variant), then you'll need to pass in the hex encoded string.

**Comment by char1yxok** [comment]
OK, thank you.

Sorry for additional question.
Using 'openchannel' not 'sync', the error message 'amount pushed to remote peer for initial state must be below the local funding amount' appered in spite of I send 'local_funding_amount' is 100,000 & 'push_sat' is 0 (and also try 10 or 100).

What is the problem about this?
