### ISSUE TITLE
using --final_cltv_delta with --cltv_limit 

### ISSUE THREAD

**Issue by offerm** [lightningnetwork/lnd#3421]
Using 0.7.1

I have 3 nodes: A<>B<>C. Routing CLTV is 576.

Sending from A to C.

Route:
```
admins-MacBook-Pro-2:xud-simnet admin$ lndltc-lncli queryroutes 0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f 12001000 --fee_limit 100 --final_cltv_delta 576
{
    "routes": [
        {
            "total_time_lock": 53484,
            "total_fees": "12",
            "total_amt": "12001012",
            "hops": [
                {
                    "chan_id": "49436241808130049",
                    "chan_capacity": "225000000000",
                    "amt_to_forward": "12001000",
                    "fee": "12",
                    "expiry": 52908,
                    "amt_to_forward_msat": "12001000000",
                    "fee_msat": "12001",
                    "pub_key": "027dbb21be00a4cace0ce73761449f4d329cd400c08d556e2df4c65cf530c4e689"
                },
                {
                    "chan_id": "456297325658113",
                    "chan_capacity": "225000000000",
                    "amt_to_forward": "12001000",
                    "fee": "0",
                    "expiry": 52908,
                    "amt_to_forward_msat": "12001000000",
                    "fee_msat": "0",
                    "pub_key": "0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f"
                }
            ],
            "total_fees_msat": "12001",
            "total_amt_msat": "12001012001"
        }
    ]
}
```
Block height was 52332 which gives route cltv of 1152 (=576 *2). 
So far so good.

Trying to send a payment with --final_cltv_delta of 576 and --cltv_limit of 1152 fails. Have to add 3 extra blocks for the cltv_limit for this to work. Looks like a bug. Easy to reproduce.

```
admins-MacBook-Pro-2:xud-simnet admin$ lndltc-lncli sendpayment 0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f 12300000 bf40278dfc2aca9ded869c0a512f570c7c13f6139202358531fbc2dcfb440b2b --final_cltv_delta 576 --cltv_limit 1152
{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}
[lncli] unable to find a path to destination
admins-MacBook-Pro-2:xud-simnet admin$ lndltc-lncli sendpayment 0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f 12300000 bf40278dfc2aca9ded869c0a512f570c7c13f6139202358531fbc2dcfb440b2b --final_cltv_delta 576 --cltv_limit 1153
{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}
[lncli] unable to find a path to destination
admins-MacBook-Pro-2:xud-simnet admin$ lndltc-lncli sendpayment 0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f 12300000 bf40278dfc2aca9ded869c0a512f570c7c13f6139202358531fbc2dcfb440b2b --final_cltv_delta 576 --cltv_limit 1154
{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}
[lncli] unable to find a path to destination
admins-MacBook-Pro-2:xud-simnet admin$ lndltc-lncli sendpayment 0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f 12300000 bf40278dfc2aca9ded869c0a512f570c7c13f6139202358531fbc2dcfb440b2b --final_cltv_delta 576 --cltv_limit 1155
{
	"payment_error": "",
	"payment_preimage": "40a8ecf25647c5c68ec12da075731fad162dbede8e321d52062793ca001af2fb",
	"payment_route": {
		"total_time_lock": 53490,
		"total_fees": 12,
		"total_amt": 12300012,
		"hops": [
			{
				"chan_id": 49436241808130049,
				"chan_capacity": 225000000000,
				"amt_to_forward": 12300000,
				"fee": 12,
				"expiry": 52914,
				"amt_to_forward_msat": 12300000000,
				"fee_msat": 12300,
				"pub_key": "027dbb21be00a4cace0ce73761449f4d329cd400c08d556e2df4c65cf530c4e689"
			},
			{
				"chan_id": 456297325658113,
				"chan_capacity": 225000000000,
				"amt_to_forward": 12300000,
				"expiry": 52914,
				"amt_to_forward_msat": 12300000000,
				"pub_key": "0270e8254e07649cdde230c9e09de6ff63c28a6d275c30b0a6863028d9db0e7c6f"
			}
		],
		"total_fees_msat": 12300,
		"total_amt_msat": 12300012300
	}
}
```

Detected by @sangaman

**Comment by cfromknecht** [comment]
Yes this recently changed because we'll now add three blocks to the required CLTV delta to avoid any race conditions with blocks being mind while a payment is in flight #3339

**Comment by sangaman** [comment]
> Yes this recently changed because we'll now add three blocks to the required CLTV delta to avoid any race conditions with blocks being mined while a payment is in flight #3339

It seems counterintuitive though that if we query a route with a total CLTV delta of X, calling `SendPayment` with X for `CltvLimit` won't be able to use that route.

Maybe we should also be adding the `BlockPadding` to the `TotalTimeLock` that we get back from `QueryRoutes`?

**Comment by cfromknecht** [comment]
@sangaman yeah the primary use case of `--cltv_limit` is to limit gross over-exposure to timelocks, rather than trying to constrain `sendpayment` to a particular path you have in mind (or one informed by `queryroutes`), but adding a small buffer should allow `sendpayment` some extra freedom in finding paths and applying its additional heuristics. if the goal is to use that exact path, then `sendtoroute` is probably the call you want

**Comment by sangaman** [comment]
Right, I see what you're saying. The use case we're thinking of was to use `QueryRoutes` to see what the total time lock of the first route chosen would be, and then limit ourselves to that total time lock but not necessarily *that route*, as there might be other routes available to try with equal or lower total time lock should the first route fail.

It's not a big deal, but personally it confounded me for a while when `SendPayment` with a `cltvLimit` of X would fail due to no route found when I knew there was a route with a total cltv delta of X. Maybe this could simply be clarified somewhere on the API documentation?

**Comment by cfromknecht** [comment]
> It's not a big deal, but personally it confounded me for a while when SendPayment with a cltvLimit of X would fail due to no route found when I knew there was a route with a total cltv delta of X.

Can definitely see how that would be confusing :) during the process of adding #3339, we considered doing this also for `queryroutes`. It seemed clear that we wanted to add it to `sendpayment` since that is more of one-stop-shop where you call it and it just works. The ultimate decision was to leave `queryroutes` unmodified since it is a lower level API, where users might add things like block padding themselves. However this doesn't preclude it's addition in the future, mostly we're just still considering how best to expose it.

> Maybe this could simply be clarified somewhere on the API documentation?

Agreed his could certainly be better documented!

**Comment by Roasbeef** [comment]
Closing as the core issue seems to have been resolved, we're open to PRs to improve the documentation.
