### ISSUE TITLE
ChannelAnnouncement not sent  for fee changes

### ISSUE THREAD

**Issue by gustavonalle** [lightningnetwork/lnd#3447]
Using ```v0.7.1-beta-64-g6e43974d378ab70583cbae51a907d1d58d19258f```

I changed the ```basefee``` and ```feerate```  for all my public channels both in the cfg and also in the cli by doing 
```lncli updatechanpolicy --base_fee_msat 0 --fee-rate 0``` but I can't see any change in public explorers for those channels.

Should channel announcements have been sent? Do I need a restart?

**Comment by peername** [comment]
Using zero fees is dangerous. The fee is protecting you from infinity loops. So I guess it doesn't let you set a zero value.

Use something standard like:
lncli updatechanpolicy --base_fee_msat 1000 --fee_rate 0.000001 --time_lock_delta 144

**Comment by gustavonalle** [comment]
I was just testing, not planning in using zero fees forever. The fact is the channel updates are not sent, either by changing the config, using the cli or restarting...
The only way I could see my fee changes reflect in the network was opening another channel...

**Comment by wpaulino** [comment]
> lncli updatechanpolicy --base_fee_msat 0 --fee-rate 0 but I can't see any change in public explorers for those channels.

Explorers are not a source of truth. Updates can take time to propagate throughout the network due to the gossip sync mechanism we have in place.

Running the `lncli updatechanpolicy` command should prompt the updates to be sent over the network. This doesn't include channel announcements as we assume the channel has already been announced. You can confirm this by setting the `PEER` log level to `debug`.

**Comment by Roasbeef** [comment]
A channel announcement won't be sent, instead a `ChannelUpdate` will be. The zero fee issue will be fixed in #3439.
