### ISSUE TITLE
Manifest signature missing for 0.8.0-rc2

### ISSUE THREAD

**Issue by dhedberg** [lightningnetwork/lnd#3580]
manifest-v0.8.0-beta-rc2.txt.sig seems to be missing from the assets for this release.

**Comment by molxyz** [comment]
@dhedberg  It's not an official stable release but a testing release.  "rc" means "release candidate" to test until the version is stable for sure before it becomes a "Release". If more bugs discovered we will see rc3. So, unless you want to test this version, just stick with the current released version which is 0.7.1.

**Comment by dhedberg** [comment]
@molxyz  I don't see what that has to do with anything? There's a .sig-file for the first release candidate.

**Comment by molxyz** [comment]
@dhedberg Ah I see.. Probably because roasbeef's key has been expired. If it's not possible to verify the sig not sure why the guide is there.  Another way to run this RC is to compile from source which is what I always do. And now we can do the deterministic build, there should be a guide for this.

**Comment by wpaulino** [comment]
Thanks @dhedberg, should be there now.
