### ISSUE TITLE
Add anchor output to the commitment transaction

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#3587]
In the current commitment format, the miner fee is negotiated through the `update_fee` message. This creates several complications:
* It is currently not possible to reject a fee rate. The only option at that point is to force close the channel. Nodes may have different sources for fee estimation and may unintentionally disagree about the fee to use.
* Even if a satisfactory fee has been negotiated, it may turn out not to be enough to get it confirmed when one of the parties actually goes to chain. The party that publishes the commitment tx has its `to_local` output timelocked and can't use that to cpfp the transaction.

A possible solution (originally proposed by @halseth on the [lightning-dev mailing list](https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-January/000943.html)) is to add a so called anchor output to the commitment transaction. This is a non-timelocked output that can be used to cpfp the transaction in order to get it confirmed. 

With the anchor output present, the fee on the commitment transaction itself can be minimal as both parties have the opportunity to attach additional fees.

**Comment by halseth** [comment]
Ideally we would have a no-fee commitment transaction, and add all fees using CPFP, but that would probably require something like package relay in order to ensure propagation: 
https://github.com/bitcoin/bitcoin/issues/14895
https://github.com/bitcoin/bitcoin/pull/16401

Having a "minimal but sufficient fee" for propagation on the commitment should therefore be the goal. We might have to keep fee negotiation using `update_fee` for now, to ensure that we have this sufficient fee during fee spikes. This will still leave the first issue in the list above though.

**Comment by Roasbeef** [comment]
Fixed by #3829.
