### ISSUE TITLE
[Feature request] Show cipher seed

### ISSUE THREAD

**Issue by otaviobps** [lightningnetwork/lnd#3608]
I searched some issues and found out that it's not possible to show the wallet cipher seed again after wallet creation.

I lost my cipher seed (I know, dumb mistake). My node was supposed to be just a test and became a really well connected node, I don't want to close all channels and create a new wallet.

It would be nice to have a rpc command to show the cipher seed again. This could be used for wallets as well to show to users the seed if needed.

Thanks

**Comment by guggero** [comment]
The wallet does not know the seed. When the `wallet.db` is created with the `lncli create` command, you enter the 24 words but they aren't stored. The seed is instead hashed and a BIP32 HD root node is created and stored (encrypted) in the database.
And because of the hashing you can't find out the original seed any more.

But since all addresses are derived from the HD node, this is enough to get all your private keys (otherwise the lnd wallet wouldn't work).
I created a PR that allows you to show/export the HD root node: https://github.com/guggero/lnd/tree/lnwallet
Unfortunately you can't import or use that to create a new wallet. But at least you can store it somewhere and it allows you to derive all private keys that hold your funds in lnd.

**Comment by Roasbeef** [comment]
Users must write down their seed, it's their responsibility to secure it. If you've lost your seed, then migrate to a new wallet.
