### ISSUE TITLE
x509: ECDSA verification failure, used to work just fine...

### ISSUE THREAD

**Issue by dognip** [lightningnetwork/lnd#3678]
### Background

I've been running a node for quite sometime now via stadicus raspibolt raspberry pi guide. I haven't done anything with it in almost a month (I updated it back when the security patch was required) and today upon trying to check up on it I received this error:

lncli channelbalance
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"ABC_DEF\")"

I have not changed anything, and do not know why this would have occurred. In order to fix the issue I attempted rebooting and upgrading from LND 0.7.1 beta to 0.8.0.

### Your environment

* version of `lnd`: Currently 0.8.0, but issue occurred on 0.7.1
* which operating system (`uname -a` on *Nix): Linux ABC_DEF 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend bitcoind "subversion": "/Satoshi:0.16.3/",
* followed https://stadicus.github.io/RaspiBolt/

### Steps to reproduce

lncli getinfo debuglevel channelbalance walletbalance etc. most commands throw the same error

### Expected behaviour

commands to work

### Actual behaviour

It throws this error
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"ABC_DEF\")"

**Comment by guggero** [comment]
This is very likely because the certificate is now expired. The expiration time is 14 months which sounds plausible in your case.
I know the error message is not very useful in this case. It should say "certificate expired" instead of "unknown authority".

You should be able to fix the problem by deleting `tls.cert` and `tls.key` in your lnd data folder. After a restart of lnd a new certificate will be created.

**Comment by dognip** [comment]
Hi guggero. I rm'd both the tls.cert and tls.key, then restarted the node. When I first attempted a command i got:

lncli walletbalance
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

on second attempt:
lncli walletbalance
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"ocn_lnnode\")"

It is remaking both files, which are contained in the same folder as my lnd.conf.

Any other help is appreciated, thanks!

**Comment by guggero** [comment]
Hm...
The first error was probably just because you tried too early and the node was still starting.
The second error is strange. Maybe something with the hostname?

Can you please post your `lnd.conf` and the new `tls.cert` that was generated?
And are you sure `lncli` is using the new certificate? Maybe there is an old file somewhere?

**Comment by dognip** [comment]
Hi guggero. Thanks for your help, your intuition was correct, I had an older file in a different directory.  I deleted all copies and restarted. When I restarted it could not find the file, as it was looking at location 1, so I had to move the created tls files from location 2 to location 1 and it worked. My question is, how do I get lnd to create them in location 1, where I expected them to be..

Thanks!

**Comment by molxyz** [comment]
@dognip How did you create the data directory for .lnd? Are you using some raspi guide that creates mutiple locations and gives you a user named "bitcoin"? I've seen this quite often, those guides confuse users.  Maybe take a look at how the data folder was set up at the start.

**Comment by guggero** [comment]
By default, the data directory is set up in `/home/<username>/.lnd`.
So it depends on which user you start the application with. Is it possible you mixed up the two users `admin` and `bitcoin`?

**Comment by willebra** [comment]
Wanted to just note that I had the same issue and reading this helped me solve my issue. My certificate had expired; and I just needed to delete the tls.cert and tls.key files; and then copy the tls.cert to the .lnd directories of both the users that my setup uses. 

The hardest part was finding this discussion, but searching directly here helped. (Perhaps my commenting raises this for others, I guess there must be a growing number of people who have had their lnd nodes running for about 13 months or so).

**Comment by carlaKC** [comment]
>My question is, how do I get lnd to create them in location 1, where I expected them to be..

@dognip you can run lnd with `--tlscertpath` to specify the directory you want the cert to be created in :)

**Comment by mjslawson** [comment]
`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"ABCDEF\")"`

I found a similar issue on https://github.com/lightningnetwork/lnd/issues/3780

My issue persisted after regenerating the tls.cert and tls.key.  To resolve, I copied the newly regenerated `/home/bitcoin/.lnd/tls.cert` to `/home/admin/.lnd/tls.cert` and restart `lnd`

**Comment by guggero** [comment]
This sounds more of an issue with how RaspiBlitz sets up its users and directories. If `lnd` is running under the `bitcoin` users, then it will re-generate the certificates there (`/home/bitcoin/.lnd`). Buf if you use `lncli` with the `admin` user, then `lncli` will look in `/home/admin/.lnd` for the cert.
