### ISSUE TITLE
LND mis-implements gossip_queries

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lnd#3728]
### Background

c-lightning has started sending errors to LND nodes because of their `reply_channel_range` answers for large queries.

Tested against @bitconner's node.

### Steps to reproduce

We send 01076fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d61900000000000007b2b400018402 which is:

```
QUERY_CHANNEL_RANGE:
chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
first_blocknum=504500
number_of_blocks=99330
```

LND replies with four messages (because of non-zlib):

```
REPLY_CHANNEL_RANGE:
chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
first_blocknum=504500
number_of_blocks=99330
complete=0
...
REPLY_CHANNEL_RANGE:
chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
first_blocknum=504500
number_of_blocks=99330
complete=0
...
REPLY_CHANNEL_RANGE:
chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
first_blocknum=504500
number_of_blocks=99330
complete=0
...
REPLY_CHANNEL_RANGE:
chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
first_blocknum=504500
number_of_blocks=99330
complete=1
```

These responses are incorrect.

### Expected behaviour

There are two problems: first, the range of blocks is wrong, second, the complete flags is wrong.

From the spec:

```markdown
  - MUST respond with one or more `reply_channel_range` whose combined range
	cover the requested `first_blocknum` to `first_blocknum` plus
	`number_of_blocks` minus one.
  - For each `reply_channel_range`:
    - MUST set with `chain_hash` equal to that of `query_channel_range`,
    - MUST encode a `short_channel_id` for every open channel it knows in blocks `first_blocknum` to `first_blocknum` plus `number_of_blocks` minus one.
    - MUST limit `number_of_blocks` to the maximum number of blocks whose
      results could fit in `encoded_short_ids`
```

You do not limit `number_of_blocks` to the maximum number of blocks which fit in the `encoded_short_ids` field, but instead, reuse the same value.  The intention was that you return (non-overlapping, though that is not stated) `first_blocknum` + `number_of_blocks` ranges.  Instead you return the same number over and over, which is wrong.

Secondly:

```markdown
    - if does not maintain up-to-date channel information for `chain_hash`:
      - MUST set `complete` to 0.
    - otherwise:
      - SHOULD set `complete` to 1.
```

`complete` is NOT an end marker.  It is used to indicate a lite node (or node bootstrapping) which doesn't have full gossip information.

### Actual behaviour

Eclair and c-lightning now need to figure out how to detect and mitigate this for now, and make sure we test protocol compatibility properly in the future!

**Comment by Roasbeef** [comment]
Thanks for reporting this! We should have the fix for setting the block related fields properly in our next release (0.9). However the fix for our usage of `complete` will take longer to roll out, since our nodes today use that as a termination signal. Based on my current understanding, we only need to fix the block fields in order to achieve better compatibility amongst us all, since the `complete` flag as defined in the spec is more or less just advisory. 

What does CL use the `complete` flag for _today_? Will it take that as a signal to keep querying other nodes until they find one w/ the flag set? Looking back, if this was actually how it was intended to be used (signal partial storage of the channel graph), then we should've added a global feature bit (in the node announcement), as otherwise you only find out I don't have all the data when I'm queried.

**Comment by araspitzu** [comment]
I reproduced this in testnet with the latest eclair from `master` and LND latest release v0.8.1-beta. From the eclair side i sent a `query_channel_range` with `first_blocknum=0` and `number_of_blocks=2147483647`, LND replied with 2 `reply_channel_range`:
```
reply_channel_range first_blocknum=0 number_of_blocks=2147483647 complete=0 <-- 8000 SCIDs
reply_channel_range first_blocknum=0 number_of_blocks=2147483647 complete=1 <-- 737  SCIDs
```
The issue seem to lay out pretty much as @rustyrussell describes it, with the main difference that eclair is actually more forgiving than c-lightning and it ends up being able to sync from LND, i performed a full sync from both the LND node and [endurance](https://1ml.com/testnet/node/03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134) and the resulting routing tables are almost identical, with the exception of the number channel announcements but this might be because of different heuristics for flappy channels.

**Comment by Roasbeef** [comment]
Half the fix can be found here: https://github.com/lightningnetwork/lnd/pull/3785

This doesn't effect any `lnd` clients in the wild, but _should_ help existing c-lightning clients in the wild. As for our usage of the `Complete` field as I mentioned above, we likely won't change it for a version or two as we depend on it currently (knowing when to process the chunks). Also AFAICT, no one actually does anything with the `Complete` field as its defined in the spec today?

**Comment by cfromknecht** [comment]
Reopening until completed flag is properly fixed
