### ISSUE TITLE
htlcswitch: reject self-loop HTLC forwarding attempts 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#3771]
Circular routes in the protocol have many use cases as is today, such as rebalancing ones channels. However, they can also be used for nuisance activities such as saturating a channel with HTLCs. In the future, there're plans to extend the protocol to make these nuisance activities no longer costless. However, until these changes are rolled out, there're a number of low-hanging mitigations we can put in place. One such mitigation is: rejecting self-loop HTLC forwarding attempts. I refer to self-loops as instances wherein a nodes receives a an HTLC with payment hash `W` over a link, then forwards out the HTLC `W` over the outgoing link, only to receive that same HTLC `W` over another link. This link may even be the very _same_ link that was the target outgoing/incoming link. See [this paper for a formal treatment of this precise attack](https://eprint.iacr.org/2019/1149.pdf). 

# Steps To Completion 

- [ ] The [`CheckHtlcForward`](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/link.go#L2119) method should be updated to reject _all_ HTLCs which are already present on the commitment transaction of the target link. This prevents us from cooperating with an attempt self-loop.

**Comment by carlaKC** [comment]
I've been working in this part of the code base recently so I'd like to pick this up. 
Just wondering what failure message we'd send back to the peer on the wire for this kind of check? `TemporaryChannelFailure`?

From my understanding, there are two mitigations that we could implement, given nodes A and B:
1. Prevent loops on the same link (as described in steps to completion, can be done in `CheckHTLCForward`, seems straightforward)
```
+----+-----------------+----+
|  A |   HTLC(W) --->  |  B | 
|    |  <---- HTLC(w)  |    |
+----+-----------------+----+
```
2. Prevent loops that are incoming on one channel link and outgoing on another, probably a bit more complex, and would need to be handled on switch level.
```
+----+-----------------+----+
|  A |   HTLC(W) --->  |  B | 
|    |-----------------|    |
|    |  <---- HTLC(w)  |    |
+----+-----------------+----+
```

Thinking of going ahead with (1) for now and then we can consider (2)?

I can't think of many uses for looping HTLCs back to yourself in the same channel in the wild, but I think that the solution for (1) should be configurable just in case somebody has a use case out there? Enabled by default, with the option to disable in case issues arise?

**Comment by alexbosworth** [comment]
I use this for sloshing

**Comment by carlaKC** [comment]
> I use this for sloshing

What is sloshing?

My plan for this would be to make your own payments immune to this check, because looping through your own node is ok. If it's from another node, I'm also going to add the ability to disable this protection, so that people can make the trade off between custom use cases/ security. 

I've been thinking about (2) some more, and I'm worried that it may be an issue for base mpp. If your node is along a mpp route, you could easily end up with multiple htlcs with the same hash, which would look a lot like a liquidity attack if they arrive/ leave on different channels. 

The only countermeasure I can think of is to disallow forwards through the same channel pair in the opposite direction. Eg, if you're node B in an `A-B-C` setup, and you've forwarded `HTLC(W)` through `A -> B -> C`, you do not allow a htlc with the same hash to be looped back through `A <- B <-C` since I'd imagine mpp payments going is different directions are less likely. This may not be worth the effort, since it's probably pretty easy to work around, will have another look at the paper and see whether it will have any material impact.

**Comment by alexbosworth** [comment]
Operationally I need to move funds from node a to node b so I do this through a circular payment

**Comment by carlaKC** [comment]
This would only affect circular payments which arrive and leave on the same channel, and will be configurable, so shouldn't disrupt that.

**Comment by alexbosworth** [comment]
Cool ok

**Comment by Roasbeef** [comment]
Resolved by #3915.

**Comment by alexbosworth** [comment]
It does seem to disrupt my above use case

**Comment by carlaKC** [comment]
> It does seem to disrupt my above use case

Do you move funds over the same channel? If so the node that you need to loop the payment through needs to be run with `allow-circular-route`.
