### ISSUE TITLE
Unable to connect to peers

### ISSUE THREAD

**Issue by sci4me** [lightningnetwork/lnd#3791]
### Background
I have recently re-setup my LND node that hasn't been running for eight months straight. I still had `~/.lnd` so getting things up and running was easy enough.
However, my node appears to be perpetually stuck in some weird state where it thinks it's not synced with the chain but it actually is, and this is preventing me from being able to connect to any peers or really do anything.

### Your environment

* lnd version 0.8.0-beta commit=v0.8.1-beta
* Linux SciPi 4.19.86-v7l+ #1283 SMP Fri Nov 29 18:37:40 GMT 2019 armv7l GNU/Linux
* Bitcoin Core version v0.19.0.1 

### Steps to reproduce
No idea. Make a node, stop running it for two thirds of a year, and restart it? That's exactly what I did. (Well, and don't forget to update it)

### Expected behaviour
After the node finishes syncing to the blockchain it seems to me that I should be able to connect to peers. This is implied by the error message shown below. This is not the case though.

### Actual behaviour
When I run `lncli connect` I get this:
```
[lncli] rpc error: code = Unknown desc = chain backend is still syncing, server not active yet
```

However when I run `lncli getinfo`, I get this:
```
{
	"version": "0.8.0-beta commit=v0.8.1-beta",
	"identity_pubkey": "02a9556ab0ce20a1e2292b684d620a3bfe4fccdd6e2a1799f753b57ffc783cd890",
	"alias": "sci4me_1",
	"color": "#ff0000",
	"num_pending_channels": 0,
	"num_active_channels": 0,
	"num_inactive_channels": 34,
	"num_peers": 0,
	"block_height": 606699,
	"block_hash": "000000000000000000103462cf4b39e549f9eba8519ccd9be14004cea39ac8a4",
	"best_header_timestamp": 1575505532,
	"synced_to_chain": true,
	"synced_to_graph": false,
	"testnet": false,
	"chains": [
		{
			"chain": "bitcoin",
			"network": "mainnet"
		}
	],
	"uris": [
		"02a9556ab0ce20a1e2292b684d620a3bfe4fccdd6e2a1799f753b57ffc783cd890@74.140.67.51:9735"
	]
}
```

Either the error message, the `getinfo` results, or both, are misleading/wrong. One claims I am synced to the chain while the other claims I am not. 

I have not attached any logs yet as I don't know what to be looking for.
The consequence of this problem is that I have no access to my Lightning BTC :sob: 
Hopefully this is an easy fix on my end.

**Comment by cfromknecht** [comment]
@sci4me how long has the node been running since you started it? it will take a fair amount of time to catch up on 8 months, i would just let it run its course and i suspect that will resolve it.

the reason the messages seem to conflict is because the server is separate from the rpcserver. the server spins up a whole bunch of subsystems, some of which block full operation of the node until they are caught up. only once all of the subsystems have given the okay will the server allow incoming or outgoing connections (we don't want to handle messages from peers until we think we're caught up).

however, the rpcserver is started before the server, to a allow a limited subset of the endpoints to be queried, e.g. getinfo, even if the server's subsystems are still catching up. much of the info populated in getinfo is queried from the backend or onchain wallet (which is started even before both rpcserver and server). essentially, the _backend_  is synced, but we're waiting for lnd to ingest that data from it before we continue.

**Comment by sci4me** [comment]
@cfromknecht I've had the node running for a couple of days (although not without a couple restarts here and there). The current uptime is just below 48 hours.

Thanks for the info. That does help, although I would assert that the `lncli` output should be made less misleading.

**Comment by sci4me** [comment]
This appears to be a non-issue. :)

**Comment by cfromknecht** [comment]
@sci4me glad everything is resolved, definitely agree we can improve the error messages. Then again, restarting after 8 months is pretty uncommon, but it would be nice to handle the situation gracefully and be more descriptive in how users should proceed :)
