### ISSUE TITLE
Cosmetics: Missing newline in "Shutdown complete" log message

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#3801]
After shutdown, lnd logs "Shutdown complete" without a trailing newline. Upon restart, the line continues:

`2019-12-05 22:39:18.593 [INF] LTND: Shutdown complete2019-12-05 22:39:39.821 [INF] LTND: Version: 0.8.2-beta commit=v0.8.0-beta-386-gf3398c0c0ecc469c31e1f7e18e0fa2d63b5729ed, build=production, logging=default`

**Comment by ellemouton** [comment]
I would like to take this one if no one has yet :)

**Comment by ellemouton** [comment]
I just had a look at this issue again. It looks like the problem comes from the line of code that reads "err := logWriter.Close()" in the lnd.go Main function. It seems that this line of code trims any new-lines in the log file which is what is causing the error. The only way I have been able to produce the correct log file result is by adding the line "ltndLog.Info("")" after the line "ltndLog.Info("Shutdown complete")" as shown in the code below:

`defer func() {
		ltndLog.Info("Shutdown complete")

		// Add new line to log because "logWriter.Close()"" trims newline in the log after the "Shutdown complete" message
		ltndLog.Info("")

		err := logWriter.Close()
		if err != nil {
			ltndLog.Errorf("Could not close log rotator: %v", err)
		}
}()`

However, I know that this fix seems a bit naive so I am not sure if I should submit a PR with this solution. Would love some feedback/tips.

**Comment by guggero** [comment]
Fixed by #4793.
