### ISSUE TITLE
Unclear/inconsistent handling of bools in lnd.conf

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#3810]
### Background

It is unclear which boolean values in lnd.conf can be specified as `0`/`1` or `true`/`false`. 

### Your environment

Irrelevant

### Steps to reproduce

1. Open the [sample conf file](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf)
2. Find semantically boolean values (e.g. `nat` and `nobootstrap`)
3. See that there are inconsistent example values `true` and `1`
4. see that there's no explanation at the top of the sample

### Expected behaviour

One of these possible explanations written at the top of the config file:

* All boolean values might be specified with `true`/`false` or `1`/`0`
* Some boolean values must be specified as `true`/`false`, others as `1`/`0` - see the examples.

### Actual behaviour

It's unclear whether the values can be mixed.

Note: This is mainly important for systems that automate config generation.

**Comment by wpaulino** [comment]
Either `0`/`1` or `true/false` can be used.

**Comment by CrashOverride1987** [comment]
I'm unsure of what you're asking. But from what I "can" tell it seems you're asking if true is counted the same as 1 and false is counted as 0? And if you can mix and match the values? I've honestly never tried to mix and match the values, because logically I would just use whatever value I know I assigned to the value. I tend to code a bit uniform. I rarely use 1 in place of true. For some reason I always prefer true/false over 1/0. Just because issues can arise when you're coding a program where you're using boolean, string and numbers all in the same program. It helps me to be organized in that manner I suppose. It would also depend on what your code is looking for. If it is looking for true/false or 1/0. It's my understanding that they are treated the same, in a manner of speaking. Though I'm not 100% positive, but I don't think that you can mix and match the values. Could be wrong though.

**Comment by Kixunil** [comment]
Yes, I was asking for clarification, the PR that fixed it fixed it for me. :)
