### ISSUE TITLE
lnd sending unexpected response

### ISSUE THREAD

**Issue by manakill** [lightningnetwork/lnd#3885]
### Background

I noticed this issue using RTL and opened an issue there related to my Events Totals when time frame filter is changed. 

"@manakill, after comparing your shared logs, it looks like LND is not sending the expected response for your queries.
To confirm, we can compare rtl.log's data from line 129 and line 132. First query is to get approx. a week's history and second is for a month. Within 1 week, channel "669379380597882881" has been used 12 times to send outbound payments but the monthly result only shows 1 event for the same. We can see differences between almost, all event totals."

See full issue and logs: https://github.com/Ride-The-Lightning/RTL/issues/212

### Your environment
version of lnd - 8.1
operating system (uname -a on *Nix)- nodl Linux
Bitcoind 180100

### Steps to reproduce

I found it by using RTL > Routing Peers
to see the events and change the time frames

### Expected behaviour

1 month >= 1 week totals

### Actual behaviour

Less events on longer time frame.

**Comment by ShahanaFarooqui** [comment]
@carlaKC and @Roasbeef, we use LND’s REST services in RTL application. RTL can be removed from the layer, if needed. The same response will be received from the rest api itself.

**Comment by carlaKC** [comment]
RTL is querying the `ForwardingHistory` endpoint once, when it should be querying until `index_offset` < `num_max_events` because the response is paginated. Nodes that have more than the default of 100 forwarding events over a period will not display the correct set of events (in this case, 1 week < 100 so it's ok and 1 month > 100 so there's an issue). 

I managed to replicate this locally, so closing this issue for now and continuing conversation on the RTL issue.
