### ISSUE TITLE
push-amt not shown as an invoice?

### ISSUE THREAD

**Issue by nicolasburtey** [lightningnetwork/lnd#4019]
Alice wants to pay Bob 100k sats, but realize there is no path, so Alice decided to open a channel with Bob with a push-amt of 100,000:

`lncli openchannel bob-key 200000 100000`

After the channel is opened, Bob can see his fund with `lncli channelbalance` but Bob don't really have a way to easily figure it out where the money comes from. 

If Bob do a `lncli listinvoices` there is no apparent invoice that would explain the change in balance. This would be the expected behavior like for a keysend?

Or what is the right way to do a per transaction accounting for funds that are sent with push-amt?

**Comment by wpaulino** [comment]
The push amount becomes the remote party's initial balance in the channel, there isn't really a record for it other than it being the channel's initial state. One thing Bob could do now is receive a notification for when the channel is opened and inspect the channel state. If there aren't any updates and Bob has a balance, then it was pushed to them. This can be somewhat racy though if an actual payment is attempted right after the channel is opened, as the payment could settle before Bob has a chance to check the initial channel state.

**Comment by nicolasburtey** [comment]
I guess the challenge is, a wallet developer, how do you show to the user where those sats come from. The sum of the payments and invoices would not be equal to the balance.

**Comment by nicolasburtey** [comment]
I have to check, but I would guess the transaction would not appear on sendpayment for the other node neither

**Comment by halseth** [comment]
cc @carlaKC on accounting for push amts

**Comment by carlaKC** [comment]
> I guess the challenge is, a wallet developer, how do you show to the user where those sats come from. The sum of the payments and invoices would not be equal to the balance.

The easiest solution here would be to just disallow push amounts with `--rejectpush`. We could add a feature where these push amounts present as key sends but I'm not sure if that's wise because they aren't actually payments. 

@nicolasburtey would having a record of the fact that the push occurred be enough?

**Comment by nicolasburtey** [comment]
> key sends but I'm not sure if that's wise because they aren't actually payments.

I'm not sure to understand this point


If I step back, I feel this would make sense to have some rules around sum(initialchannelockup) + sum(list"settled"invoice) - sum(listpayments) = current balance. 

This is a first principle in accounting. I see that at list push amount breaks this assumption.

**Comment by carlaKC** [comment]
> I'm not sure to understand this point

A keysend and a push amount are different concepts. Keysends are invoiceless sends. Push amounts are just people gifting you sats. They should not be recorded as paid invoices because they're not a payment you're receiving, there is no htlc. 

> If I step back, I feel this would make sense to have a rules around sum(initialchannelockup) + sum(list"settled"invoice) - sum(listpayments) = current balance.

Indeed, I'm currently working on accounting improvements in lnd. You would need to factor a push amount into this calculation. It unfortunately isn't as simple as this equation, because you'd need to factor in current reserved balance or fees on the channel. 

> I see that at list push amount breaks this assumption.

Correct, that's why I would recommend disabling push amounts so that these unexpected amounts cannot be sent to your node.

**Comment by nicolasburtey** [comment]
> A keysend and a push amount are different concepts. Keysends are invoiceless sends. Push amounts are just people gifting you sats. They should not be recorded as paid invoices because they're not a payment you're receiving, there is no htlc.

How is push_amt paid then?

I thought that @Roasbeef said on slack that push_amt was not part of the funding transaction, but the amount was pushed after the channel was opened.

More importantly, why have those 2 concepts now that we have keysends? Seems to be the same use case for me.

**Comment by carlaKC** [comment]
When a channel is created, the two parties involved sign a 2-2 multi-sig transaction which is called the funding transaction. Before they exchange these signatures, they each sign a commitment transaction which pays out the respective parties their balances. This prevents parties from disappearing and leaving you’re money trapped in the multi sig.

Currently one party funds a channel. If they specify push amount, the first commitment transaction assigns some capital to the remote peer. So the channel does not exist, and when it it is created with a push amount the remote party gets some sats. This is not a payment. It is an amount that you give to the other party.

Keysend, by contrast, is a payment that does not require an invoice. It requires that a channel already exists, and can be sent to a peer that we do not have a channel open with. It has an invoice because a HTLC is sent to our node and we record the payment. 

We are not going to record push amounts as payments. I am completely sympathetic to the accounting use case, but a push amount is simply not a payment by definition. If you would like to be able to account for push amount, I think the best course of action is to open an issue to record push amounts for channels on open. I will personally pick it up. 

I’m going to close this issue for now, but please do open another issue for recording push amounts if it is relevant for you. I’m also around on the LND slack if you want to chat further. Having a look at the BOLT#2 spec would also be helpful to help your understanding.
