### ISSUE TITLE
[Question] How the multiple channel scenario is handled?

### ISSUE THREAD

**Issue by nachikettapas** [lightningnetwork/lnd#4044]
Consider the following scenario of channels between nodes:
A -> B (0.015 sat)
A -> C (0.015 sat)
B -> D (0.015 sat)
C -> D (0.015 sat)

I created an invoice of 0.005 sat at D and tried to pay from A. I got the message: unable to find route to destination: UnknownNextPeer.

Is this an expected behavior?

### My environment

* version of `lnd`
v0.8.2-beta

* which operating system (`uname -a` on *Nix)
Ubuntu 16.04

* version of `btcd`, `bitcoind`, or other backend
v0.19.0.1

**Comment by guggero** [comment]
This should work fine. The error sounds like something with the setup is not correct.
Can you make sure that all nodes are fully synced, are connected to each other (at least the nodes that have channels between each other) and maybe that you can pay between direct nodes?
You can also try resetting the routing algorithm cache with `lncli resetmc` on node A. But that requires lnd to be compiled with the `routerrpc` tag.

**Comment by nachikettapas** [comment]
Yes I can pay invoice generated between direct nodes. But between nodes with multiple paths, the payment fails.
I am using the simulation tool polar to simulate the scenario. Are you suggesting the problem may lie with the simulation tool?

Also, how does the autopilot work? Does it operate when a new node joins the network or even while routing payments across multiple channel paths?

**Comment by guggero** [comment]
There were quite a few router bugs fixed in lnd version 0.9.0. Maybe it would be worth trying out the scenario on updated nodes. I don't know how Polar works in detail, if you can configure the version of lnd to use or have to wait for them to update the dependency.

The autopilot has nothing to do with routing payments. It only opens new channels if it is enabled.
The path finding algorithm is called "Mission Control" in lnd and that has been improved a lot in the recent versions.

**Comment by nachikettapas** [comment]
@guggero Thanks a lot. I will give it a try.
