### ISSUE TITLE
Docker cluster RPC error

### ISSUE THREAD

**Issue by captain-red-baron** [lightningnetwork/lnd#4149]
### Background

I am trying to set up a cluster of docker containers with simnet as decribed here: https://github.com/lightningnetwork/lnd/tree/master/docker

### Your environment

* version of `lnd`: master commit ffa7bed7f0ffcf8cb3ef4a612b6d5761e40b3f42
* which operating system (`uname -a` on *Nix): Ubuntu
* version of `btcd`, `bitcoind`, or other backend: as defined in docker-compose
* any other relevant environment details

### Steps to reproduce

Clone repository: Follow https://github.com/lightningnetwork/lnd/tree/master/docker

# Init bitcoin network env variable:
$ export NETWORK="simnet" 

# Create persistent volumes for alice and bob.
$ docker volume create simnet_lnd_alice
$ docker volume create simnet_lnd_bob

Run the "Alice" container and log into it:
$ docker-compose run -d --name alice --volume simnet_lnd_alice:/root/.lnd lnd
$ docker exec -i -t alice bash

Generate a new backward compatible nested p2sh address for Alice:
alice$ lncli --network=simnet newaddress np2wkh 

Recreate "btcd" node and set Alice's address as mining address:
$ MINING_ADDRESS=<alice_address> docker-compose up -d btcd

Generate 400 blocks (we need at least "100 >=" blocks because of coinbase 
block maturity and "300 ~=" in order to activate segwit):
$ docker exec -it btcd /start-btcctl.sh generate 400

Check that segwit is active:
$ docker exec -it btcd /start-btcctl.sh getblockchaininfo | grep -A 1 segwit
alice$ lncli --network=simnet walletbalance

Run "Bob" node and log into it:
$ docker-compose run -d --name bob --volume simnet_lnd_bob:/root/.lnd lnd
$ docker exec -i -t bob bash

bob$ lncli --network=simnet getinfo

### Expected behaviour

Return 

{
    ----->"identity_pubkey": "0343bc80b914aebf8e50eb0b8e445fc79b9e6e8e5e018fa8c5f85c7d429c117b38",
    "alias": "",
    "num_pending_channels": 0,
    "num_active_channels": 0,
    "num_inactive_channels": 0,
    "num_peers": 0,
    "block_height": 1215,
    "block_hash": "7d0bc86ea4151ed3b5be908ea883d2ac3073263537bcf8ca2dca4bec22e79d50",
    "synced_to_chain": true,
    "testnet": false
    "chains": [
        "bitcoin"
    ]
}

### Actual behaviour

[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Comment by Roasbeef** [comment]
Check that the node you're trying to issue a command to is actually up.

**Comment by doer01** [comment]
Same problems facing

**To add**

**Logs of bob node**
$ sudo docker logs -f bob
2020-04-04 03:47:26.060 [WRN] LTND: open /root/.lnd/lnd.conf: no such file or directory
2020-04-04 03:47:26.060 [INF] LTND: Version: 0.9.0-beta commit=v0.9.0-beta-463-g184939c81a2ffe2f3ec622582892537313537666-dirty, build=production, logging=default
2020-04-04 03:47:26.060 [INF] LTND: Active chain: Bitcoin (network=simnet)
2020-04-04 03:47:26.060 [INF] LTND: Opening the main database, this might take a few minutes...


stuck here since node started, last 5-6 hrs

**Comment by carlaKC** [comment]
> Opening the main database, this might take a few minutes

BBolt DB obtains a [file lock](https://github.com/etcd-io/bbolt#opening-a-database) on the `channeldb` file. you're likely stuck in this stage because you already have another lnd instance running using the same data path; this node is trying to obtain a lock on a file that's already in use. 

Bolt does have a timeout option, so we could set this to some very forgiving value (5mins?) so that nodes at least fail rather than hang if they can't open the db, @Roasbeef ?

**Comment by Roasbeef** [comment]
Correct @carlaKC, this will need to be done in the `walletdb` repo rather than here.

**Comment by jakesyl** [comment]
op didn't specify a wallet lock in their case and I'm not seeing this issue being caused by a walletdb lock either. I think it might be an issue with the tutorial. If I run:

```
# Init bitcoin network env variable:
export NETWORK="simnet"
docker volume create simnet_lnd_alice
docker volume create simnet_lnd_bob

# Create persistent volumes for alice and bob.
docker volume create simnet_lnd_alice
docker volume create simnet_lnd_bob
docker-compose run --name alice --volume simnet_lnd_alice:/root/.lnd lnd
```

all good so far. If I login (`docker exec -i -t alice bash`), and run `lncli --network=simnet newaddress np2wkh` I get:

`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"`

If this were a walletdb issue,  I assume you'd get the same thing, but if I run this with a hostname specified:

`lncli --network=simnet --rpcserver=$(hostname -i):10009 newaddress np2wkh`

I get: `[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for 127.0.0.1, ::1, 172.19.0.3, not 172.21.0.3"`

Am I missing something in the tutorial? Seems like this might've been ops issue as well

**Comment by jakesyl** [comment]
Okay, this is bizarre. So I rebuilt from scratch (full logs w/ docker system prune, etc [here](https://gist.github.com/jakesyl/b889e4072c8f6288667ecdc66ec4f3f2). As I suspected, `lncli --network=simnet newaddress np2wkh` returned the same error as above. But `lncli --network=simnet --rpcserver=$(hostname -i):10009 newaddress np2wkh) works great
