### ISSUE TITLE
Ability to set inbound and outbound fees

### ISSUE THREAD

**Issue by Swissnode** [lightningnetwork/lnd#4225]
As a major channel balancer and node operator, it has become clear to me and the community of channel balancers I work with that we really need the ability to incentivize traffic in certain directions.

As such, we would highly recommend having inbound and outbound fees to allow such incentivization.

**Comment by Roasbeef** [comment]
As is, on the protocol level, you can only set the fees for _outbound_ (routing an HTLC over that channel). The remote party controls the "inbound fees", since their bandwidth is used to carry the HTLC. 

One thing we've discussed is possibly introducing "pair wise" fee schedules. So this would mean you can set different fees for A -> B, and A -> C, where B and C are your channels. We could possibly add some new TLV fields to the `ChannelUpdate` to make this possible, but no one has attempted to fully specify it yet.

**Comment by Swissnode** [comment]
Pairwise fees would be a GREAT option @Roasbeef ! Thanks for taking the time to look at this. I realise the discussion probably belonged on another repo, apologies if I hit the wrong one!!

Great work, loving Lightning and LND!

**Comment by Jestopher-BTC** [comment]
Either pairwise fees or inbound fees are gravely need for node management! Inbound liquidity is a scarce resource and it does not have the same value even in different channels; some inbound is worth more in certain channels than others.

**Comment by grnqrtr** [comment]
Just adding that I agree. Having some kind of "pair wise" fees or inbound fees would be really helpful.

**Comment by Roasbeef** [comment]
This is a spec level thing, so closing here as the discussion needs to be started on the rfc repo and/or the dev mailing list.

**Comment by AbelLykens** [comment]
Opened in RFC repo: 
https://github.com/lightningnetwork/lightning-rfc/issues/835
Link added for reference. Mentioned you @Swissnode as original.

**Comment by joostjager** [comment]
But is this a spec level thing? It seems to me that this can also be a implementation-specific extension when inbound fees are always negative or zero. Ref: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-July/003643.html

**Comment by Roasbeef** [comment]
Re-opening since #6703 is now a thing

**Comment by dstadulis** [comment]
relevant blip
https://github.com/lightning/blips/pull/18
