### ISSUE TITLE
Whats the meaning of IncorrectOrUnknownPaymentDetails and how is it different from UnknownPaymentHash?

### ISSUE THREAD

**Issue by Overtorment** [lightningnetwork/lnd#4247]
Get this error occasionally sending to route:

```
{ payment_error:
   'IncorrectOrUnknownPaymentDetails(amt=867594000 mSAT, height=629188)@1',
  payment_preimage: <Buffer >,
  payment_route: null,
  payment_hash:
   <Buffer 08 d9 5b 32 c1 ac 07 54 91 17 cb cb ba 6d 02 ad e0 28 3c 7c fa e1 98 6f a9 f5 5e a2 8a 24 0c c2> }

```

Feels like this is the same as `UnknownPaymentHash` but not quite sure

**Comment by carlaKC** [comment]
Failure due to incorrect details covers a few cases (from [BOLT#4](https://github.com/lightningnetwork/lightning-rfc/blob/452a0eb916fedf4c954137b4fd0b61b5002b34ad/04-onion-routing.md#failure-messages)):
- The node you are sending the payment to does not have an invoice with that hash
- The amount being paid is wrong, or the htlc has the wrong expiry, or expires too soon so is rejected
- Payment secret for MPP is wrong

These errors are all combined into a single error to prevent probing attacks. 

What version of lnd are you running on?

**Comment by Overtorment** [comment]
0.10
Is it safe to assume that funds sent in this attempt are not spent?

**Comment by carlaKC** [comment]
Yes, it's a permanent failure so the payment status will say failed.

**Comment by Overtorment** [comment]
thanks!
