### ISSUE TITLE
Association of HTLC events to local invoice or payment

### ISSUE THREAD

**Issue by MrHash** [lightningnetwork/lnd#4272]
Is it possible for HTLC events to contain a reference id which can be used to associate the event to a local payment or invoice?

**Comment by carlaKC** [comment]
Htlc events have a type field which will tell you whether an event is related to an invoice/payment/forward. Since we now allow multiple hltcs per invoice/ payment, it is possible that multiple events are associated with the same invoice or payment. 

Invoices currently have their htlcs displayed by list invoices, so you can match the `IncomingChannelID` and `IncomingHtlcIndex` in a HtlcEvent to the `HtlcIndex` and `ChanID` in your invoice.

Unfortunately you do need to map channel ID (in listinvoices) to the short channel id which is provided by the event stream. This issue could serve as a feature request to have both channel ID fields in the event, if that is going to be a big blocker to your use of the stream?

Payments side, we currently have the channel ID saved in the payments database, but the htlc index (required to uniquely identify each htlc) still needs to be added.

**Comment by MrHash** [comment]
Thanks for the info. The goal is to be async notified at the sender on settlement or failure of a remotely held invoice, but it seems like htlcs are not indexed in the `listpayments` output. I guess that's not possible then?

**Comment by carlaKC** [comment]
You can use `TrackPayment` and `SubscribeInvoice` to be notified when your own payments/invoices succeed or fail?

**Comment by MrHash** [comment]
I'm using `SubscribeInvoices` currently and `SubscribeSingleInvoice` but i don't see an equivalent such as `SubscribePayments` so that i know when to track a specific payment. Is there a way to do that?

**Comment by carlaKC** [comment]
You can use `TrackPayment` to keep track of a specific payment.

**Comment by MrHash** [comment]
Yes thanks. I see that you are working on payment indexing and hopefully this will lead to support of a consistent interface spec for querying invoices and payments as suggested here https://github.com/lightningnetwork/lnd/issues/4164#issuecomment-610826793

**Comment by carlaKC** [comment]
> support of a consistent interface spec for querying invoices and payments

As is, there is no planned unified interface for payments and invoices, but it's certainly something we're thinking about. Going to close this issue, since the question is resolved, but feel free to open a feature request interface if you have a strong need for something of that sort! Feedback on what the ideal interface looks like is really helpful.
