### ISSUE TITLE
Graph syncing on windows takes around 1-1:15 hour, while on same machine on linux around 8-10 minutes

### ISSUE THREAD

**Issue by RostyslavAntonyshyn** [lightningnetwork/lnd#4314]
### Background

Graph syncing on windows takes around 1-1:15 hour, while on same machine on linux around 8-10 minutes.

### Your environment

* version of `lnd` - 0.10.0-rc5
* Windows 10
* neutrino if using lightning wallet, bitcoind when manually 
* Using routing.assumechanvalid

### Steps to reproduce

Can be reproduced on both latest lightning wallet and lnd 0.10.0-rc5.
As I noticed most of time takes db update

```
func (c *ChannelGraph) AddLightningNode(node *LightningNode) error {
	return kvdb.Update(c.db, func(tx kvdb.RwTx) error {
		return addLightningNode(tx, node)
	})
}
```

### Expected behaviour

Expected a bit faster sync. 

### Actual behaviour

Graph syncs for hour or more (connecting to same peers on both Linux and Win, trying to sync ~36500 channels).

**Comment by wpaulino** [comment]
> Graph syncing on windows takes around 1-1:15 hour, while on same machine on linux around 8-10 minutes.

Does the longer sync happen with both neutrino and bitcoind?

What does your `lnd.conf` look like? Are you using `localhost` anywhere? We've noticed that [resolving `localhost` on Windows takes a long time](https://github.com/lightningnetwork/lnd/issues/1027), which affects each RPC made to `bitcoind`. If you use `bitcoind.rpchost=127.0.0.1`, do you see any improvements?

**Comment by roeierez** [comment]
I think the bottleneck goest to the boltdb insertions.
synchronizing the network for ~30000 channels consists of roughly ~100000 insertions.
During some experiments on how to optimize graph sync we ran a program that populates the graph from a c-lightning file that contains all the raw lightning messages (as if they came from the network). In a linux machine it took ~10 minutes. In a mac machine it took ~40 minutes.
When running the program with eliminating `fsync` using boltdb `NoSync` flag all graph was processed in less than 1 minute.
With some small changes to LND we managed to expose batch API and when running the software with the batched version (inserting everything in one transaction) it was processed in less than 1 minute.
This shows the `fsync` is the issue here and in Windows it is probably more reflected.
Also worth thinking on how to batch these updates during historical sync as the performance gain is huge.

**Comment by RostyslavAntonyshyn** [comment]
> > Graph syncing on windows takes around 1-1:15 hour, while on same machine on linux around 8-10 minutes.
> 
> Does the longer sync happen with both neutrino and bitcoind?
> 
> What does your `lnd.conf` look like? Are you using `localhost` anywhere? We've noticed that [resolving `localhost` on Windows takes a long time](https://github.com/lightningnetwork/lnd/issues/1027), which affects each RPC made to `bitcoind`. If you use `bitcoind.rpchost=127.0.0.1`, do you see any improvements?

Tried to sync with "127.0.0.1" instead of "localhost", it helped a bit, now I synced full graph of 36307 channels ( 73 query requests ) in ~35-40 minutes instead of 1h+.

Tried using bitcoind and running last version of lightning-app which runs on neutrino node, both were syncing for a while.

lnd.conf is pretty similar to one that lightning-app uses.

**Comment by Roasbeef** [comment]
> Also worth thinking on how to batch these updates during historical sync as the performance gain is huge.

See #3367

**Comment by Roasbeef** [comment]
One other issue with `bitcoind` as a backend, is that since it doesn't have a persistent connection like btcd (which uses websockets), it needs to continually make new connections, which at times we've seen even exhaust the set of available file descriptors on certain systems.

**Comment by Roasbeef** [comment]
Initial graph download is now batched, will re-open if things are still really slow on windows.
