### ISSUE TITLE
Moving rest-gateway http annotations to seperate files

### ISSUE THREAD

**Issue by sputn1ck** [lightningnetwork/lnd#4329]
Would it make sense to move the http annotations that are used in the proto definitions to seperate service configuration files as explained here:

https://grpc-ecosystem.github.io/grpc-gateway/docs/grpcapiconfiguration.html

https://cloud.google.com/endpoints/docs/grpc/grpc-service-config

I personally need to remove all http annotations when compiling to c#, as when compiling with the http annotations it adds a dependency to the google.api library, which I can't/don't want to include in my Unity projects.

**Comment by guggero** [comment]
This is actually a pretty good idea! I didn't know it was possible to define the annotations in a separate file.
I tested this quickly and it looks like it works great and produces the exact same output (also for the `.swagger.json` files).

@Roasbeef should I go ahead with this and switch #4251 over to this as long as it's not merged yet?

The only downside I see to this is that we might forget to add the REST definitions more easily when adding new RPCs because they are in a separate file.

**Comment by sputn1ck** [comment]
> The only downside I see to this is that we might forget to add the REST definitions more easily when adding new RPCs because they are in a separate file.

Maybe this could be done as a test with [grpc reflection](https://github.com/grpc/grpc-go/tree/master/reflection) and yml parsing? I didn't find anything regarding grpc-gateway reflection support

**Comment by sputn1ck** [comment]
You could use https://godoc.org/github.com/jhump/protoreflect/desc/protoparse to do that 

example https://gist.github.com/sputn1ck/e57420046622a2b15dd249ba4b0e7155

**Comment by guggero** [comment]
I ended up implementing a very simple check using `grep` and `awk` to make sure every RPC is defined in the `lnrpc/rest-annotations.yaml`, see #4251.
