### ISSUE TITLE
lncli openchannel in psbt mode does not accept network serialized tx at final step

### ISSUE THREAD

**Issue by SomberNight** [lightningnetwork/lnd#4330]
When trying open a channel using the CLI in psbt mode, at the last step, after the tx has been signed, lnd [only accepts a finalized PSBT](https://github.com/lightningnetwork/lnd/blob/948fe8cfdbf5b873e55f68e3b4463ff0c1ffff73/cmd/lncli/cmd_open_channel.go#L510).
The [PSBT at this point](https://github.com/lightningnetwork/lnd/blame/32b04b7ac32ba7eabbcda7722cef03b5977acf62/docs/psbt.md#L221) is a complete and signed transaction, as returned by an [Input Finalizer](https://github.com/bitcoin/bips/blob/4fb2c5290e10270c8e4a6df357fe98bfab2ddfe9/bip-0174.mediawiki#Input_Finalizer).

What is the reasoning for not accepting a network serialized raw hex tx at that point, as returned by a [Transaction Extractor](https://github.com/bitcoin/bips/blob/4fb2c5290e10270c8e4a6df357fe98bfab2ddfe9/bip-0174.mediawiki#transaction-extractor)?

I cannot see any technical reason why the finalized PSBT would be needed: the only extra information inside it (compared to the network tx) is potentially the input UTXOs, but even the presence of those is not guaranteed (and if they were there, they have already been seen by lnd in the earlier steps).

Context: Electrum currently does not expose the finalised PSBT to the user; only the network serialized tx. The "Transation Extractor" phase of the PSBT flow happens automatically. This makes the UX significantly simpler.

**Comment by Roasbeef** [comment]
It's certainly possible to modify the interface to accept the final fully signed transaction. One thing we wanted to prevent (depending on how the client can interpret a partial PSBT where only the outputs are populated) is having a user create an invalid funding transaction, which possibly locks up their coins without interaction from the counter-party. Ideally the user always executes the verify call to ensure that they aren't at risk of this, with `lnd` broadcasting the final funding transaction in the end itself (which also lets it rebroadcast since the transaction will be stored in the wallet).

**Comment by guggero** [comment]
When fixing this, we should also make sure that the funding flow is not aborted for simple encoding or copy/paste errors as described in point 1 of https://github.com/lightningnetwork/lnd/issues/4400.
Ideally we ask for the same input in a loop until either a non-nil error is received or the user aborts by pressing Ctrl+C.
