### ISSUE TITLE
why the Lightning Network channel can't Increase balance？

### ISSUE THREAD

**Issue by SmartMeshFoundation** [lightningnetwork/lnd#437]
if A and B have a Lightning Network channel，A has put some balance to this channel,when A translate some time with B, the balance of A is will be spend all, at this time the channel will be closed ,so why Lightning Network channel did not support increase balance to this existing channel，then A and B can continue use this channel for translate？

**Comment by Roasbeef** [comment]
It can. We call that "splicing in". It allows A to add additional fund to the channel _without_ needing to halt all channel updates. They can continue updating the channel on the fly while the splice in/out transaction is confirming. 

`lnd` hasn't implemented this feature yet though.

**Comment by johnsonhzhang** [comment]
There is a way to increase the capacity of the payment channel. [Dynamic Channel Deposit and Withdraw for Lightning Networks][1]
[![The FundCasc Splice-in][2]][2]

If A want to add 0.5 BTC to the channel, he can propose to create a new funding transaction which spent the old funding and another UTXO from A. The new Funding transaction can be created by following steps.

1. Creating a new Funding Transaction
2. Creating a pair of new Commitment Transactions (C2a and C2b), containing the corresponding RD2a and RD2b
3. Signing the new Commitment Transactions
4. Exchanging signatures for new Commitment Transactions
5. Signing a new Funding Transaction
6. Exchanging signatures for the new Funding Transaction
7. Broadcasting the new Funding Transaction

  [1]: https://github.com/litexnetwork/papers/blob/master/FundCasc.pdf
  [2]: https://i.stack.imgur.com/IVyyc.png

**Comment by Roasbeef** [comment]
Yes, we know how to do this. We call it "splicing". Do you follow the
lightning-dev mailing list?

**Comment by johnsonhzhang** [comment]
@Roasbeef Thanks for your timely reply. I have indeed overlooked the mailing list. I prefer the synchronous splice-in proposed in the mailing list, which costs less fee. My proposal is similar to the synchronous splice-in. Additionally, we are implementing this in great details and it’s close to be finished.

**Comment by Roasbeef** [comment]
The asynchronous method is superior as it doesn't block the channel until
the new Commitment is confirmed. In any case, this isn't related to lnd at
all.

On May 10, 2018 7:06 AM, "johnson.zhang" <notifications@github.com> wrote:

@Roasbeef <https://github.com/Roasbeef> Thanks for your timely reply. I
have indeed overlooked the mailing list. I prefer the synchronous splice-in
proposed in the mailing list, which costs less fee. My proposal is similar
to the synchronous splice-in. Additionally, we are implementing this in
great details and it’s close to be finished.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/437#issuecomment-388063657>,
or mute the thread

**Comment by Roasbeef** [comment]
> Additionally, we are implementing this in great details and it’s close to be finished.

For `lnd`?

**Comment by johnsonhzhang** [comment]
@Roasbeef yes，we are implementing this based on lnd.

**Comment by nilskp** [comment]
@johnsonhzhang for `lnd` as a PR, or your own fork?
