### ISSUE TITLE
--base_psbt parameter not added to bitcoin-cli example

### ISSUE THREAD

**Issue by gcomte** [lightningnetwork/lnd#4406]
### Background

If one wants to open multiple channels in a single tx, one can use the --psbt flag to do so. 

The first channel funding process can be created using --psbt and it returns a base64 encoded PSBT: `cHNidP8BADUCAAAAAAFAQg8AAAAAACIAIKR0rScOcvDcFqoXU1/0ExxYiiGVQ+/bNVfyXKDsWqqPAAAAAAAA`

For the second channel, one can then pass this PSBT, when starting the process: `lncli openchannel --psbt --base_psbt cHNidP8BADUCAAAAAAFAQg8AAAAAACIAIKR0rScOcvDcFqoXU1/0ExxYiiGVQ+/bNVfyXKDsWqqPAAAAAAAA ...`

Then you receive a longer PSBT than the first time: 
`cHNidP8BAGACAAAAAAJAQg8AAAAAACIAIKR0rScOcvDcFqoXU1/0ExxYiiGVQ+/bNVfyXKDsWqqPQEIPAAAAAAAiACAjmdEPMKH84riEPxz4gPIubaRguBuNWTLgxvLqmFBgMAAAAAAAAAA=`

It appears that this PSBT contains the addresses for both new channels. So far, so good. But there is also an example for `bitcoind` which does *not* contain both addresses:
`bitcoin-cli walletcreatefundedpsbt [] '[{"tb1qywvazres587w9wyy8uw03q8j9ek6gc9crwx4jvhqcmew4xzsvqcq3jjdja":0.01000000}]`

As far as I understand, this example should rather look like this, containing the information given with the `--base_psbt` argument:

`bitcoin-cli walletcreatefundedpsbt [] '[{"tb1q53626fcwwtcdc942zaf4laqnr3vg5gv4g0hakd2h7fw2pmz6428sk3ezcx":0.01000000},{"tb1qywvazres587w9wyy8uw03q8j9ek6gc9crwx4jvhqcmew4xzsvqcq3jjdja":0.01000000}]'`

### Your environment

* LND 0.10.0

**Comment by guggero** [comment]
I'm not sure what example you are referring to. The [example in psbt.md](https://github.com/lightningnetwork/lnd/blob/master/docs/psbt.md) does not mention the `--base_psbt` at all.

But feel free to add the example to the doc.

**Comment by gcomte** [comment]
Oh sorry. I am referring to the bitcoind example that the interactive PSBT mode proposes after entering the `lncli openchannel` command:

![Selection_099](https://user-images.githubusercontent.com/8024734/85458057-fc450d00-b5a0-11ea-8de9-e77f3f60cff0.png)

**Comment by guggero** [comment]
Ah, right. We could show that, that's actually not a bad idea.
The thing is though, if there happens to be more information in the base PSBT than just the previous outputs, that information would be lost if you continued with the `bitcoin-cli` approach. But a user would probably know that or not care if they just want to open multiple channels.

By the way, be careful with batch opening of channels through PSBT. If you feed in the finalized TX into the first `openchannel` window/instance, it will already publish the transaction. If any of the other `openchannel` calls fail for whatever reason (because the remote node times out for example), you could lose the money sent into that funding multisig output.

I plan to add a `--no-publish` flag to the PSBT flow that should be set for each call but the very last. That would make it safer. Also there is a "real" batch channel open feature in the works that makes the whole flow easier again.

**Comment by gcomte** [comment]
Oh cool, looking forward to that catch channel feature!

Appreciate your thougts on that `bitcoin-cli` command issue. I'll just leave it like that, you know best how to proceed with this ;-)
