### ISSUE TITLE
0.11.0-beta.rc2 should attach routing hints in any case

### ISSUE THREAD

**Issue by kilrau** [lightningnetwork/lnd#4514]
### Background

Up until now that made sense, but looks like lnd is not attaching routing hints for private channels if the invoice amount exceeds the largest channels inbound capacity. Now that MPP+Wumbo are available, I think it makes sense to remove these restrictions and attach routing hints in any case since payments can be split and come in via multiple private channels settling the invoice.

### Your environment

* version of `lnd`: 0.11.0-beta.rc2
* which operating system (`uname -a` on *Nix): ubuntu 20.04 amd64
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.20.99 (own build)
* any other relevant environment details

### Steps to reproduce

My example:
1. Set up lnd with 2 private channels with 0.5 BTC inbound capacity each
2. Create invoice of 1 BTC -> no routing hints attached in invoice
3. Create invoice of <0.5 BTC -> routing hints attached in invoice

### Expected behaviour

Routing hints for both private channels should be attached for the 1 btc invoice

### Actual behaviour

No routing hints attached (verified with `decodepayreq`)

**Comment by carlaKC** [comment]
This isn't actually related to wumbo; the same would apply if you created a private channel with 20k sats and added an invoice for 30k sats because we currently skip over any channels that don't have [sufficient inbound](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/addinvoice.go#L281) to cover the amount when adding hints. 

Since payments can be split into many parts (senders choice as to how many, and defaults differ across implementations), I'd say that we need to relax the inbound amount requirement. Perhaps just relaxing our selection to the channels with the most inbound.

**Comment by alexbosworth** [comment]
This could also be a spec issue because routing hints do not include bandwidth hints, which makes splitting more tricky

**Comment by alexbosworth** [comment]
A potential workaround if this is not addressed is to use the signing APIs and create and sign a new payment request that includes your desired routing hints

**Comment by Roasbeef** [comment]
Just put up a fix (#4521), would appreciate if you could give it a spin @kilrau. Also thanks for this bug report in the first place! This was totally an oversight, as we were mainly focused on the case where the receiver has all public channels.

**Comment by kilrau** [comment]
Works for the 2x0.5 btc channel scenario (but didn't test others)!
