### ISSUE TITLE
What do you set to --externalip=X.X.X.X when behind TOR and your IP changes every 10 minutes?

### ISSUE THREAD

**Issue by johnblanc** [lightningnetwork/lnd#4516]
### Background
I'm trying to run a node behind tor and giving value to --externalip=X.X.X.X is a bit tricky since my external IP changes every 10 minutes or so. What do we do in that case?

I can run it without that parameter and it starts, but not sure what will be the issues down the road because of it?

### Your environment

* version of `lnd` Latest version
* which operating system (`uname -a` on *Nix) Debian
* version of `btcd`, `bitcoind`, or other backend latest bitcoind
* any other relevant environment details

**Comment by guggero** [comment]
If you are only reachable through Tor (which it sounds like), you don't need to set any value to `--externalip`. The Tor controller of `lnd` will automatically announce your Onion address to the network.

Nodes that don't support Tor connections won't be able to connect to your node anyway if it doesn't listen on clearnet as well. So you only need to use `--externalip` if you do listen on clearnet.

**Comment by johnblanc** [comment]
yes only through Tor so far. From your experience do the majority of nodes support tor connections? 
I can ditch the tor if I won't be able to connect to most. It was just as security precaution.

**Comment by guggero** [comment]
According to [Clark Moody's dashboard](https://bitcoin.clarkmoody.com/dashboard/) around 44% of the public LN capacity comes from Tor enabled nodes. But I've heard that getting inbound liquidity is harder when running Tor only because non-Tor nodes cannot connect to you and open channels. You can always connect out to any node.

Closing this as I believe the original question is answered, right?
