### ISSUE TITLE
Unable to restore my Lightning wallet 

### ISSUE THREAD

**Issue by miguelmartinn9** [lightningnetwork/lnd#4539]
### Background

I was doing a Lightning Torch on reddit when my node suddenly wasn't able to connect anymore. See more about it [here].(https://www.reddit.com/r/Bitcoin/comments/i9lbnp/bored_shall_we_start_a_lightning_torch/g1g5ue6/)

So I deleted every instance of LND to reinstall it again and when I did, I run the command `lncli create` and went for the option that asked me if I had a 24 word recovery seed, which I do. 

And when everything is running as expected, I do `lncli walletbalance` and I get 0 sats, when I should have 10k.
Plus, when running `lncli channelbalance` I also get 0 sats, when I should have 111 sats.

The onchain balance is no problem since I was able to recover it with another wallet, but how do I recover my channels?
### Your environment

* Version of LND: lnd version 0.10.4-beta commit=v0.10.4-beta
* Operating System: Raspbian GNU/Linux 10 
* Version of bitcoind: v0.20.1
* Running a Raspberry Pi 3.

### Expected behaviour

I should be able to see my onchain balance as well as my channel balance when I enter my 24word seed.

### Actual behaviour

All my balances show 0 sats.

**Comment by guggero** [comment]
To recover your channels, you need the `channel.backup` file that is created by lnd. The seed isn't enough.
See this chapter: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#static-channel-backups-scbs

Also, because restoring from backup involves closing all channels to get the on-chain sats back, your 111 sats would probably go to miner fees because that is too small an amount to be represented on-chain and would be considered dust.

Just deleting everything really is the worst thing you can do in this case. If you made a backup before deleting, try restoring with the `channel.backup` file so at least the other peer is notified the channel won't become active again.

Closing this as there is nothing to fix in the code. Feel free to comment if you need help with the SCB restore. The document linked above should contain a link to the restore procedure.
