### ISSUE TITLE
Bug: balance reported by /channels disagrees with what LND checks in payinvoice

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#4585]
### Background

Paying an invoice can fail with "insufficient balance" even if the local balance (with channel reserve subtracted) reported by `/channel` is higher than amount in the invoice.

[Python code calculating the balance](https://github.com/Kixunil/lnpbp-testkit/blob/master/lnpbp_testkit/lnd.py#L145)

### Your environment

* version of `lnd`: `0.11.0`
* which operating system (`uname -a` on *Nix) `:Linux disp7952 4.19.132-1.pvops.qubes.x86_64 #1 SMP Tue Jul 14 03:42:21 UTC 2020 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: `Bitcoin Core version v0.20.0`
* any other relevant environment details: regtest

### Steps to reproduce

1. Setup two regtest LN nodes and a bitcoind node
2. Create (and confirm) a 40000 sat channel from A to B
3. Create a 20000 sat invoice at node B and pay it from node A
4. Get balance of the channel
5. Create a 10000 sat invoice and attempt to pay it from A

### Expected behaviour

Either balance is reported to be lower than the invoice amount or the payment succeeds.

### Actual behaviour

The reported balance is 10337, yet paying a 10000 sat invoice fails.

**Comment by Roasbeef** [comment]
Are you taking into account the reserve and also the fees we "deduct" when we need to pay for the HTLC on the commitment transaction in the intermediate state?

**Comment by Kixunil** [comment]
> Are you taking into account the reserve

Yes, that's what I meant by "with channel reserve subtracted"

> the fees we "deduct" 

Oh, this is not a part of reserve? Is there any way to get it from LND API? `commit_fee` doesn't sound like it, but maybe it is?

**Comment by Roasbeef** [comment]
The only way to compute that is to do it manually. Here's an example: 
  * We have 10k satoshis available balance 
  * We go to add an HTLC that is 9k satoshis 
  * As a result of this new HTLC, since we're the initiator, we need to pay 2k satoshis of fees
  * We now have a 1k satoshi shortage so we reject this HTLC addition

**Comment by Kixunil** [comment]
Is that 2k sats a constant or do I need to retrieve it from the node somehow?

**Comment by Roasbeef** [comment]
> Is that 2k sats a constant or do I need to retrieve it from the node somehow?

The size/weight of an HTLC is known, but what's variable is the actual fee rate used on the commitment. This value can be checked using `listchannels`. 

So given that, I don't think there's an actual issue here, and would file it under #2708 -- which has some hidden dragons on the way to implementation.

**Comment by Kixunil** [comment]
Ah, OK, thanks!
