### ISSUE TITLE
Cancellable subscriptions in GRPC api

### ISSUE THREAD

**Issue by ischepin** [lightningnetwork/lnd#4727]
### Background

I have a question regarding various subscriptions (server side streams) in lnd grpc api:
Suppose that I want to subscribe for status of single invoice using `invoicesrpc` service, that is `SubscribeSingleInvoice` . This method is a server stream, returning all updates of specified invoice. But if invoice has already settled, there is no reason for client to continue monitoring it, and there is no ‘proper’ way to end the subscription according to grpc protocol (https://github.com/elixir-grpc/grpc/issues/179). The ‘proper’ way to implement a cancellable subscription would be a bidirectional streaming rpc where first client request would initiate the subscription, and second request would stop it.
Maybe it’s worth changing the subscription rpcs in lnd to support this, or just add new rpcs?

**Comment by carlaKC** [comment]
Once lnd's subscriptions reach a terminal state (invoice settled or expired, payment failed or completed etc), the server will terminate the stream to the client because it has no more updates. 

Other grpc client implementations clients to cancel streams (golang passes in a `context` which can be [cancelled](https://github.com/grpc/grpc-go/issues/990#issuecomment-261131233) to kill the stream, python seems to have a [similar](https://stackoverflow.com/questions/55160210/python-grpc-cancel-unary-stream-call-from-client-side) `stream.cancel`), so unfortunately this seems like an elixir issue rather than something we can address.

**Comment by lukaszsamson** [comment]
@carlaKC I'm facing a similar problem to what @ischepin described. I tested it on v.0.12.1-beta and for payments it works as expected - when a terminal state is reached, the server ends the stream. On the other hand it does not work for invoices. When the invoice reaches settled state the stream remains open. until I cancel it on the client side. I tested it in javascript using a slightly modified code from official docs (https://api.lightning.community/?javascript#subscribesingleinvoice). The 'end' callback is never reached.
```
let call = invoices.subscribeSingleInvoice(request);
call.on('data', function(response) {
  // A response was received from the server.
  console.log("resp", response);
  if (response.state == 'SETTLED') {
    // If I don't call cancel here the stream stays open indefinitely
    call.cancel();
  }
});
call.on('status', function(status) {
  // The current status of the stream.
  console.log("stat", status);
});
call.on('end', function() {
  // This is never reached
  console.log("end");
});

call.on('error', function(...args) {
  // This is reached if I cancel the stream
  console.log("error", args);
});
```
Is it a bug?

**Comment by carlaKC** [comment]
My mistake here, looks like we don't close single subscriptions. Fix incoming!
