### ISSUE TITLE
Disconnect the wallet from the  channel.db

### ISSUE THREAD

**Issue by MrManPew** [lightningnetwork/lnd#4728]
### Background
Not sure why the lnd bitcoin wallet has to be in the channel.db. It might be more stable to disconnect between the two, so that in the channel.db is corrupted, one can still access the lnd wallet without having to use the recovery seed.
It will make the recovery process much easier. Especially as the node already has a working and synchronized bitcoind 

Some points I get form this crush:
https://github.com/lightningnetwork/lnd/issues/4720

**Comment by guggero** [comment]
This is already implemented. The on-chain wallet is a separate file (by default located in `.lnd/data/chain/bitcoin/mainnet/`.
My comment in #4720 was imprecise. If you only need to recover the channels because of a database corruption in the `channel.db` file, you can just move or delete that file and access the on-chain wallet individually (but all channels will be gone until recovered from SCB).

I recommended doing a full restore from the seed because the data corruption from a failed hard drive could also affect the `wallet.db` file.

**Comment by MrManPew** [comment]
thanks!
Maybe it will be good to update 
https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md
