### ISSUE TITLE
Money disappeared

### ISSUE THREAD

**Issue by rene78** [lightningnetwork/lnd#4740]
### Background

Left my node unattended during October and realized a balance decrease upon return. Thought it might be related to the LND vulnerability, thus updated my Raspiblitz LND to 0.11.1-beta. The next day some more satoshis diappeared. So I decided to close all my open channels. Not sure what's wrong there.

Balances right after the update to 0.11.1-beta
![image](https://user-images.githubusercontent.com/36115705/97800234-f7215a00-1c33-11eb-871a-723373dabb7b.png)

Balances roughly 20h later
![image](https://user-images.githubusercontent.com/36115705/97800248-06a0a300-1c34-11eb-9a3b-7471d2daf3fc.png)

### Your environment

* version of `lnd`: 0.11.1-beta
* which operating system: Linux Ubuntu
* version of `btcd`, `bitcoind`, or other backend: v0.20.0-mainnet
* Raspiblitz v1.6.0

### Steps to reproduce
nil

### Expected behaviour

Money does not just diapear 😊

### Actual behaviour

Balance gradually decreases over time

**Comment by vegardengen** [comment]
In a channel, there is set aside an amount reserved for if you need to force-close a channel. This reserve is negotiated between you and your peer, and is updated with the on-chain fee rate, so that you should always be able to force close. It is thus completely normal that your balance will fluctuate a little, even though you don't actively do anything.

Honestly, you are not the first to get this wrong. The information is there, but in my opinion these visualizers could show them - and in a way that it's easy to do the numbers and have them add up.

**Comment by rene78** [comment]
This is completely new information to me, @vegardengen. Learnt something new - thank you! Gonna close the issue.
