### ISSUE TITLE
LND force close of channel from peer

### ISSUE THREAD

**Issue by fiksn** [lightningnetwork/lnd#4742]
### Background

I have a few lightning channels open with collegues. Now we're all running lnd 0.11+. Every once in a while (once per month or so) it happens that a channel gets force closed. It looks as if my peer force closed it (in RTL) but according to them they didn't do anything.

So this is more of a question than issue report, is there any lnd code path that force closing of channels would happen automatically? Peer offline for too long, sending something strange or anything like that?

What kind of logging can I enable to investigate this issue should it occur next time? It's true that I have bitcoind synced on the machine but I am not sure whether I want gigabytes of debug logs (since like I said this occurs very rarely).

### Your environment
My raspberry pi node:

lnd 0.11.1-beta
bitcoind 0.20.1
Linux ln 4.19.118 #1-NixOS SMP Tue Jan 1 00:00:00 UTC 1980 aarch64 GNU/Linux

**Comment by Roasbeef** [comment]
It depends really. Channels can possibly force close if you need to go on-chain for an HTLC for various reasons. Closing this for now unless you have an actionable case that isn't a force closure due to an HTLC. There's also a larger issue that's tracking some of the recent reported cases of spurious force closes.

**Comment by MrManPew** [comment]
Hi @fiksn 

> There's also a larger issue that's tracking some of the recent reported cases of spurious force closes.

I think he means this:
#4613
