### ISSUE TITLE
Failed write attempt to backup file does not terminate lnd

### ISSUE THREAD

**Issue by lispmeister** [lightningnetwork/lnd#4749]
### Background

When `lnd` is configured to write a backup file of the `channel.db` file it attempts to write
to the specified backup path right after booting. If it fails the first write it logs an error but doesn't
immediately exit with error code (after cleanup).

### Your environment

* version of `lnd`
lnd version 0.11.1-beta commit=v0.11.1-beta

* which operating system (`uname -a` on *Nix)
Linux lnd-gateway-6b44bcb896-xh7dd 4.14.186-146.268.amzn2.x86_64 #1 SMP Tue Jul 14 18:16:52 UTC 2020 x86_64 Linux

* version of `btcd`, `bitcoind`, or other backend
bitcoind v0.20

* any other relevant environment details
This issue is mostly relevant in a Kubernetes environment where an exit signals container
failure to the scheduler and can be surfaced to the operator.

### Steps to reproduce
Include the following in your `lnd.conf` file:
```
      backupfilepath=/backup/channel.backup
```
Make sure this path isn't writable or doesn't exist. Boot `lnd` as usual an tail the log file.

### Expected behaviour

The `lnd` process should complain about the fact that it can't write to the path defined for
the backup file and exit immediately after cleaning up. 

### Actual behaviour

The `lnd` process exits eventually. This is what we find in the log:
```
unable to start server: unable to refresh backup file: unable to
update multi backup: unable to create temp file:
open /backup/lnd-gateway/temp-dont-use.backup: no such file or directory
stream closed
```

**Comment by Roasbeef** [comment]
Looking at the code, if we can't read then we should shutdown immediately. Your "actual behavior" section seems to point to this as well? It won't be the _very_ first thing that happens, but AFAICT, `lnd` _will not_ start up if it can't read the existing SCB file (assuming it exists), and/or also fails to write the new set of backups. 

We recently changed our behavior [after this issue was created](https://github.com/lightningnetwork/lnd/issues/4377) with this PR: https://github.com/lightningnetwork/lnd/pull/4379

**Comment by Roasbeef** [comment]
Should crash if we can't write after start up, using the log writer critical. Could also check this much earlier in the start up logic to "fail fast".

**Comment by Roasbeef** [comment]
Closing as we do indeed crash.
