### ISSUE TITLE
LND seed and compatibility other wallets

### ISSUE THREAD

**Issue by belgacoin** [lightningnetwork/lnd#4834]
### Background

I have my LND seed but my node isn't online anymore. Can I restore the (off-chain) funds by means of another compatible wallet?

**Comment by guggero** [comment]
Currently only `lnd` uses the `aezeed` seed format. But you can use the [`chantools showrootkey`](https://github.com/guggero/chantools#showrootkey) command to extract the `xprv` of the seed that is supported by some of the more advanced wallets out there. The on-chain funds are all on either a `m/49'/0'/0'/0/x` or `m/84'/0'/0'/0/x` derivation path.

The off-chain funds are a completely different matter. If you don't have a `channel.backup` file from when your node was last online, the default answer would be: No, off-chain funds cannot be restored without the backup.
If you are able and willing to dive into some quite technical and involved manual work, you can try [reconstructing the channel backup from public information](https://medium.com/@guggero/did-you-lose-funds-on-the-lightning-network-because-of-a-disk-crash-8971b6a92494). But that has a set of conditions to even work (mainly the peer is still around).

If you do have a `channel.backup` file, you can just [follow the official recovery guide](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md) to recover the off-chain funds (will close all channels).

I'm closing this issue because the main question is answered. You can still ask more questions here if things are still unclear.
