### ISSUE TITLE
Unable to start LND after restoring channel backup

### ISSUE THREAD

**Issue by mmarsalko** [lightningnetwork/lnd#4863]
### Background

I had restored a channel backup from another node.. one of the channels was waiting to close for over 12 hours and I shut it down to perform a backup and an update (I didn't realize it was still closing. whoops!). Now when starting LND, it get the error: 
> unable to start server: a height hint greater than 0 must be provided

I'd been working with @guggero on Telegram to get this issue resolved, and he suggested creating a ticket here so it could be tracked.

### Your environment

* v0.11.1-beta (commit=v0.11.1-beta)
* Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
* Bitcoin Core version v0.20.0
* Running on raspiblitz v1.6.1

### Steps to reproduce

1. Create a node and open a bunch of channels (NODE_A)
2. Screw up and create another node with the same seed using the lightning desktop app (NODE_B)
3. Have autopilot create a channel for you unknowingly (oof!)
4. use `lncli restorechanbackup` to restore NODE_B's channel backup on NODE_A
5. 12 hours later, screw up again by shutting down your NODE_A while a channel was still waiting to close.
6. Start up NODE_A

### Expected behaviour

Well.. I should be able to use my node again after it starts! :)

### Actual behaviour
unable to start server: a height hint greater than 0 must be provided

Here is debug output from the `debug` command in raspiblitz: https://cloud.shaffle.me/s/tMmTp6gjsii53kw
Here's the full lnd log: https://cloud.shaffle.me/s/kQ8TACiCWG4mQoL
Here's what occurs after unlocking the wallet: https://cloud.shaffle.me/s/HTwkgFDDyc9tjM5

**Comment by guggero** [comment]
Still trying to figure out how this could happen in the first place, given that we fixed the height hint problem for pending channels in SCBs.

Can you try if running with `--height-hint-cache-query-disable` allows `lnd` to start?

If not, can you please download [`chantools`](https://github.com/guggero/chantools/releases/tag/v0.6.0) and run the following commands:
 - `chantools dumpchannels --channeldb <path-to-raspiblitz's-lnd>/data/graph/mainnet/channel.db` (`lnd` must be stopped for this to work!)
 - `chantools dumpbackup --multi_file <the-channel.backup-you-restored-from-node-B>` (this will ask you for the node's seed, which is required because the backup is encrypted with the seed).

You can send the output to me directly as that contains some sensitive elements.

**Comment by mmarsalko** [comment]
Looks like `--height-hint-cache-query-disable` didn't do it. I've sent you the chantools logs over Telegram.

**Comment by guggero** [comment]
We did fix this in https://github.com/lightningnetwork/lnd/pull/3719 but the fix itself contained a bug... Will be fixed in #4865.

**Comment by mmarsalko** [comment]
For future readers, this issue was resolved on my end with a new version of chantools (v0.7.0), running the following command:

`chantools removechannel --channeldb <path-to-channel.db> --channel <bad channel>`
