### ISSUE TITLE
Estimate mpp routing fee - documentation

### ISSUE THREAD

**Issue by michaelWuensch** [lightningnetwork/lnd#4922]
### Background

I want to implement multi path payments and display an estimated fee before sending.
Neither QueryRoutes nor EstimateRouteFee have a max_parts attribute like SendPaymentV2.

The documentation for the fee estimation endpoints do not mention multi path payments at all.
Is this not possible yet or do I miss something? What is the correct way to achieve this?

I think the api documentation could be improved in regards to this issue.

Thank you!

### Your environment

lnd 0.11.1-beta

**Comment by Roasbeef** [comment]
In practice it's difficult since only at run time can we _really_ know which paths are taken given we only split when we encounter a failure atm. What we recommend instead is to use the `fee_limit` parameter to set a limit ahead of time, which'll ensure that `lnd` never selects a route that exceeds that amount.

**Comment by saubyk** [comment]
Closing this issue as `EstimateRouteFee` has now been updated to provide a close to accurate fee estimate, but no parts param in the API still which per the above comment is difficult to accomplish.
