### ISSUE TITLE
Calls to LookupInvoice with invalid r_hash raises an internal rpc exception

### ISSUE THREAD

**Issue by SamCymbaluk** [lightningnetwork/lnd#4936]
### Background

When calling the LookupInvoice rpc with an invalid payment hash it raises a grpc._channel._InactiveRpcError error.

### Your environment

* version of `lnd`: v0.12.0-beta.rc5-20-gb2857bf3
* which operating system: Host on Ubuntu 20.04, client on Windows 10
* version of `btcd`, `bitcoind`: `bitcoind` version 0.21.0

### Steps to reproduce

Minimal reproducible example:
```python
import rpc_pb2 as ln
import rpc_pb2_grpc as lnrpc
import grpc
import os
import codecs

os.environ['GRPC_SSL_CIPHER_SUITES'] = 'HIGH+ECDSA'

cert = open('tls.cert', 'rb').read()
cert_creds = grpc.ssl_channel_credentials(cert)
macaroon = codecs.encode(open('admin.macaroon', 'rb').read(), 'hex')
auth_creds = grpc.metadata_call_credentials(lambda ctx, cb: cb([('macaroon', macaroon)], None))
combined_creds = grpc.composite_channel_credentials(cert_creds, auth_creds)

channel = grpc.secure_channel('X.X.X.X:10009', combined_creds)
stub = lnrpc.LightningStub(channel)

req = ln.PaymentHash(r_hash=b'these_words_are_thirty_two_bytes')
stub.LookupInvoice(req)
```
Outputs:
```
Traceback (most recent call last):
  File "C:/Users/ukssp/Documents/Development/lookupinvoice_err.py", line 19, in <module>
    stub.LookupInvoice(req)
  File "C:\Users\ukssp\AppData\Local\Programs\Python\Python38\lib\site-packages\grpc\_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\ukssp\AppData\Local\Programs\Python\Python38\lib\site-packages\grpc\_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "unable to locate invoice"
	debug_error_string = "{"created":"@1611208556.364000000","description":"Error received from peer ipv4:X.X.X.X:10009","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"unable to locate invoice","grpc_status":2}"
>
```

### Expected behaviour

I would expect a proper error to be raised than can be caught by name without digging into private gRPC code.

### Actual behaviour

The rpc raises a grpc._channel._InactiveRpcError.

**Comment by Roasbeef** [comment]
I think this is because we don't yet send "nice" gRPC errors for all our error conditions. This is something we're working on improving across all our RPCs in general. Before we get around to that, callers may need to manually do string matching though we understand that's very brittle (error string can change which ends up breaking other code).

**Comment by guggero** [comment]
I'd say this is a quirk of gRPC and the specific Python implementation. It's true that we don't set gRPC error codes in 99.5% of our code base, so every RPC error is returned with code 2 (`StatusCode.UNKNOWN`). But I don't think that is going to change across the whole API. So the fact that Python raises this unknown but otherwise totally "normal" error message as an `grpc._channel._InactiveRpcError` is not something we can fix. And I would even guess this wouldn't change even if we used different error codes (haven't tested this assumption).

Anyway, I'm going to close this issue with "works as designed" on the `lnd` side. Errors with `StatusCode.UNKNOWN` are returned across all APIs for all sorts of issues, including invalid user input.
