### ISSUE TITLE
lncli cannot connect to rpcserver on 127.0.0.1 (Docker - Create lightning network cluster)

### ISSUE THREAD

**Issue by motorina0** [lightningnetwork/lnd#4937]
### Background
- following the tutorial described here: https://github.com/lightningnetwork/lnd/tree/master/docker

### Your environment
- not relevant

### Steps to reproduce
 - follow the steps until you get to:
```
# Generate a new backward compatible nested p2sh address for Alice:
alice$ lncli --network=simnet newaddress np2wkh 
```

### Expected behaviour
- `lncli` responds with an address
```
{
    "address": "rr1aiEqkxyRSMnBqzKDLjQhuPrqxQ5cQT4"
}
```

### Actual behaviour
- received the bellow error:
`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"`

### Solution
- provide the `--rpcserver` value to `lncli`:
`lncli --network=simnet --rpcserver $HOSTNAME:10009 newaddress np2wkh`

### Other Details
- running `netstat -l` returns:
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 43b6b890ff6b:10009      0.0.0.0:*               LISTEN 
```
- `lnd` uses the container name  (not 127.0.0.1)
- the change was introduced by these two PRs: 
    - https://github.com/lightningnetwork/lnd/pull/3461 and 
    - https://github.com/lightningnetwork/lnd/pull/4790/files#diff-1b54317674f1082613f107ed8f50de8535c35ef260c9182f0d4e17189b90576eR67

**Comment by motorina0** [comment]
- I can create a PR with the updated documentation (if that is the decided fix)

**Comment by guggero** [comment]
Thanks for the report.
The added `"--rpclisten=$HOSTNAME:10009"` was added to make sure the gRPC port can also be exposed to the host machine.
Instead of fixing the tutorial I think we should add an _extra_ listener for localhost to make sure the `lncli` command  can be used inside of the container without needing to specify the `--rpcserver` flag all the time.

So basically add the line ` "--rpclisten=localhost:10009" \` after line 67 in `start-lnd.sh`.
Feel free to open a PR for that.

**Comment by motorina0** [comment]
PR created: https://github.com/lightningnetwork/lnd/pull/4938
Not sure if the documentation (lines 53-56) should have also been updated to explain the extra `--rpclisten`
