### ISSUE TITLE
rpc: streamline PSBT funding API to better support batch-funding and expanded use cases

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#4972]
### Background

The current PSBT funding API uses the funding shim in open channels which is designed for flexibility in arguments

Pitfalls in this API:

- The `no_publish` directive is difficult to test as generating a failure condition for this argument is tricky
- It cannot be used with the REST request/response API and requires using the streaming endpoint
- The internal publish step of the transaction relies on the local mempool accepting the tx, which for CPFP or other chain spends may not be reliable
- It's tricky to batch funding across multiple nodes because of the internal control over the publish step

Suggested improvements:

- Reduce the abstraction in the high level API design to be more dedicated to batch PSBT funding
- Allow callers to be solely responsible for the funding transaction broadcast
- Add the option or document PSBT creation using LND on-chain funds for batch opens

### Your environment

* LND 0.12.0-beta

**Comment by guggero** [comment]
I started working on a `BatchOpenChannel` RPC that will make it easy to atomically open multiple channels at the same time (funded by the internal wallet, not using PSBTs).

Wanted to check back on this issue to see if there was anything that needs to be improved for the manual batch open process using the PSBT API.
From what I can see all the points mentioned in the issue above can be resolved without any changes to the channel open API:

Pitfalls in this API:

- The `no_publish` directive is difficult to test as generating a failure condition for this argument is tricky
   - You can set `no_publish` to `true` for all channels then manually publish the transaction once everything is ready. The main problem is that the external script needs to be responsible for cleaning up everything if the funding fails. This can be achieved by #5335. Perhaps we can simplify it quite a bit if the new `BatchChannelOpen` has parameters for the account to use for creating the funding TX (that way a HW wallet can be used if `lnd` watches the addresses for it) and a parameter for interrupting the process before the TX is signed. That way the first two steps (`OpenChannel` and `PsbtVerify`) would be done by `BatchChannelOpen` and the user only has to sign the TX, then call `PsbtFinalize` and manually publish the TX. The burden for cleaning up pending states would still fall to the user though.
- It cannot be used with the REST request/response API and requires using the streaming endpoint
   - With the WebSocket API all RPC endpoints can now be used via REST.
- The internal publish step of the transaction relies on the local mempool accepting the tx, which for CPFP or other chain spends may not be reliable
   - See point above about setting `no_publish=true` for all channels.
- It's tricky to batch funding across multiple nodes because of the internal control over the publish step
   - See point above about setting `no_publish=true` for all channels.

Suggested improvements:

- Reduce the abstraction in the high level API design to be more dedicated to batch PSBT funding
   - The API is a bit tricky to use, that's true. Perhaps we could simplify it a bit by 
- Allow callers to be solely responsible for the funding transaction broadcast
   - See point above about setting `no_publish=true` for all channels.
- Add the option or document PSBT creation using LND on-chain funds for batch opens
   - See https://github.com/lightningnetwork/lnd/blob/master/docs/psbt.md#batch-opening-channels

**Comment by Kixunil** [comment]
> has parameters for the account to use for creating the funding TX

This would interfere with PayJoin use case I had in mind, I hope it won't be mandatory.

I don't understand what's the problem with cleanup, also the use case for `abandonchannel` - shouldn't double-spend of the input be detected automatically?

**Comment by guggero** [comment]
> This would interfere with PayJoin use case I had in mind, I hope it won't be mandatory.

I was talking about the new [`BatchOpenChannel` RPC](https://github.com/lightningnetwork/lnd/pull/5356). You would only use that in cases where `lnd` is either the single funder or at least watches the UTXOs (hence the `--account` flag for watch-only imported accounts).

For the PayJoin use case you would use the existing `OpenChannel+psbt_shim`/`FundingStateStep` flow as it exists today. Removing the need for giving `lnd` the final, signed TX before it continues should fully allow that use case (see comment in #5215).

> I don't understand what's the problem with cleanup, also the use case for abandonchannel - shouldn't double-spend of the input be detected automatically?

There are three things that are possibly created during the funding flow (depending on how far everything got and how exactly you are funding the TX):
1. A funding _shim_/_intent_: Informs the wallet that a funding process is going on. This remains in memory for 10 minutes or until the next restart. Should be cleaned up with `FundingStateStep->CancelFundingShim`. Doing so will also tell the peer that the channel won't be created. If you don't do this it'll time out after 10 minutes on their end but until then you might run into "too many pending channels" errors if you try too often without cleaning up.
2. A _pending channel_. Once the channel negotiation has completed and it is shown as pending, it will stay around forever. If it doesn't confirm within 2 weeks the other party will forget it and it'll become useless. But the funding party will never forget it automatically. This is probably something that we should fix, registering a spend of the funding input should probably be a straight-forward way. Currently you need to call `AbandonChannel` to get rid of it (which is only available in dev builds, but see also https://github.com/lightningnetwork/lnd/pull/5335).
3. A _locked UTXO_: If `lnd` is the funder a UTXO will be locked for 10 minutes. If you don't unlock that your next funding attempt might fail if you only have one UTXO.

**Comment by Kixunil** [comment]
Thanks for clarification, I believe I understand it now.

I agree that spend of the input should automatically clean up things. Apart from it being the sane thing to do this would probably resolve all issues around PayJoin because PayJoin mandates always spending the input.
