### ISSUE TITLE
Unknown implications of enabling keysend by default

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#5190]
### Background

To my surprise, I found that keysend is still considered experimental after this much time and I don't see any explanations of risks if it's enabled. Because of this I can not decide if I'm willing to enable it for myself and the users of my project.

### Your environment

Irrelevant

### Steps to reproduce

* Read [config sample](https://github.com/lightningnetwork/lnd/blob/c27e9ab953e0bbb36ee3973146f84f4057f029d7/sample-lnd.conf)
* Try search for "lnd keysend experimental" (without quotes)
* Search keysend in github issues

### Expected behaviour

Some text explaining the risks and conditions what needs to happen to be no longer considered experimental.

### Actual behaviour

It's only marked as experimental with no further explanation.

**Comment by Roasbeef** [comment]
Keysend is being deprecated in favor of AMP. Keysend was meant to be just a hold over until AMP was rolled out, but that took longer than anticipated. It's marked as experimental as since it was purposefully not fully completed (no feature bits advertised, , etc). If you want to try out AMP on the command line, you can use this branch: https://github.com/lightningnetwork/lnd/compare/master...Roasbeef:amp-sendpayment-cli?expand=1 and enable it as you would keysend.

**Comment by Kixunil** [comment]
So if I enable it then the correct migration path later is enabling AMP instead? I suppose they aren't compatible, so there will be a period when both will have to be used in the network, right?
