### ISSUE TITLE
[Feature Request]: Add TxOut output scripts and values to ListLeases response

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#5202]
When calling ListLeases only the lock id, expiration, and outpoint is given

Since some portion of current funds may be locked at one time or another, it would be helpful for auditing purposes to be able to gain visibility into the funds of the referenced outpoint

While UTXOs are locked, funds become limited in visibility to an external observer, making balance auditing more difficult, especially for applications that choose to keep funds locked in an ongoing basis.

A change would add the TxOut details of each locked UTXO to allow for analyzing the value of the set of these locked funds.

**Comment by hitanshu-mehta** [comment]
Hi! I am super interested in this project and would like to work on this issue. 
I guess I need to add new fields in [this](https://github.com/lightningnetwork/lnd/blob/e7505c3e6b90f43857bd47a47d369d42f5af7f9f/lnrpc/walletrpc/walletkit.proto#L876) message.  I am a beginner and will be very happy to receive any guidance from your side.

**Comment by guggero** [comment]
Yes, adding new values to `UtxoLeases` (https://github.com/lightningnetwork/lnd/blob/e7505c3e6b90f43857bd47a47d369d42f5af7f9f/lnrpc/walletrpc/walletkit.proto#L823) is what is needed. You can edit that file directly and then run `make rpc` to compile everything (you only need to have `make` and `docker` installed, apart from `golang` of course).

The problem is that the wallet currently doesn't return more information about the locks. So a PR in https://github.com/btcsuite/btcwallet (which is used as the wallet library in `lnd`) is needed first that collects and returns the required information here: https://github.com/btcsuite/btcwallet/blob/master/wallet/wallet.go#L2714

**Comment by hitanshu-mehta** [comment]
Thank you @guggero! I will create an issue in btcwallet and if maintainers approve of these changes, I'll also create PR.
