### ISSUE TITLE
lnd 0.12.1 exits prematurely with fatal error (can not finish compaction db)

### ISSUE THREAD

**Issue by Stronzo-sky** [lightningnetwork/lnd#5234]
### Background

Can not start lnd.

### Your environment

lnd 0.12.1-beta
Linux 4.15.0-142-generic #146-Ubuntu SMP

### Steps to reproduce

LND were found in a strange state -- it where kinda running (wrote to log, all external ports ok, but lncli could not connect to rpc with an error "all subconns are in transientfailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"). 

After correct manual shutdown and restart it starts compacting database and fails with an error (see files). 
[error2204.txt](https://github.com/lightningnetwork/lnd/files/6357106/error2204.txt)
[error2204-1.txt](https://github.com/lightningnetwork/lnd/files/6357107/error2204-1.txt)

After each compaction attempt it leaves a file temp-dont-use.db of exactly same size:
4096 Apr 22 09:14 .
4096 May  3  2019 ..
1256878080 Apr 22 08:31 channel.db
26746880 Apr 22 07:49 sphinxreplay.db
8 Feb 23 19:45 sphinxreplay.db.last-compacted
536805376 Apr 22 09:24 temp-dont-use.db
536805376 Apr 22 08:55 temp-dont-use.db.off
536805376 Apr 22 09:05 temp-dont-use.db.off1

Removing "last-compacted" doesnt help as the problem is that it can not finish the compaction process.

Adding memory to VPS also doesnt help.

### Expected behaviour

Finish compaction and start lnd

### Actual behaviour

lnd unable to finish compaction process due to a fatal error.

**Comment by Stronzo-sky** [comment]
Update: I was able to start lnd after removing "db.bolt.auto-compact=true" from lnd.conf. But working like this seems dangerous to me as it looks like a corrupted channel.db?

**Comment by guggero** [comment]
From looking at the log, I see `runtime/asm_386.s`. Is the Linux you're running a 32bit OS? Or is the VPS running on 32bit hardware? Or is your `lnd` version simply the 32bit version?
I'm pretty sure you're running into this because the DB grew too large for 32bit processes. Try upgrading to the 64bit version of lnd and compacting _should_ work.
If you're unable to upgrade to 64bit, you can also temporarily fix this by shutting down `lnd`, moving the `channel.db` file to a 64bit system, running [`chantools compactdb`](https://github.com/guggero/chantools/blob/master/doc/chantools_compactdb.md) on it and then moving the result back to your original machine. Please be careful to only ever have one version of the DB around. Never start from an old version if a newer one was ever started up!

**Comment by Stronzo-sky** [comment]
I cant belive the solution was this easy. Just used x64 build. Thank you very much Oliver, you`ve saved me again!
