### ISSUE TITLE
Can't start server due to duplicate transaction being rejected by network

### ISSUE THREAD

**Issue by champbronc2** [lightningnetwork/lnd#529]
![image](https://user-images.githubusercontent.com/7240180/34395199-823f6a32-eb2c-11e7-9c8f-4502b13435f1.png)

Using Windows 7. I closed a bunch of payment channels last night, then closed my client, then restarted my client today and it won't load anymore.

**Comment by champbronc2** [comment]
Just an update, I was able to fix my node by simply re-running LND multiple times. Eventually just fixed itself..

**Comment by halseth** [comment]
@cfromknecht

**Comment by cfromknecht** [comment]
@champbronc2 this looks to be an edge case in our not-yet-robust handling of publication errors. Currently, we only ignore the duplicate error messages of the form "Transaction rejected:", [source](https://github.com/lightningnetwork/lnd/blob/master/utxonursery.go#L959), though this error message has the form "Transaction <txid> rejected". The ideal solution is to have a well-tested mapping of errors returned by btcd and neutrino to concrete error types in lnd. Failing due to duplicate publications can be safely ignored in many cases, as it just means that the txn was already broadcast before going down.

**Comment by cfromknecht** [comment]
By the log statements, I'm assuming this is using neutrino mode. I was able to track down the place where [this error format is used](https://github.com/lightninglabs/neutrino/blob/master/query.go#L578:24). We have yet to expand our integration tests to fully support integration tests, which is why the filter only checks for the format produced by btcd.

**Comment by champbronc2** [comment]
Yep, was using neutrino mode. Thanks!

**Comment by cfromknecht** [comment]
@champbronc2 thanks for reporting this, going to make an attempt at getting the behaviors to coincide even if we don't have full support for neutrino in the integration suite
