### ISSUE TITLE
LND paid insanely high closing fees

### ISSUE THREAD

**Issue by Kixunil** [lightningnetwork/lnd#5345]
### Background

A channel that got closed recently paid 95 sat/vB fee on what I understand to be sweep transaction. At current mempool, 2 sat/vB transactions should confirm in next block.

### Your environment

* version of `lnd` 0.12.1
* which operating system (`uname -a` on *Nix) Linux <censored> 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend - bitcoind v0.20.0
* any other relevant environment details - the channel was opened with LOOP node

### Steps to reproduce

0. Open a channel with LOOP with reasonably small fees
1. Wait until LOOP closes the channel (after a few days at most)
2. Check fee rates on closing transactions

### Expected behaviour

At current situation, sweep fee rate should be at 2-3 sat/vB.

### Actual behaviour

Fee rate was 95 sat/vB.

**Comment by Roasbeef** [comment]
> A channel that got closed recently paid 95 sat/vB fee on what I understand to be sweep transaction. At current mempool, 2 sat/vB transactions should confirm in next block.

Fee negotiation as defined right now in the protocol is an incremental negotiation process. Both sides advertise a fee rate then attempt to incrementally walk towards them. If one side advertises a very high fee, and the other a low fee, then the final fee will be somewhere in the middle. There's some idea to improve things by advertising an absolute range on both sides, with the initiator (since they pay the fees) just picking one of them.

**Comment by Kixunil** [comment]
Hmm, that's quite sad, if an abusive node sucks up all liquidity and then closes the channel with very high fee, it's pure loss for the one who opened it. It'd be really great if something was done about it.

**Comment by BhaagBoseDK** [comment]
LND should not accept a fee for coop close which is higher than what would have been for a force close.
