### ISSUE TITLE
Watchtower client: unable to remove tower: removing towers is disallowed while a new session negotiation is in progress

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5361]
### Background

I have the watchtower connection issues described in #5360. In an attempt to fix this issue, I wanted to remove the watchtower. However, this is not possible (even hours after the initial attempt):

`removing towers is disallowed while a new session negotiation is in progress`

How can I remove a tower that fails to connect?

### Your environment

lnd 0.13.0-rc5
Linux server 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
bitcoind 0.21.0 (bitcoin core)

**Comment by guggero** [comment]
This is a known issue that we definitely need to fix. A temporary workaround is to connect to a working watchtower. Once the session was initialized successfully you should be able to remove both towers if you start with the offline one.

**Comment by C-Otto** [comment]
Got it. I was able to remove the bogus towers. I'll leave this open because this isn't possible before having a successful connection. Aside from this, I think the CLI always shows an error "tower not found" even if this is due to a successful removal.

**Comment by xanoni** [comment]
> This is a known issue that we definitely need to fix. A temporary workaround is to connect to a working watchtower. Once the session was initialized successfully you should be able to remove both towers if you start with the offline one.

@guggero This workaround doesn't work for me. My current node state is as follows: connected to 3 bad watchtowers and 3 good watchtowers.

Whenever I try to remove a watchtower (no matter if good or bad), I get this:

`[lncli] rpc error: code = Unknown desc = cannot remove last tower address`

**Comment by xanoni** [comment]
suddenly it looks like this ... I'll turn wtclient off for now, don't like (apparently) undefined behavior on a production node

```
$ lncli wtclient towers |grep active
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": true,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
            "active_session_candidate": false,
```

**Comment by fabu21** [comment]
Hi guys. I have a similar problem and got stuck using the wtclient.

I added a watchtower some time ago and this tower is not reachable anymore. As soon as I start LND with wtclient.active=true I run into the following issue:

`lnd    | 2021-12-19 10:58:42.656 [ERR] LTND: Shutting down because error in main method: unable to create server: tower not found
lnd    | 2021-12-19 10:58:42.656 [ERR] LTND: error stopping tor controller: invalid arguments: unexpected code
lnd    | unable to create server: tower not found
lnd    | 2021-12-19 10:58:42.679 [INF] LTND: Shutdown complete
lnd    |
lnd    | 2021-12-19 10:58:43.394 [INF] LTND: Version: 0.14.1-beta commit=v0.14.1-beta, build=production, logging=default, debuglevel=info`

If I disable the wtclient I can't add new watchtowers or remove the current one. So I'm stuck in this situation and cannot activate the wtclient.
Is there anything I can do in this situation?

**Comment by C-Otto** [comment]
@fabu21 this sounds like a different issue. Please open a new GitHub issue instead.

**Comment by bota87** [comment]
I even have issue with a watchtower and can't remove it
`2022-01-31 22:13:15.184 [ERR] WTCL: (anchor) SessionQueue(YYYYYYYY) unable to dial tower at QQQQQQ@RRRRRRR.onion:9911: dial proxy failed: socks connect tcp 127.0.0.1:9050->RRRRRRR.onion:9911: unknown error host unreachable`

`lncli wtclient remove QQQQQQ`
`[lncli] rpc error: code = Unknown desc = removing towers is disallowed while a new session negotiation is in progress`
