### ISSUE TITLE
Add total number of payments in REST GET /v1/payments API

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightningnetwork/lnd#5382]
Currently, LND's payments API returns the `last_index_offset` field, but it cannot be used as total number of payments due to missing deleted payments from the list. Please add total payments for easier & faster pagination implementation for the UI.

* version of `lnd`: 0.12.1-beta
* which operating system (`uname -a` on *Nix): Windows
* version of `btcd`, `bitcoind`, or other backend: v0.19.0.1 (64-bit)

### Steps to reproduce
* Call GET /v1/payments API with max_payments=10 & index_offset=0 & reversed=true

### Expected behaviour
The API should also include the total number of records for `complete` and `incomplete` payments.

### Actual behaviour
* It will return first and last offset indices but not total number of records.

**Comment by de6df1re** [comment]
Digging in on this ... should have an analysis update within 24 hrs.

**Comment by de6df1re** [comment]
Hello @ShahanaFarooqui - clarifying question please... does the include_incomplete=true parameter meet your needs?  Per your example:  

`
v1/payments?include_incomplete=true&max_payments=10&index_offset=0&reversed=true`

**Comment by ShahanaFarooqui** [comment]
@de6df1re We need ‘total_payments’ count for both the cases. For example, if the include_incomplete is true then the total_payments count should return total number of complete + incomplete payments. If it is false then the API should return the total number of completed payments.

**Comment by de6df1re** [comment]
OK thanks... will work through some options and present them here in the next day or two.

**Comment by de6df1re** [comment]
**Analysis Update:**  

Most of the logic for the API/CLI call to get a list of payments lives in lnd/rpcserver.go ListPayments() and  lnd/channeldb/payments.go QueryPayments().  In ListPayments(), the query parameters for a 'slice' of payments as provided by consumer are formulated and then passed to QueryPayments().  In QueryPayments(), a connection to the channeldb (boltdb) is made, and the slice is returned.  The logic for "IncludeIncomplete" also lives in QueryPayments().  QueryPayments() return a PaymentResponse which includes the payments, firstindexoffset, and lastindexoffset.  ListPayments() returns a similar object with similar attributes called ListPaymentsResponse.  

**Intention Update:** 

I think we could  add a total_payments to the API/CLI response at the same level as first_index_offset and last_index_offset.  It may not always be clear to the consumer that total_payments would  not be the same as the total payments actually being returned based on the query parameters, and could differ depending on the IncludeIncomplete flag as mentioned in the request.  Another option would be to add additional response elements, something like total_returned_payments, total_complete_payments, total_incomplete_payments, and total_payments.  This logic would be a bit more complicated and maybe unnecessary?     

I'm also intending to determine the best place to add this logic.  It could live in QueryPayments() as a separate chunk of logic, which is where the DB is being queried, and simply count the various payments and set them as new elements in the response.  However QueryPayments is currently  focused on a slice of detailed payment information as determined by the query parameters (and not total counts)... so it may make sense to isolate this logic in another function in channeldb/payments.go like QueryPaymentsTotals() that could be used elsewhere as needed and called by ListPayments when invoked by API/CLI.   However, that would introduce two calls to the database (instead of one) in a single API/CLI request and which may not be desirable? 

I will keep working based on intentions above, but welcome all feedback.

**Comment by de6df1re** [comment]
An additional option I will try is to call QueryPayments twice from ListPayments.  Once to get the total counts, and once to get the smaller slice requested.

**Comment by de6df1re** [comment]
Code changes and testing in progress. Should have PR for evaluation this week.

**Comment by tvolk131** [comment]
@guggero this was fixed by #6463 right?

**Comment by guggero** [comment]
Yes, thanks for noticing @tvolk131!
Fixed by https://github.com/lightningnetwork/lnd/pull/6463.
