### ISSUE TITLE
Paying via SendPaymentV2 to payment hash does not automatically use MPP (if not explicitly setting DestFeatures)

### ISSUE THREAD

**Issue by bjarnemagnussen** [lightningnetwork/lnd#5482]
### Background

Paying to a payment hash using the `RouterRPC.SendPaymentV2` without specifying the destination features will always result in sending exclusively via non-MPP and _not_ fallback to MPP. 

I am not completely sure if this is in fact a mis-behaviour or on purpose. I hope my description below is detailed enough to answer this though.

### Your environment

* version of `lnd`: master

### Steps to reproduce

Calling the RouterRPC SendPaymentV2 with 
 * `Dest` set to the receiving node pubkey, 
 * `Amt` set to the total amount from the invoice, 
 * `PaymentHash` set to the hash from the invoice, and 
 * `PaymentAddr` set to the secret from the invoice 

will not fallback to MPP payment even if the remote node supports MPP and those features can be retrieved from the graph (but are not explicitly set with the call to `SendPaymentV2` with `DestFeatures`).

Only when explicitly setting `DestFeatures` to e.g. `[9, 14, 17]` will the payment fallback to MPP.

### Expected behaviour

The RPC [documentation](https://api.lightning.community/#sendpaymentv2) says that if `DestFeatures` is not set it will be assumed from the graph. I would therefore expect that if the remote node supports MPP and my node knows it from the graph, then sending to the payment hash via `SendPaymentV2` should fallback to MPP if non-MPP is not possible. 

### Actual behaviour

If `DestFeatures` is not set, then inside `pathfind.go`
https://github.com/lightningnetwork/lnd/blob/bb5c3f3b51c7c58296d120d5afe4ed0640d5751e/routing/pathfind.go#L433-L442

it does load the features for the remote from the graph correctly on the first (non-MPP) trial of payment.

However, as those features are not stored in the payment request, inside the calling function in `payment_session.go`
https://github.com/lightningnetwork/lnd/blob/bb5c3f3b51c7c58296d120d5afe4ed0640d5751e/routing/payment_session.go#L324-L328

it will not continue to try sending via MPP if non-MPP was unsuccessful and only do it if explicitly set via `DestFeatures` on the request.

#### Note

This does of course not apply when sending directly using the invoice in `PaymentRequest` if the Bolt11 encodes the destination features, as in this case LND will automatically extract and use them from the invoice. I haven't tried what happens if the Bolt11 invoice does _not_ include destination features though.

**Comment by Roasbeef** [comment]
> This does of course not apply when sending directly using the invoice in PaymentRequest if the Bolt11 encodes the destination features,

This is expected, since we don't know if they support MPP or not if we don't have their feature bits available (or even if they want an MPP payment. The other thing is that if you're sending a payment to a destination without an invoice, then that means you don't know a payment address, which is actually _required_ when using an MPP payment to ensure things are secure against the old zero-value invoice probing attacks. In short, in order to use MPP securely, you need a payment address which is found in the invoice, as it must be known by the receiver to prevent the probing attacks mentioned. 

> it will not continue to try sending via MPP if non-MPP was unsuccessful and only do it if explicitly set via DestFeatures on the request.

You're right about this AFAICT, but it's partially made moot by the above point: you can't use MPP securely without obtaining an invoice first. If you _really_ want to force it (I wouldn't advise doing so), you can set the feature bit set yourself manually.

**Comment by bjarnemagnussen** [comment]
Alright, thanks for the explanation @Roasbeef !
