### ISSUE TITLE
Force closed channel (pending) not shown in `lncli closedchannels`

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#5574]
### Background

I force-closed a channel and now have to wait for my funds to arrive in my wallet (limbo). This is fine and it works as expected. 

However, the channel isn't shown in `lncli listchannels` (that's fine, it's closed, after all), but it also does not show in `lncli closedchannels`. The channel is shown in `lncli pendingchannels`, though. I believe the channel should be listed in `lncli closedchannels`, as the channel is already closed, and only the retrievel of funds is pending. As I derive certain statistics out of these outputs, this is highly confusing. The peer just dropped out of my statistics, messing up my numbers. And, I guess, it will reappear once my limbo balance arrives in my wallet.

As `lncli pendingchannels` doesn't include the channel ID, fixing my scripts doesn't seem to be possible.

### Your environment

- lnd 0.13.1 with some patches
- Linux server 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
- bitcoind 0.21.0 (bitcoin core)

### Steps to reproduce

Force-close a channel with local balance that will be returned after the time lock. Run `lncli listchannels` and `lncli closedchannels`, try to find the channel.

### Expected behaviour

The channel appears in `lncli closedchannels`.

### Actual behaviour

It does not show up.

**Comment by carlaKC** [comment]
This behaviour is expected. `lnd` does not consider channels closed until they are fully resolved on-chain. We can't report on the channel in `closedchannels` because the outcome of the htlcs on the channel have not yet been resolved (we don't know whether they will timeout or claim), likewise the commit output is also _theoretically_ not finalized because there could be a justice tx claim (although unlikely).

I would suggest updating your statistics to include pending channels. This is part of the lifecycle of a channel, and it doesn't make sense to make an aesthetic change to include these channels in closed channels when they are not yet resolved, IMO it would be even more confusing.

**Comment by C-Otto** [comment]
OK, I agree. I'll create a follow-up issue (chan ID is missing in `lncli pendingchannels`).
