### ISSUE TITLE
Question: does `lnd` penalize nodes that change their channel fee policies frequently?

### ISSUE THREAD

**Issue by xanoni** [lightningnetwork/lnd#5654]
Given that several `lnd` management tools support dynamic fee setting, I was curious if `lnd` somehow penalizes nodes that change their fees too often (e.g., by reducing the routing probability, or similar)? Obviously, a channel is less attractive if the fees are higher, so I'm just talking about the effects of the fee "volatility".

If yes, where can I find the relevant logic in the code to better understand the implications?

Also, does the (proprietary) Lightning Terminal web dashboard factor this into any of its 5-6 metrics?

Do we know if other node software handles it similarly?

**Comment by Roasbeef** [comment]
No not explicitly, getting a new update during routing is a routine part of path finding.  If we route thru a channel and need to get a new channel update, then we'll give it a second chance, and try again. However if the update changes _again_ during that second chance period, we may penalize it for a period of time. In practice, this is pretty rare though, and would only happen if a node is trying to update their fees every second, which won't actually propagate that quickly due to dampening at the gossip layer. 

Btw, in the future using the new discussions feature may be better for issues like this: https://github.com/lightningnetwork/lnd/discussions
