### ISSUE TITLE
Invalid continuation byte when trying to restore Umbrel channel backup

### ISSUE THREAD

**Issue by StefanJson** [lightningnetwork/lnd#5727]
### Background

I'm not sure if this is an issue to publish here but you have to remove it if not.
I'm trying to restore a Bitcoinwallet and channel backup from Umbrel but when I click Restore I get "invalid continuation byte".

### Your environment

* version of `lnd` v0.13.1-beta
* which operating system (`uname -a` on *Nix) Ubuntu Server 21.04
* version of `btcd`, `bitcoind`, or other backend Bitcoin Core v0.21.1
* any other relevant environment details I'm using Blixt wallet v 0.3.3 (27) on an iPhone 12 Pro.

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
I put in the seed phrase and chose my Lightning channel backup created in Umbrel and when I click Restore I get "invalid continuation byte".

### Expected behaviour

Tell us what should happen The wallet and channels are suposed to be restored.

### Actual behaviour

Tell us what happens instead When I click Restore I get "invalid continuation byte" and nothing more happens.

**Comment by guggero** [comment]
The error message `invalid continuation byte` is not coming from `lnd`. Googling for that error tells me that it's likely coming from Python code. Are you trying to restore a wallet created in Umbrel in a Blixt wallet? Or are you trying to restore on Umbrel?
I assume either the `channel.backup` you are trying to use is a custom format created by Umbrel or something else is going wrong.

Closing the issue because I'm pretty sure the error isn't coming from `lnd` but the UI/App you're using.

**Comment by StefanJson** [comment]
Ok, I see. I was trying to restore a channel backup from Umbrel with Blixt wallet because I made a mistake with Umbrel so I now have a new seed phrase in Umbrel. I have to look for another solution.
Thank you for your response!
