### ISSUE TITLE
rpc trying to pay same invoice twice should return preimage as well

### ISSUE THREAD

**Issue by anycolo** [lightningnetwork/lnd#5926]
If you pay a bolt11 invoice twice, first time you get the preimage in the json, but the second time you only get
{'status': 'invoice is already paid'}
Could we receive the preimage as well?

**Comment by Roasbeef** [comment]
If you do `TrackPayment`, you'll get the last update which'll include the pre-image if the payment has completed: https://api.lightning.community/#trackpaymentv2

**Comment by mohamedawnallah** [comment]
@yyforyongyu I think this issue is already resolved ?
![2024-02-04_18-28](https://github.com/lightningnetwork/lnd/assets/69568555/1b9c6245-2436-4a9b-b8be-2d78121084c6)

**Comment by mohamedawnallah** [comment]
@yyforyongyu Is this issue already resolved ?
![302117487-1b9c6245-2436-4a9b-b8be-2d78121084c6](https://github.com/lightningnetwork/lnd/assets/69568555/358ffa79-8ee3-40c8-8e34-5e6a25ac9a1b)

**Comment by guggero** [comment]
I think it's correct that an error is returned, that way app developers can be certain that the payment didn't succeed. If we went ahead and added a new status (for example `INVOICE_ALREADY_PAID`) then API users that aren't aware of the new code would simply show the payment as succeeded.

@saubyk since the proper way is to check using `TrackPayment` I would vote for closing the issue.

@mohamedawnallah the `--json` flag only affects the successful output (to switch from the live-updated table view to a JSON rendered output). But you got an error message, which in `lncli` is always formatted that way.

**Comment by saubyk** [comment]
Agree with the assessment here. Doesn't make sense to break the existing rpc behavior to return pre-image, when we have an rpc to get the pre-image, if required.

developers can catch the error status 'invoice already paid' and invoke trackpayment to get the pre-image.

closing this issue
