### ISSUE TITLE
BIP32 HD root key, when is used to recover electrum wallet (master private key) not  funds. not history

### ISSUE THREAD

**Issue by webdinos** [lightningnetwork/lnd#5929]
### Background

I used chantools for extract root key from seed lnd wallet.
When I create a new wallet from a master private key , I am seing legit addresses (instead of right segwit ones), and transactions history neither is shown. 

### Your environment

* version of `lnd`: lncli version 0.13.3-beta commit=v0.13.3-beta
* which operating system (`uname -a` on *Nix); Linux raspi4FN 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core RPC client version v22.0.0
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
create a electrum wallet from master private key.

### Expected behaviour
It should list my btc segwit adresses, ransaction history and funds

### Actual behaviour
list legit adresess, no history. no funds

Tell us what happens instead

**Comment by guggero** [comment]
You need to tell Electrum to use a BIP84 derivation scheme when importing the master private key. Perhaps that works automatically if `chantools` creates a `zpriv` instead of an `xpriv`.
Also, see https://www.lightningnode.info/technicals/restorelndonchainfundsinelectrum

In any case, this isn't an `lnd` issue, closing.
