### ISSUE TITLE
LND crash on MyNode 

### ISSUE THREAD

**Issue by Bennettd77** [lightningnetwork/lnd#5945]
### Background

I've had a crash of LND v0.12.1 and the guys at MyNode haven't seen a crash log like this. They suggested seeking help here and I am hoping that you guys can, indeed, help me. 

### Your environment

lnd v0.12.1
MyNode v0.2.27
btcd 0.21.0

### Steps to reproduce

I am placing a screenshot of the lnd status as an attachment for this section.

![This](https://user-images.githubusercontent.com/7851939/140655950-f4bc1506-bad6-4dbe-8ca6-0136f0f8baaa.png)

### Expected behaviour

My Lightning Network Node should be running

### Actual behaviour

It's offline and I cannot get it back.

**Comment by Roasbeef** [comment]
Your screen shot doesn't show the full stack trace, it should be written to `sdterr`. 

Also you're on an old version that's vulnerable to a recently announced CVE, [I recommend updating asap](https://github.com/lightningnetwork/lnd/releases/tag/v0.13.3-beta).

**Comment by guggero** [comment]
Without the full stack trace it's hard to say what the exact cause is. But from similar crashes it can be one of the following things:
 - Your DB needs to be compacted (`db.bolt.auto-compact=true`)
 - You are running a 32bit `lnd` and the `channel.db` file approached 1GB. You need to upgrade to a 64bit OS and 64bit `lnd` version.
 - Your `channel.db` file got corrupted because of an unclean shutdown. In that case you'll need to recover your node from seed/SCB.

**Comment by pangyuteng** [comment]
@guggero Thank you for the tips. I happen to be running a 32-bit, and are seeing the similar tracebacks!  Checked the `channel.db` size and indeed it hit 2GB.

**Comment by guggero** [comment]
Okay, closing this as it's a known limitation of 32-bit systems. Feel free to reopen if upgrading to a 64-bit OS doesn't solve your issue.
