### ISSUE TITLE
Transactions and wallet balance are empty after sending a satoshi to the public address

### ISSUE THREAD

**Issue by kaganovych** [lightningnetwork/lnd#5949]
### Background
Hey!
I'm building an Android app and using Android aar and generated proto files. 
I created a brand-new wallet, generated an address with [nextAddr](https://api.lightning.community/#nextaddr) and sent some bitcoins with a help of this bitcoin [faucet](https://bitcoinfaucet.uo1.net/send.php). I sent it to this `tb1q7n88z5p07edtvmxyqd3tcs3re46u2zauvnpwf2` address and the transaction is confirmed and they should be available in my wallet. But when I try to get my transactions and wallet balance - they are empty. The byte array in transactions is `null`.

Thanks for help!

### Your environment

* version of `lnd` - I generated proto files from this [commit](https://github.com/lightningnetwork/lnd/commit/5681c0eecfac1277834ee54bf4d5e08a9fc46551)
* which operating system (`uname -a` on *Nix) - MacOS Big Sur.

### Steps to reproduce

Run the daemon with next commands 
```"""--bitcoin.active
                        --lnddir="${file.path}"
                        --bitcoin.node=neutrino
                        --bitcoin.testnet
                        --tlsdisableautofill
                        --no-macaroons""".trimIndent()
```
Create a wallet with `Lndmobile.initWallet` using seed and password.

Generate address via
```
val request = Walletkit.AddrRequest
            .getDefaultInstance()
            .toByteArray()
```

Send bitcoins on testnet.
Call  
```
val request = LightningOuterClass.GetTransactionsRequest
            .getDefaultInstance()
            .toByteArray()

        Lndmobile.getTransactions(request, object : Callback)
```

### Expected behaviour

I should receive the list of transactions.

### Actual behaviour

The response of the callback is empty.

**Comment by guggero** [comment]
What does the output of `GetInfo` show? Is `synced_to_chain` true? It probably just takes quite a while for the Neutrino wallet to sync the whole chain.

**Comment by Jorikua** [comment]
I haven't tried to get info.
I've implemented it, the response is successful and now it crashes if I want to parse it.
```
val request = LightningOuterClass.GetInfoRequest.getDefaultInstance().toByteArray()
```

```
Lndmobile.getInfo(request, object: Callback)
```

In this line the JNI crashes. I believe it cannot parse the byte array.
```
val response = LightningOuterClass.GetInfoResponse.parseFrom(p0)
```

**Comment by Jorikua** [comment]
Also, if I recover this wallet with seed, I can see transactions.

**Comment by guggero** [comment]
Can you post some logs? Or error messages from the `GetInfo` crash?

**Comment by Jorikua** [comment]
So, when I run a daemon and unlock the wallet, the state becomes `RPC_ACTIVE`.
The last info message
```
[INF] BTCN: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch: No address associated with hostname
```

Here're the logs.
[logs.zip](https://github.com/lightningnetwork/lnd/files/7498284/logs.zip)

**Comment by guggero** [comment]
You don't seem to have all the classes generated that you need: `java.lang.NoClassDefFoundError: no.bitmynt.data.definitions.LightningOuterClass$GetInfoResponse$FeaturesDefaultEntryHolder`

And for the actual issue: I think you might need to manually connect to some neutrino peers to start the chain download.

**Comment by Jorikua** [comment]
I had a feeling as well that there's something with generated classes.
Also, on iOS I don't need to make any additional manipulations. Just use Lndmobile and it works, so I guess that it should work on Android as well.

**Comment by Jorikua** [comment]
So I created all the classes from scratch from the latest version from git, and it still crashes. Question: can I change the package name of those generated classes or it should remain the same and the JNI code somehow depends on those package names?

**Comment by Roasbeef** [comment]
Based on the timing here, you might've been hitting a neutrino related bug that was recetnytl fixed.

If you try with lnd v0.14.0-beta.rc2, do things work? 

> it works just fine, but the second response doesn't have a total balance. It only has confirmed and unconfirmed. Is it intended that I have to use the second one?


Are you making new wrappers around the generated API? Confirmed and unconfirmed sum up to the total, or you can read `total_balance`.

**Comment by Jorikua** [comment]
Hey. Okay, I'll try that. About neutrino bugs: I described 2 unexpected behaviors:
1. I can't parse `GetInfo`, cause it crashes. But as I can observe, `synced_to_chain` is false, that's why I don't see any transactions in a long period of time.
2. No, I don't build any wrappers. At least yet. There's 1 request class for wallet balance: `LightningOuterClass.WalletBalanceRequest`, but there're 2 response classes for balance: `LightningOuterClass.WalletBalanceResponse` and `LightningOuterClass.WalletAccountBalance`. The first one crashes if I try to use it and it **has** `total_balance` field. The second one doesn't have the `total_balance` field, but it parses the response. And this is really confusing.

**Comment by Jorikua** [comment]
Basically, the same crash happens when I try to calculate the fee. 
```
val request = LightningOuterClass.EstimateFeeRequest.newBuilder()
            .setTargetConf(2)
            .setMinConfs(0)
            .putAddrToAmount(address, 10000)
            .setSpendUnconfirmed(false)
            .build().toByteArray()
```
This is how I parse it 
```
val response = LightningOuterClass.EstimateFeeResponse.parseFrom(p0)
```
Logs
[logs.zip](https://github.com/lightningnetwork/lnd/files/7512437/logs.zip)

So there may be 2 reasons: generating of classes failed somewhere or it's incompatible with protobuf version that I've sent earlier.

**Comment by martinlachev** [comment]
> You don't seem to have all the classes generated that you need: `java.lang.NoClassDefFoundError: no.bitmynt.data.definitions.LightningOuterClass$GetInfoResponse$FeaturesDefaultEntryHolder`
> 
> And for the actual issue: I think you might need to manually connect to some neutrino peers to start the chain download.

Is this necessary and if I do not what is the default behavior of neutrino?

**Comment by Jorikua** [comment]
So I built the aar from the `v0.14.0-beta.rc2` tag. Problems with parsing didn't go away. Can't parse `Lndmobile.estimateFee()` and `Lndmobile.getInfo()`. And `wallet balance` as well.

**Comment by guggero** [comment]
Sounds like something could be wrong with the emulator? https://stackoverflow.com/questions/43922288/rejecting-re-init-on-previously-failed-class-java-lang-classnt-java-lang-nocl

I just googled part of the error you posted, I don't really have any experience with Android.

**Comment by Jorikua** [comment]
Nope, it's not related to emulator. I'm testing on a real device. I believe there could be 2 options: either there's a difference in versions of protobuf or the classes are generated not fully/in a wrong way.

**Comment by guggero** [comment]
Can you try with the older versions of `io.grpc:grpc-protobuf:1.8.0` as [described here](https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/java.md)? We did update some gRPC libraries with `v0.14.0-beta.rcX`, not sure what version of the Java libraries that translates to...

**Comment by Jorikua** [comment]
Nope, this dependency doesn't help either, unfortunately.

**Comment by guggero** [comment]
Hmm, and you get the same errors if you use those dependencies with an lnd `v0.13.x-beta` version?

**Comment by Jorikua** [comment]
So, the generated build is `Version: 0.13.4-beta commit=v0.13.4-beta, build=development, logging=default, debuglevel=info`.
In this version I don't have the `LightningOuterClass.java`, but it generated for me `Rpc.java`. Maybe you renamed it in newer version. But the problem remained the same.

**Comment by hsjoberg** [comment]
@Jorikua 

> Maybe Lndmobile.getInfo(request, object : Callback) expects not LightningOuterClass.GetInfoRequest and not LightningOuterClass.GetInfoResponse ?

No, from what I can tell you're using the lib correctly.

However I'm not sure I follow where 

```
implementation "com.google.protobuf:protobuf-java:3.10.0"
implementation "com.google.api.grpc:proto-google-common-protos:1.17.0"
```
comes from. Because those are not the libs I use when dealing with protobuf/gRPC in an Android Java environment.

This is what I've been using for around 2 years without any issues:
https://github.com/hsjoberg/blixt-wallet/blob/13ddff7248def3572b53f73e64ed24040a1864db/android/build.gradle#L18
https://github.com/hsjoberg/blixt-wallet/blob/13ddff7248def3572b53f73e64ed24040a1864db/android/app/build.gradle#L2
https://github.com/hsjoberg/blixt-wallet/blob/13ddff7248def3572b53f73e64ed24040a1864db/android/app/build.gradle#L262-L268
https://github.com/hsjoberg/blixt-wallet/blob/13ddff7248def3572b53f73e64ed24040a1864db/android/app/build.gradle#L310
https://github.com/hsjoberg/blixt-wallet/blob/13ddff7248def3572b53f73e64ed24040a1864db/android/app/build.gradle#L342-L355

I also have an example project up here on how to make it work on Android:
https://github.com/hsjoberg/lndmobile-speed-tests
(Haven't been updated for while but shouldn't really matter.)

I've full blown backend here but it's most probably more difficult to follow:
https://github.com/hsjoberg/blixt-wallet/blob/master/android/app/src/main/java/com/blixtwallet/LndMobile.java
https://github.com/hsjoberg/blixt-wallet/blob/master/android/app/src/main/java/com/blixtwallet/LndMobileService.java

**Comment by hsjoberg** [comment]
Also, classes not being found at runtime sounds like ProGuard is in action?
Perhaps try disabling ProGuard and see what happens.

Here's how I made ProGuard ignore minimization:
https://github.com/hsjoberg/blixt-wallet/blob/13ddff7248def3572b53f73e64ed24040a1864db/android/app/proguard-rules.pro#L35

**Comment by Jorikua** [comment]
No, Proguard is switched off. I'm testing on debug builds.
I used already generated classes from `make rpc` command. But in your case you're using protobuf plugin in and proto files in order to generate classes in compile time in project itself. I'll try this approach, thanks.

**Comment by Jorikua** [comment]
@hsjoberg Sir, you saved my day. Thank you! So the reason of the crashes was that I generated java proto files from the terminal instead of using the Gradle plugin for Android. When I imported proto files directly to the project and plugin generated classes for me - everything launched.
@guggero I can write docs for the installation of LND on Android from scratch if it's needed.

**Comment by guggero** [comment]
Awesome, that's great to hear :tada:  Thanks @hsjoberg for your input.

@Jorikua updating the installation docs for Android would be highly appreciated.

**Comment by hsjoberg** [comment]
@Jorikua Cheers! 🎉

**Comment by Jorikua** [comment]
@guggero okay. Will do that and create a PR.
Thanks everyone for helping. Really appreciate it.

**Comment by Jorikua** [comment]
Also, since we're here, one question: is there a way to get `pending` transactions that either sent or are going to be received?

**Comment by guggero** [comment]
The `getTransactions()` call gives you all transactions that are currently known to `lnd`. If it's not confirmed yet, it has `num_confirmations` of 0.

**Comment by Jorikua** [comment]
Got it, will look at it more precisely. Thanks again)

**Comment by hsjoberg** [comment]
Well, if you are using neutrino, unconfirmed transactions won't get recognized as neutrino has no mempool and nodes not listen to the tx P2P gossip.

**Comment by Jorikua** [comment]
@hsjoberg is there another way to do it?

**Comment by hsjoberg** [comment]
@kaganovych no, not that I'm aware of.
Third party services could possibly be used, but this defeats the purpose of Neutrino, which is privacy.
