### ISSUE TITLE
Question regarding channel fees

### ISSUE THREAD

**Issue by jaxkeiser** [lightningnetwork/lnd#5978]
How can I find out what I should set `--base_fee_msat` and `--fee_rate` to for an individual channel in order to be competitive?

**Comment by guggero** [comment]
Please don't spam the issues section with double posts. I suspect nobody answered in the discussions sections because it's too much of an open question. It's like asking the manufacturer of an oven how much you should sell your bread for. The answer will likely be: "It depends."

I suggest you try out our [Slack](https://lightning.engineering/slack.html) channel, where people might be more inclined to answer open questions.
