### ISSUE TITLE
Need help adjusting channel fees

### ISSUE THREAD

**Issue by jaxkeiser** [lightningnetwork/lnd#6011]
`lncli updatechanpolicy --base_fee_msat 750 --fee_rate 0.000001 --time_lock_delta 40 max_accepted_htlcs=30 580a1d6966ecd9a192a287dbcb3abe0268ba4d5c2b77d7e4417d6bf4f2d0b9db:1`

returns 

`[lncli] unable to parse chan point: expecting chan_point to be in format of: txid:index`

How do I format it correctly?

**Comment by yyforyongyu** [comment]
I don't think `updatechanpolicy` takes `max_accepted_htlcs=30`.
Please refer to [this doc on sample usage of `lncli updatechanpolicy`](https://docs.lightning.engineering/lightning-network-tools/lnd/channel-fees#update-channel-policies).

Closed since it's not a software issue, feel free to use Discussions if you have more questions.
