### ISSUE TITLE
Can't mutual close with pending HTLC

### ISSUE THREAD

**Issue by thomash-acinq** [lightningnetwork/lnd#6039]
### Background

When trying to close a channel with a lnd node, the node returned the error `cannot co-op close channel w/ active htlcs`

### Steps to reproduce

Open a channel to a lnd node, add a HTLC , send a shutdown message.

### Expected behaviour

The node should wait for the HTLC to be resolved, not add any new HTLC, and then reply with a shutdown message.
[BOLT 2: Channel Close](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#channel-close)

### Actual behaviour

The lnd node returns an error: `cannot co-op close channel w/ active htlcs`

**Comment by Crypt-iQ** [comment]
We're aware and plan to fix this in the future

**Comment by Roasbeef** [comment]
Related issue: https://github.com/lightningnetwork/lnd/issues/4819

**Comment by Roasbeef** [comment]
On the API level we return this error so the user gets quick feedback that a co-op close isn't possible at that time. On the p2p level, we currently use the same codepath, but should instead defer and wait till things clear up (or the channel force closes?).

**Comment by Crypt-iQ** [comment]
This is one area of the spec I had trouble with. I think the spec could use better wording here also.

**Comment by saubyk** [comment]
prioed 17

**Comment by ziggie1984** [comment]
I like this potential feature and would like to implement it, is it up for grabs ?

**Comment by Crypt-iQ** [comment]
No this is not up for grabs

**Comment by ProofOfKeags** [comment]
Ok. I think I have a decent handle on what's going on here. The issue is that when we receive the `shutdown` message, we attempt a link shutdown which errors if the channel state is "unclean" (has HTLCs), and then rather than handling that error differently and put the channel into a flushing state, we just propagate that error all the way up the call stack. As far as I can tell, there isn't a proper update flushing state in the codebase as is, so I believe I will have to add this.

I believe the appropriate thing to do here is to make it a property of the channel link. If we do that then we can handle the shutdown message in a way that puts the link into this flushing state, and we can similarly handle it from the gRPC interface as well.

**Comment by Roasbeef** [comment]
@ProofOfKeags yep, we've done that here in this PR: https://github.com/lightningnetwork/lnd/pull/6760. We ultimately decided the implementation was more invasive than ideal, to instead go with a simplified approach.
