### ISSUE TITLE
option_channel_type was negotiated but channel_type is missing

### ISSUE THREAD

**Issue by joostjager** [lightningnetwork/lnd#6067]
### Background

Cannot open a channel to Eclair

### Your environment

* lnd v0.14.1-beta
* eclair https://github.com/ACINQ/eclair/pull/2063

### Steps to reproduce

* Connect Eclair to LND
* LND initiates channel open via `lncli openchannel`

### Expected behaviour

Channel opened.

### Actual behaviour

Error: `option_channel_type was negotiated but channel_type is missing`

### Investigation

It seems that lnd is silently not sending the channel type tlv when `OpenChannelRequest.CommitmentType` isn't set. The `lncli` default is to not set the channel type.

https://github.com/lightningnetwork/lnd/blob/c75c3bd847afa86030697960990b4aaa88256efc/rpcserver.go#L1995

**Comment by joostjager** [comment]
Yes

**Comment by Roasbeef** [comment]
Seems they've changed behavior (in master?) since their last release. 

> It seems that lnd is silently not sending the channel type tlv when OpenChannelRequest.CommitmentType isn't set.

Thing is, we don't necessarily know if the other side actually supports the feature when a _user_ goes to open a channel type. So we opt to not use explicit funding if the user doesn't select a type manually. 

As the spec is written right now, it's technically ok for them to always require it (the "MAY" wording), but there're still some other ambiguous cases, like: we don't set it, but they do (in accept_channel) now we both go to implicit. So it's up to an implementation today if they always want it or not.

**Comment by Roasbeef** [comment]
Ok, cleared things up here with some of the other BOLT-ers, we can both ensure that users don't get downgraded, but also maintain compat across all levels. We'll soon have some CI up to run cdecker's old cross-impl tests to make sure this gets caught during the rc process (ideally we only target the last major release, since the master branch can at times be a moving target).
