### ISSUE TITLE
REST error response shape changed unexpectedly in 0.14.1

### ISSUE THREAD

**Issue by wbobeirne** [lightningnetwork/lnd#6095]
### Background

Errors from the REST API changed their shape from
```ts
{
  "error": string;
  "code": number;
  "details": any[];
}
```
to
```ts
{
  "message": string;
  "code": number;
  "details": any[];
}
```
in v0.14.1 as a result of #5473. This has had the unfortunate side-effect of breaking Joule, as it relied on parsing error messages (probably a bad idea tbh, my b) and I can only imagine anyone else parsing or displaying error messages will run into the same thing.

Would there be any interest in rolling back this field name change for a v0.14.2, or was this an intentional rename?

**Comment by guggero** [comment]
Oh, I wasn't aware of this change in the error message structure.
But yes, it was a fully intentional change. We updated the major version of the REST proxy library (from `v1.14.3` to `v2.5.0`).
It's interesting that this change in structure isn't reflected in the generated API docs (`*.swagger.json`).

Can you work around this somehow? Because rolling back isn't really an option, we'd also need to roll this back in loop, pool, faraday and lndclient...

**Comment by wbobeirne** [comment]
> It's interesting that this change in structure isn't reflected in the generated API docs (*.swagger.json).

I'm pretty sure it was here: https://github.com/lightningnetwork/lnd/pull/5473/commits/dd749fe5802039f335779b282f3fb854d1094730#diff-a2c955e5bdb220a40ecc95855004e68ee986113afdf29969cd3e1bc37cfe90a7L227-L232

> Can you work around this somehow?

Yeah it's trivial to work around once you know what's changed, I was just concerned about anything else out there that might break as a result of this.

**Comment by guggero** [comment]
Oh, I see. So the `message` was always there, but now the `error` was removed.
Since the change happened in a major version update and was quite vital to us (allowed us to bump a whole bunch of other library versions that were stuck because of the `grpc-gateway` library) and the change is somewhat documented in the API docs, are you okay with us closing this as "expexpected, possibly breaking change"? We can add it more explicitly to the release notes for `v0.14.0-beta` to make it somewhat more visible.

**Comment by wbobeirne** [comment]
Sure, I just at the very least wanted to get an issue out there so anyone else who maybe runs into this has something to stumble upon 👍
