### ISSUE TITLE
lncli addinvoice adds a route hint even if --private isn't specified

### ISSUE THREAD

**Issue by rkfg** [lightningnetwork/lnd#6099]
### Background

I have the following, slightly unusual channel configuration:

my node - [public channel] - my friend's node
my node - [private channel] - my friend's node
my node - [many more public channels to other nodes]

My friend only has these two channels to my node and nothing else. I opened a private channel because the public one was too small and was often truncated from other nodes' graph so it resulted in "no path found" to him when receiving payments. Now when I do `lncli addinvoice 100000` (for example) I get an invoice with a `route_hints` field that contains that private channel to my friend's node _even though I don't specify `--private` in the command!_ Naturally, if I _do_ add `--private` I get the same invoice structure with this channel as a route hint. I don't know how to remove it because my node already has good connectivity and that channel can't be reached other than through my node anyway. I suppose it's a bug because of some heuristic deciding that if I have a private channel to a node with public channels it has to be added no matter what. I might be wrong of course but I'd like to be able to generate a pure invoice without exposing that private channel and I can't.

### Your environment

* version of `lnd` `0.14.1-beta`
* which operating system (`uname -a` on *Nix) `Raspbian stable arm64`
* version of `btcd`, `bitcoind`, or other backend `bitcoind 22.0`

**Comment by carlaKC** [comment]
The `private` flag is true by default for `lncli`, you can disable adding any route hints by setting `--private=false`. 

Based on your setup, a few relevant points that my be of interest: 
* LND will not add hop hints for a node that is "private" to the network, meaning that it has a private channel with your node, but no other public channels. This is done to ensure that we don't expose the existence of nodes that would otherwise be completely unknown to the network (you can manually create an invoice with route hints to this type of node if you want to). So in this case, we will include your friend's node because they've got a public channel.
* Non-strict forwarding: if your friend is running lnd, payments routed to your node through them will be sent on any channel available + with enough balance, so the private channel might end up being used even if you don't include a hop hint 

Hope this answers your question! Feel free to re-open if anything is unclear :)

**Comment by rkfg** [comment]
Hmm, thanks! I had no idea it's possible to do `--private=false` but it worked indeed. I suggest adding to `addinvoice --help` that it's enabled by default and that it can be turned off like this, most other options have defaults explicitly specified but not this one.
