### ISSUE TITLE
Can't advertise non-standard p2p port with --externalhosts

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#6141]
It doesn't look like there's any way to use the `externalhosts` option while also advertising a port besides 9735. Adding a port to the domain name causes lnd to fail to resolve it (e.g. if I set `externalhosts=[my.domain.com:19735]`). Even if I specify a different port using the `listen` option, lnd will advertise port 9735 after it resolves the IP of the specified domain iname.

**Comment by guggero** [comment]
I just tried this locally and it seems to work for me. I used:

```
--externalip=localhost:9749
--listen=0.0.0.0:9749
--externalhosts=<redacted_domain_name>:19735
```

And the result is:

```
"uris": [
        "03b1bbb36ebb8a2880a469959a9c1d1425dbad2eb3db4672352061fc80804b22f9@127.0.0.1:9749",
        "03b1bbb36ebb8a2880a469959a9c1d1425dbad2eb3db4672352061fc80804b22f9@<redacted_ip_address>:19735"
    ],
```

Not sure if this works because I also use `externalip`?
Or maybe it's just the `[]` brackets you use that are wrong?

**Comment by guggero** [comment]
Or do you see the IP correctly in `lncli getinfo` but the actual _announcement_ is incorrect?

**Comment by guggero** [comment]
Ah okay. Weird that it ever worked with brackets (before adding the port). I guess that's a hidden feature of the address parsing library.
Multiple addresses can be added by specifying the flag (or config option) multiple times. But I guess that's not fully clear from just the command line help description...

I'm closing this since everything seems to be working as expected.
