### ISSUE TITLE
lncli addholdinvoice --> invoice is too large

### ISSUE THREAD

**Issue by AbelLykens** [lightningnetwork/lnd#6225]
### Background

Adding a hold invoice on a node with many private channels (hundreds) leads to invoice is too large

### Your environment

* version of `lnd` 0.14.1-beta
* which operating system (`uname -a` on *Nix) 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend bitcoin-22.0
* any other relevant environment details: I have around 400 private channels

### Steps to reproduce

$ lncli addholdinvoice --amt 100 --memo test1 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
[lncli] rpc error: code = Unknown desc = invoice is too large

### Expected behaviour

Get a hold invoice ;)

### Actual behaviour

Get `invoice is too large` notification

![image](https://user-images.githubusercontent.com/47113175/152108740-5208a3c7-b2b3-4d12-b408-3c37c418cd34.png)

**Comment by carlaKC** [comment]
`SelectHopHints` should limit to maximum of 20 hints. Looks like that limit can [underflow](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/addinvoice.go#L407) if you provide >20 hints yourself. That doesn't look like the case in this instance (no hints provided in the example), but something we should fix nonetheless. 

Do you have any `IRPC` logs that show information about hop hints being added when you try create an invoice?

**Comment by AbelLykens** [comment]
hey! The only log I get is:
`lnd[2093]: 2022-02-02 09:26:29.221 [ERR] RPCS: [/invoicesrpc.Invoices/AddHoldInvoice]: invoice is too large`
Do you have a hint on how to enable more logs / the log you want?

**Comment by carlaKC** [comment]
It's possible that there were no `IRPC` logs, because they only trigger on specific cases :( 

I'll try to reproduce and see what I find!

**Comment by carlaKC** [comment]
Attempt at reproduction [here](https://github.com/carlaKC/lnd/tree/6225-invoicetoolarge), no luck with a node with 500 private channels (stops at 20 hints as expected). 

@AbelLykens is this a persistent problem, or did it only happen once? Do you also get the issue trying to add regular (non-hodl) invoices?

**Comment by Crypt-iQ** [comment]
I might be wrong but I don't think an underflow can happen there because there should only be one forcedhint per routehint which is limited to 20 (https://github.com/lightningnetwork/lnd/blob/04bbbea9a7115d8986653ac56e3d5d53443a8573/lnrpc/invoicesrpc/addinvoice.go#L357-L374)

**Comment by Crypt-iQ** [comment]
@carlaKC you were right, your itest was just off - the openchannelandassert needed to have `net.Bob` as the opener so that this line would get skipped (https://github.com/lightningnetwork/lnd/blob/04bbbea9a7115d8986653ac56e3d5d53443a8573/lnrpc/invoicesrpc/addinvoice.go#L655-L657)

Invoice with 60 hints from itest:
`lnbcrt1u1pslcz5dpp5nxkm6ztd3acsq6y8ywtad85rfgc84s2kqs6rcut6mpwxwvct3wwqdqvw3jhxarfdenscqzpgxqyz5vqrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz8yqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz65qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzuuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqrzyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqrpvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqp6vqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzw5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz2uqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqpmyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqrzuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzkuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzqvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzjvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqrq5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz0vqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzsuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqznyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz95qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzxvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqr9yqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzmvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqpu5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzyyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzt5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz4vqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqryvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqza5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz55qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzpuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzdyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqp7yqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzfvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzduqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzpyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqpmuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzh5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzcvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqpl5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzeyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzz5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzeuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzkyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqp7uqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz8uqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzrvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqpcuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqpavqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqznuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzsyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzvvqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzyuqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz2yqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzg5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqpe5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzuyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzlyqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqrr5qqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqzluqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz7vqqqqgqqqqqqqlgqqqqqqgq9qrzjq0cd0tdy08esn8u80zv04pvkql3pzjvjgwpcd0t35uqknrw6qvzf2qqz35qqqqgqqqqqqqlgqqqqqqgq9qsp5nuqrjvc366aq99lyrl24f29pe6gqzkccwughvggh38hj7np92ejq9qyyssq23dny0kju3r2d885quhqvs7ed82qpp43qwmwxy944354qu2hgxz8qk56f9rpu53sf7fuws2yq8hee3ae0eunnq29fh8yhkv0exfap6sp3kdd85`

**Comment by carlaKC** [comment]
Easy fix, just need to add a max hop hints limit [here](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/addinvoice.go#L646).

**Comment by carlaKC** [comment]
> the openchannelandassert needed to have net.Bob as the opener so that this line would get skipped 

Managed to reproduce once I fixed this, thanks!
