### ISSUE TITLE
Significant size of postgresql folder even with no open channels

### ISSUE THREAD

**Issue by asvdf** [lightningnetwork/lnd#6238]
### Background

After starting lnd with postgresql backend, wallet freshly created, no open channels, CPU load spikes to 8 for a long while, and main postgresql folder grows to 900MB and counting. Replica is over 400MB.

```
sudo du -sch /btc/postgresql/
927M    /btc/postgresql/

sudo du -sch /replica/postgresql/
431M    /replica/postgresql/
```
### Your environment

* version of `lnd` __14.2__
* which operating system (`uname -a` on *Nix) __5.10.63-v8+ # 1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 GNU/Linux__
* version of `btcd`, `bitcoind`, or other backend __0.22__
* any other relevant environment details __PostgreSQL 11__

### Steps to reproduce

Install lnd with postesql backend, create a wallet, do not open any channels and have it stay to mainnet and wait enough time.
Observe the increase in size of the database data folder.

### Expected behaviour

All of the above, with expected database folder size up to 50% of `lncli describegraph` output size

### Actual behaviour

Almost up to 1GB of database folder with a bare node

**Comment by hazrulnizam** [comment]
I have a postgres-backed node that has been running on mainnet for 60 days now. The node only ever has one open channel and had performed only a handful of transactions so far, so maybe I can provide my postgres usage as comparison. Not as bad as @asvdf 's node but it is around the 500MB mark, with the most of the size going to the channeldb_kv table.

![lnd postgres usage](https://user-images.githubusercontent.com/47681422/152687322-43621663-8d6d-41c5-b9dc-1e0d7da4344a.PNG)
.

**Comment by joostjager** [comment]
I am not sure if `lncli describegraph` is indicative of the expected postgres db size, because there is more graph data present on disk than what is reported through `describegraph`. Signatures for example aren't exposed on the rpc.

A better comparison would be to take the size of `channel.db` of a fully synced bbolt instance.

My own mainnet postgres instance has a `channeldb_kv` table size of 293 mb.

**Comment by joostjager** [comment]
What you can do is run VACUUM FULL on the database. Although VACUUM FULL is a heavy operation, and shouldn't be necessary unless you really want to reclaim all possible disk space. In my case, it brought the table size down to 71 mb. 

It seems that the table contains unused space because of the heavy updating during the initial graph sync. VACUUM (which runs automatically) makes that space available again for subsequent db operations. Future graph updates can reuse the space. So, according to this theory, your database size should not grow further.

**Comment by asvdf** [comment]
> What you can do is run VACUUM FULL on the database. Although VACUUM FULL is a heavy operation, and shouldn't be necessary unless you really want to reclaim all possible disk space. In my case, it brought the table size down to 71 mb.
> 
> It seems that the table contains unused space because of the heavy updating during the initial graph sync. VACUUM (which runs automatically) makes that space available again for subsequent db operations. Future graph updates can reuse the space. So, according to this theory, your database size should not grow further.

I knew about the difference between `VACUUM;` and `VACUUM FULL;`, I do run a postgres node on a custom signet so I play there as well... on this mainnet node, after the full vacuuming, the postgres folder is 902MB (was 830MB yesterday), so it didn't help much!

**Comment by Roasbeef** [comment]
> so I suppose postgresl's space management is not so good.

Our data schema right now is very naive, it just maps things onto a key-value namespace. As a result, I wager postgres isn't able to properly optimize the on-disk format as it would for a traditional normalized table set. 

Closing this as the disk space can be reclaim after initial sync as shown above, and also our format isn't yet space optimized.
