### ISSUE TITLE
rpc: Add support for v1 segwit outputs in chain notifier

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#6330]
### Background

When using `RegisterConfirmationsNtfn` to listen for a confirmation against an output script, pre-Taproot outputs will result in notifications through the API, but V1 Taproot outputs will be ignored when they should result in notifications as well.

### Your environment

- lnd v0.14.2

### Steps to reproduce

- use the `RegisterConfirmationsNtfn` against a v1 segwit output

### Expected behavior

- a confirmation notification should be sent

### Actual behavior

- no notification is sent

**Comment by Roasbeef** [comment]
I think this should be possible as soon as we update to the latest `btcutil`, which was done in https://github.com/lightningnetwork/lnd/pull/6285. So should be possible in master as is.

**Comment by alexbosworth** [comment]
I tried it today on a v1 output script and it returned `unsupported script type` as an error so maybe it needs #6263 to work

**Comment by guggero** [comment]
Actually, on current `master` you shouldn't get the `unsupported script type`, as that should indeed be fixed by #6285 as mentioned.
But I noticed today (while adding new test cases for the notification RPC to #6263) that `RegisterSpendNtfn` won't fire for any p2tr output, since the comparison only relies on calculating the pkScript from the witness, which is currently not supported anywhere (see https://github.com/lightninglabs/neutrino/pull/234).
So I think we need to update https://github.com/lightningnetwork/lnd/blob/master/chainntnfs/txnotifier.go#L359 or the underlying `txscript.ComputePkScript` to be Taproot compatible.
