### ISSUE TITLE
LND crashing with index out of range

### ISSUE THREAD

**Issue by philipp1992** [lightningnetwork/lnd#6381]
![image](https://user-images.githubusercontent.com/11994884/160675066-13b2128b-392e-4e45-98c0-eda1f877e4bc.png)

can anyone help with this error?

**Comment by Roasbeef** [comment]
Can you fill out the full issue templating including your lnd version and any other related information?

Also AFAICT, some of those log lines aren't in the current or prior versions of lnd, leading me to believe this is actually a fork of lnd with some custom modifications?

**Comment by philipp1992** [comment]
Yeah its a mod but not mine. Could you give me a hint on why it's crashing?

**Comment by Roasbeef** [comment]
AFAICT, you're working with a fork off of version v0.12, which is a few major versions back. This issue tracker is only for mainline lnd, as we have no idea what other modifications you've made in your fork. In the past issues like this were discovered to be due to [incorrect data being returned by a node backend](https://github.com/lightningnetwork/lnd/issues/5977#issuecomment-969354323). In that case, a reindex of the user's node resolved the issue. 

If I look at that block on testnet, then that transaction referenced in the log isn't included. 

Closing this as it's an lnd fork using a very old version of lnd. If you find any issues in your fork attempting to support another chain that are relevant to main line lnd, any issues/PRs would be much appreciated.

**Comment by Crypt-iQ** [comment]
The spenderinputindex here (https://github.com/philipp1992/neutrino-lnd/blob/0df3a283120c234de69097db1507fe4d02197d78/chainntnfs/lightwalletnotify/lightwallet.go#L732) is incorrect. It should be using the index of the TxIn spending the output in the current transaction rather than the Prevout's index in the parent transaction

**Comment by philipp1992** [comment]
> The spenderinputindex here (https://github.com/philipp1992/neutrino-lnd/blob/0df3a283120c234de69097db1507fe4d02197d78/chainntnfs/lightwalletnotify/lightwallet.go#L732) is incorrect. It should be using the index of the TxIn spending the output in the current transaction rather than the Prevout's index in the parent transaction

do you know what changes i have to make to fix this? thanks a lot
