### ISSUE TITLE
Recovering bitcoin from missing channel

### ISSUE THREAD

**Issue by minecraft2048** [lightningnetwork/lnd#664]
Lets say that I have several channels open filled with several mBTC in it, and then Murphy's law strikes and then the only thing I have now is the backup seed for lnd wallet. How do I recover all those bitcoins from those opened channels?

**Comment by dabura667** [comment]
Hmmm, maybe lncli could offer a “export encrypted channel.db” that encrypts the current channel.db using a key derived from master private key, and then “import encrypted channel.db” that will attempt to decrypt, and merge any channels info with priority given to currently open channel.db.

Then I can (ie) link it up with dropbox or gdrive or mega or whatever I want, and the info is all encrypted gunk to anyone but the lnd client holding the private key used to encrypt.

**Comment by brtknr** [comment]
perhaps a backup location should be mandatory in the setting up process so that encrypted keys are dumped every time a transaction takes place. would be a hassle to export them every time.

**Comment by stridentbean** [comment]
Not sure if this helps, but my current solution to this is to create a script that stores a backup of the code, channel.bd, and wallet.db. 

1. Stop LND
2. Backup code
3. Backup channel.db and wallet.db
4. Restart LND

Matching the backed up data and code has always worked for me. You have to back up that code also because at this time code changes can be breaking changes :/. I do this backup before every attempt to update the code.

**Comment by Roasbeef** [comment]
See #1364 and #175.
