### ISSUE TITLE
Lnd not reconnect with peers after restart.

### ISSUE THREAD

**Issue by gamer90** [lightningnetwork/lnd#667]
If lnd is restarted after successful connection to peer and opening channel, channel become inactive and connecting to channel peer become pending.

`unable to send AnnounceSignatures message to peer(02fea3f091dad9eeb5facebaeda301fbdd18b3d33187a019327d80201d451ace1e): unable to find peer. Will retry when online.`

Manual connection from lncli to channel node_pub returns error:

`error connecting to peer: connection attempt to 02fea3f091dad9eeb5facebaeda301fbdd18b3d33187a019327d80201d451ace1e@192.168.0.100:9735 is pending`

**Comment by Roasbeef** [comment]
`lnd` _will_ reconnect to all peers after a restart. The first message is just due to the fact that we may not have established any connections at the time it attempts to retransmit that message. You get that second error as it's actively trying to connect to the target node. If the peer isn't actually listening, or has changed pubkeys, then you won't be able to connect to them. Peers on testnet atm frequently change out public keys as there's no real money at stake.
