### ISSUE TITLE
routing+htlcswitch: add support for selecting, and encoding+decoding blinded paths 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#6690]
This is a master tracking issue that tracks the prototyping/implementation of blinded paths: https://github.com/lightning/bolts/pull/765. 

Blinded paths re-uses a few of the Sphinx tricks to allow a receiver to give a sender an obfuscated path that hides the set of nodes traversed (subject to leakage via the routing policies) to the sender. We have code lying around some where that already implements all the blinding/encrypting bits. What's missing, and what will be the long tail to deployment (imo) is: figuring out exactly _which_ paths to place in the blinded payload. Selecting these paths poorly may make a receiver hard to pay. On top of that, the paths selected decay over time, as routing policy changes may cause routes to no longer be used (fee is now 4x, etc). 

Related to the question of which paths to select is: how many of them to stuff into the invoice. Unlike the normal last-hop hop hints usage in the invoice, these paths may _extend into the public graph_. As a result, there's more possibilities w.r.t which hops/nodes to include in a payload. As a result, when encoding for a BOLT 11 QR code, there's a sort of satisficement/optimization problem at hand. On the other hand, if something like LN-URL or BOLT 12 are used, then you're fetching these invoices over HTTP (or w/e) so you don't need to be as concerned w/ the side of the payload.

**Comment by ellemouton** [comment]
linking here so that it doesn't get lost: PR for creating blinded path, decrypting encrypted data from blinded path & processing an onion as a hop within a blinded path: https://github.com/lightningnetwork/lightning-onion/pull/57

**Comment by ellemouton** [comment]
About to start opening some PRs so gonna give an outline here of what they will include & what is still missing:

## PR 1

### Overview: 
This PR will include all the prep work for blinded path receives. By the end of the PR, a user will be able to:
1) create an invoice and specify that it include a blinded path. 
2) pay to an invoice with a blinded path

### More in depth description:
1) All the set-up work for being able to create the final hop encrypted payload in a blinded path (ie, the data that the recipient basically sends to itself. This will, for example, include the `PathID` which will basically act as the payment address. We also include the `Padding` field so that we can ensure that all encrypted payloads are of equal size.
2) Add the new Bolt11 blinded path type along with encoding/decoding logic
3) Ability to find any candidate blinded paths to self given min/max num hop params
4) Use mission control to determine which of these paths are best. 
5) Construct the full blinded path to self and add to a Bolt11 invoice
6) Changes necessary to send an MP payment to a _single_ blinded path. 

## PR 2

This PR will cover being able to send shards of an MP payment through _multiple_ paths. This will require quite a bit of refactoring which is why it gets its own PR.

## PR 3

In PR 1, we start querying MC to choose the best paths _towards_ us but realistically, MC wont have much (if any) data about links in this direction (all of its data currently comes from sending _out_). 
If we use a blinded path to receive, however, we will start gaining some info about success pairs in the _correct_ directions. So this PR will cover tracking this & updating MC accordingly.

**Comment by ziggie1984** [comment]
> In PR 1, we start querying MC to choose the best paths towards us but realistically, MC wont have much (if any) data about links in this direction (all of its data currently comes from sending out).

But don't rebalances of the node also track the direction to us ? So I think we already have MC data pointing into our direction through all the rebalances routing nodes make ?

**Comment by ellemouton** [comment]
> But don't rebalances of the node also track the direction to us ? So I think we already have MC data pointing into our direction through all the rebalances routing nodes make ?

Good point! that will certainly help too 🎉

**Comment by saubyk** [comment]
> But don't rebalances of the node also track the direction to us ? So I think we already have MC data pointing into our direction through all the rebalances routing nodes make ?

The only point I would add here is, even though it covers the scenario of payments being made to the node, the proportion of the nodes on the network actively rebalancing may not be that high. Since a large proportion of the channels on the network are unbalanced i.e. bi-modal liquidity distribution.

**Comment by ziggie1984** [comment]
Feature request:

Add a parameter when creating the invoice for blinded paths which limits the overall fee of the route blinding section to a specific value. This would give the invoice creator more control so that the sender is not overpaying heavily.

**Comment by saubyk** [comment]
Closing this as all the relevant prs are merged
