### ISSUE TITLE
channeldb: unable to apply migration #25

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#6841]
Went to upgrade a mega old node and ran into this error:
```
2022-08-18 03:42:39.757 [ERR] LTND: unable to open graph DB: unable to fetch chan info: no chan info found
2022-08-18 03:42:39.756 [INF] CHDB: Unable to apply migration #25
```

AFAICT, it's just failing to fetch the channel information for a channel: https://github.com/lightningnetwork/lnd/blob/v0.15.1-beta.rc1/channeldb/migration25/migration.go#L79-L90

 However the _channel point_ bucket exists, so it's weird that the channel information isn't found. Might be some DB corruption? Or possibly an ancient "strategic continue" showing up years later...

**Comment by yyforyongyu** [comment]
Do you happen to know the channel point? If not could you apply #6755 and run it again?

We've had a user reporting the same issue on slack, and it turned out to be a corrupted channel. The related issues are #1629 and #1633, which created the corrupted channel point.

I suggested using `abandonchannel`, but haven't heard back from the user ever since.

**Comment by Roasbeef** [comment]
So I dug in and the two channel points are from 4 years ago, and have already been fully closed on chain. I was able to modify my migration locally to just continue and print out those channels, and it was able to complete everything.

**Comment by Roasbeef** [comment]
I ended up applying a local patch which was pretty much #6755 as well.

**Comment by Roasbeef** [comment]
Closing this since I was able to recover, and these were likely old dangling channels 4+ years old fixed by more recent changes.
