### ISSUE TITLE
[feature]: allow configuring sweeper fee rates by output type

### ISSUE THREAD

**Issue by antonilol** [lightningnetwork/lnd#7026]
**Is your feature request related to a problem? Please describe.**

When a channel is force closed, some outputs have no priority to be swept, like the balance outputs, for others, like HTLCs, priority can vary, from HTLCs expiring in the next few block or a 1000 block timelocked one from a long route payment

**Describe the solution you'd like**

more sweeper config (lnd.conf) to configure fees by output type, that can be set to a static fee rate like 1 sat/vB, or a block target (i want it to be confirmed in n blocks)
for htlcs something like "i want it confirmed at least n blocks before/after its expiry" would do
(before/after depends on htlc expiry or settlement)

**Describe alternatives you've considered**

**Additional context**

**Comment by ziggie1984** [comment]
Hey all would want to work on this, will present some thoughts how I want to structure this in the coming days. I am mostly thinking of first adding some adjustable feerates for sweeps which are not time sensitive (examples you mentioned above, maybe adding some maxcaps the noderunner can adjust) and later also proceed to control the feerate of timesensible sweeps.

**Comment by ziggie1984** [comment]
My first approach would split the settings like the following:

It seems to me that Anchor Channels are completely handled in the `sweeper` package whereas there is still some logic to sweep Commitment Txouts in the `utxonursery` package. Have to get familiar with the differences of both.

1. The Commitment Resolver which sweeps the CSV delayed output to us when we initiate the force_close (`to_local`)

This sweep is not timesensitive at all so I would allow the node-runner to sweep it with a predefined feerate (blocks/kweight/satpervbyte) currently 6 confirmations.

`CommitmentResolveFee(sat_per_vbyte)`
`CommitmentResolveFee(sat_per_kweight)`
`CommitmentResolveFee(confirmations)`

2. (AnchorChannels only) Introduce a capping for the CPFP Transaction using the Anchor to bump the fee of the Commitment Transaction

This Feerate is time sensitive  when we having HTLC outputs in the Commitment which are critical for use to confirm. These are Outgoing HTLCs and also Incoming HTLCs we know the preimage of.

I would also allow this feerate to be customized by the user because depending on the cltv timelock delta of a node, this might also not be as timecritical as it seems at first glance (this thinking could even expand where we even don't go onchain to resolve if we still have enough delta left, currently we immediately go to chain if the transaction is `broadcastable` but this is not topic of this PR and should be handled in a separate one).

`CPFPAnchorCommitmentFee(sat_per_vbyte)`
`CPFPAnchorCommitmentFee(sat_per_kweight)`
`CPFPAnchorCommitmentFee(confirmations)`


3. Incoming HTLCs | Outgoing HTLCs (First-Level-Sweep) (Anchors-Only) | For non-anchor channels the feerate of the Commitment Tx is used - not sure if we wanna make fees for non-anchorchannels customizable.

We could even go further and allow non-anchor channels when the peer closes and we can sweep the CLTV timeout branch or the the preimage branch (when we know the preimage)?

These are time sensitive but also depending on the timelock delta not as much.  But they are more timesenstive as the second-levell sweep of the HTLC which is CSV-Locked so it makes sense to introduce a separate config setting.

`FirstLevelHTLCResolveFee(sat_per_vbyte)`
`FirstLevelHTLCResolveFee(sat_per_kweight)`
`FirstLevelHTLCResolveFee(confirmations)`

3. Incoming|Outgoing HTLCs (Second-Level-Sweep) (Anchors + other channeltypes)

This sweep is not time-senstive but can be convenient to have at hand when opening new channels. So a separate parameter makes sense. This applies to all channeltypes. Current default 6 blocks.

`SecondLevelHTLCResolveFee(sat_per_vbyte)`
`SecondLevelHTLCResolveFee(sat_per_kweight)`
`SecondLevelHTLCResolveFee(confirmations)`


This was just my first impression when thinking about the sweeper fee structure. 

Open for discussions before beginning to implement my idea.

**Comment by ziggie1984** [comment]
My first approach will be ready this week an only will give the user the ability to specify sat_per_kweight for now.
