### ISSUE TITLE
[feature]: API improvement to close a channel

### ISSUE THREAD

**Issue by gcool-info** [lightningnetwork/lnd#7075]
**Is your feature request related to a problem? Please describe.**
Imagine the following function to close a channel:

```golang
func closeChannelFromAliceToBob(ch *lnrpc.Channel) error {
  chPoint := ch.ChannelPoint
  fundingTxid := lnrpc.ChannelPoint_FundingTxidStr{
    FundingTxidStr: strings.Split(chPoint, ":")[0],
  }

  outputIndexStr := strings.Split(chPoint, ":")[1]
  outputIndex, err := strconv.Atoi(outputIndexStr)
  if err != nil {
    return err
  }

  _, err = alice.CloseChannel(context.Background(), &lnrpc.CloseChannelRequest{
    TargetConf: 1,
    ChannelPoint: &lnrpc.ChannelPoint{
      FundingTxid: &fundingTxid,
      OutputIndex: uint32(outputIndex),
    },
  })
  
  return err
}
```

The need to do string manipulation to extract `FundingTxid` and `OutputIndex` is a bit verbose. I would've expected this to be done more easily through the API.

**Describe the solution you'd like**
`lnrpc.Channel` could have a method to get the fields `FundingTxid` and `OutputIndex`.

**Describe alternatives you've considered**
NA

**Additional context**
I've assumed that this is the best way to get `FundingTxid` & `OutputIndex`  to close the channel. If there's a better way, please let me know :)

**Comment by guggero** [comment]
If you look at https://github.com/lightningnetwork/lnd/blob/master/lnrpc/lightning.proto#L1940, you see that `CloseChannelRequest` also takes a `lnrpc.ChannelPoint`. So you should be able to use `ch.ChannelPoint` directly.

**Comment by gcool-info** [comment]
Thanks! However, 
- `ch.ChannelPoint` is a `string` ([ref](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/lightning.pb.go#L4368)) 
- `CloseChannelRequest.ChannelPoint` is a `*ChannelPoint` ([ref](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/lightning.pb.go#L6416))

So you would still need to convert a `string` somehow to a `*ChannelPoint`.

**Comment by guggero** [comment]
Ah, right, forgot about that part. Unfortunately the use of channel points is very different across all the RPCs, as things grew historically and were worked on by different people. We have a couple of those "convert from format X to Y" helper functions ourselves as well.

**Comment by gcool-info** [comment]
Yeah, no worries, I understand how these things happen! :) 

Do you want me to keep this issue open or to close it? I guess it depends on whether you think it's a problem that should be improved at some point.

**Comment by guggero** [comment]
I don't think there's an easy way to improve the API without making things more complicated or confusing for the user.
As far as I can see there are two options:
 - Add the composite channel point to `ListChannels`: Now it's easy to use for developers but users see duplicate information in the CLI (with a confusing hex-reversed transaction ID in `ChannelPoint_FundingTxidBytes`).
 - Add the string based channel point to `CloseChannel`: Now there are two ways to specify a channel point. Which one should a dev use? What's the difference? We can't replace the old one without breaking older clients.

Unfortunately your proposal to add a method to `lnrpc.Channel` is not possible, because that code is auto-generated by the gRPC code generators.
But maybe all you need is a `ParseChannelPoint` helper function?

**Comment by gcool-info** [comment]
> Unfortunately your proposal to add a method to lnrpc.Channel is not possible, because that code is auto-generated by the gRPC code generators.

Yeah, I was afraid of that... :P 

> But maybe all you need is a ParseChannelPoint helper function?
👍
