### ISSUE TITLE
[feature]: allow feature bits to be sent using peersrpc.UpdateNodeAnnouncement

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#7094]
**Is your feature request related to a problem? Please describe.**

Today it's possible to create all sorts of meta/overlay protocols that hook into lnd using the various interceptors we have. However, none of these are able to currently advertise feature bits or custom TLVs in the node announcement message. 

**Describe the solution you'd like**

Extend the new [UpdateNodeAnnouncement](https://api.lightning.community/#updatenodeannouncement) RPC call to allow feature bits to be set. 

Only feature bits that `lnd` doesn't know about and/or isn't setting should be allowed. Otherwise it would be possible for a user to create a node ann that would actually be rejected by other peers due to things like violating dependnacy constraints.

The resposnse should tell the caller if their feature bits were able to be set or not, and the final set of feature bits that are now advertised. 

With another small change, we can also enable custom TLV ranges to be set as well. 

**Describe alternatives you've considered**

Only allow it in the config, but that wouldn't be that flexible.

**Comment by joostjager** [comment]
You probably want to also allow in config?

**Comment by carlaKC** [comment]
This is actually mostly addressed in #5587, I'm going to put up a PR to allow setting feature bit values in config because I think that's useful for more "permanent" use cases. 

> Only feature bits that lnd doesn't know about and/or isn't setting should be allowed. 

Do we want to update the API to add this restriction? As I read the [current update code](https://github.com/lightningnetwork/lnd/blob/2fd900b172f4acc2934215591d86532db78d207e/lnrpc/peersrpc/peers_server.go#L247), we're allowed to set/unset features that are known to LND (provided dependencies remain valid). This would be a breaking change for the API, but I think it's _pretty_ unlikely that people are using to to mess with defined protocol features?

**Comment by SeverinAlexB** [comment]
Hi guys!
The LSPSpec group is working on a spec for channel purchase and Just-In-Time channels for wallets. This will be built on LNDs `SendCustomMessage` and thus should not require any of your developers time.

The spec will define a [node announcement feature bit](https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/23/files#diff-56ee25af4ddef6121a47e8c91b93abe49f091a82a73c149cbc1c32dc2c599d54R257) though. Is there any timeline for the extension of `UpdateNodeAnnouncement`? We at Synonym are using LND in our [Blocktank](https://blocktank.to) product and the LSPSpec requires this feature bit.

Best regards
Sev

**Comment by ZmnSCPxj-jr** [comment]
To interject, the LSPS0 proposal also requires an `init` feature bit as well, not just `node_announcement`.
