### ISSUE TITLE
[bug]: unable to forward, wrong "insufficient bandwidth"

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lnd#7108]
### Background

I have more than enough liquidity in one of my channels and should be able to serve outgoing forward requests. However, this doesn't work. Instead, lnd reports "insufficient bandwidth". Details below.

### Your environment

* lnd v0.15.4-beta
* Linux server 5.10.0-13-amd64 #<i></i>1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
* bitcoind v23

### Steps to reproduce

Get forwarding request out via channel X.

### Expected behaviour

Forwarding request is served, fees are earned, local balance is reduced.

### Actual behaviour

"insufficient bandwidth to route htlc: x is larger than y" (canSendHtlc in link.go)

First observed failure:
* Date: 2022-10-25 18:31:17
* Requested amount: 188,242,405 msat
* Available (according to lnd): 3,005,999 msat

Balance at 2022-10-25 18:29:25+02:
* local: 9,897,025 sat
* local reserve: 100,000 sat
* remote: 100,078 sat
* remote reserve: 100,000 sat

Most recent failure:
* Date: 2022-11-03 13:18:31
* Requested amount: 50,024,602 msat
* Available (according to lnd): 2,843,999 msat

Balance at 2022-11-03 13:14:47+01:
* local: 9,896,568 sat
* local reserve: 100,000 sat
* remote: 100,712 sat
* remote reserve: 100,000 sat

`lncli listchannels`:

```
{
            "active": true,
            "remote_pubkey": "03627ebe50fc6eb80b0caab0c3714958c701eda735e3c29588e83150d6d4a93976",
            "channel_point": "db8a9a4d483e0fd0c84e5a004d51dd51ecbb113329729c18db6a5112bab61a4f:0",
            "chan_id": "834535922707529728",
            "capacity": "10000000",
            "local_balance": "9891564",
            "remote_balance": "108241",
            "commit_fee": "195",
            "commit_weight": "724",
            "fee_per_kw": "269",
            "unsettled_balance": "0",
            "total_satoshis_sent": "2036708",
            "total_satoshis_received": "11928272",
            "num_updates": "9950",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false,
            "initiator": false,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "100000",
            "remote_chan_reserve_sat": "100000",
            "static_remote_key": true,
            "commitment_type": "STATIC_REMOTE_KEY",
            "lifetime": "174093",
            "uptime": "174093",
            "close_address": "",
            "push_amount_sat": "0",
            "thaw_height": 0,
            "local_constraints": {
                "csv_delay": 144,
                "chan_reserve_sat": "100000",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "18446744073709551615",
                "min_htlc_msat": "0",
                "max_accepted_htlcs": 30
            },
            "remote_constraints": {
                "csv_delay": 1201,
                "chan_reserve_sat": "100000",
                "dust_limit_sat": "546",
                "max_pending_amt_msat": "9900000000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "alias_scids": [
            ],
            "zero_conf": false,
            "zero_conf_confirmed_scid": "0"
        }
```

`lncli getchaninfo`:
```
{
    "channel_id": "834535922707529728",
    "chan_point": "db8a9a4d483e0fd0c84e5a004d51dd51ecbb113329729c18db6a5112bab61a4f:0",
    "last_update": 1667403066,
    "node1_pub": "027ce055380348d7812d2ae7745701c9f93e70c1adeb2657f053f91df4f2843c71",
    "node2_pub": "03627ebe50fc6eb80b0caab0c3714958c701eda735e3c29588e83150d6d4a93976",
    "capacity": "10000000",
    "node1_policy": {
        "time_lock_delta": 99,
        "min_htlc": "1",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "1",
        "disabled": false,
        "max_htlc_msat": "10000000000",
        "last_update": 1667403066
    },
    "node2_policy": {
        "time_lock_delta": 34,
        "min_htlc": "1",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "135",
        "disabled": false,
        "max_htlc_msat": "104096134",
        "last_update": 1667143395
    }
}
```

**Comment by C-Otto** [comment]
The available local balance, as parsed from lnd's log messages:
```
 count |  available   
-------+--------------
     1 |        2,604
     1 |        2,608
     1 |        2,702
     1 |        2,703
     1 |        2,704
     1 |        2,706
     4 |        2,707
     1 |        2,844
     2 |        2,977
     1 |        2,981
     2 |        2,992
     1 |        2,994
     2 |        2,995
     1 |        2,996
    69 |        3,006
(15 rows)
```

**Comment by C-Otto** [comment]
Note that I was able to forward 200,104 sat after the first failure (a few days later, 2022-10-29 10:54:17+02). As far as I can tell, the channel didn't move any sats between the first error and this outgoing forward.

**Comment by positiveblue** [comment]
@C-Otto I guess not but is there is any htlc in flight blocking the channel liquidity?

**Comment by C-Otto** [comment]
Note that all "available local balance" values end with 999msat, so I guess it's this code:
https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L7034

**Comment by Roasbeef** [comment]
FWIW, that's a static key channel (legacy), so any HTLC needs to be able to pay fees for itself at the given fee rate, this can cause you to be unable to send even though it looks like you can. 

Anchor channels allow the second level HTLC to be zero fees, so you don't need to commit as much since you just care about the impact of the output and not also the second level transaction itself.

**Comment by Roasbeef** [comment]
> Yes, the remote party has a very low balance, especially considering the reserve. However, I don't understand why this stops me from sending funds to their side, i.e. creating a more balanced channel. It feels like the channel drove itself into a dead end?

So the initiator pays fees for a commitment transaction the entire time. They need to have enough fees to pay for a force close assigned, and also they pay all the fees for a co-op close. 

Each time you add an HTLC, they need to have enough funds to pay for that HTLC (it increases the size of the commitment transaction). This is the case even if they aren't the one adding an HTLC. In the case above, the initiator only has 100,078 sats on their side. The reserve itself is just 78 sats below that at 100k. As as a result, the channel can't be utilized unless the fee rate (for the commitment) transaction is reduced to the point that it can support another HTLC, then things can be rebalanced somewhat. 

The relationship between the fees paid, HTLC weight and the reserve _mostly_ works on the spec level. However, there're some degenerate cases when a channel isn't able to be used due to the initiator not being able to pay fees. I think what happened is that they tried to send everything out of the channel, realized the reserve was there, then played around to send the most they could out, leaving that amount.

**Comment by Roasbeef** [comment]
We added that logic to fix issues like this: https://github.com/lightningnetwork/lnd/issues/3787. In this case, the router would keep trying to send across that link, but it can't support it due to fees. Now we'll just ignore that and try another link. There were also prior cases of things like the reserve being violated, an output taking too many fees and becoming unspendable ("negative" balance).

**Comment by U-got-IT** [comment]
If I may chime in. I am running the node on the other side and initiated the channel a few weeks ago. 
I am running Core Lightning 0.12.1, not LND. When opening the channel I used default values for everything and didn't do anything manually ever since other than automatic fee adjustment depending on imbalance via a plugin. Over time all the liquidity shifted over to C-Otto's side through normal, unattended routing activity. If this can lead to the situation at hand this seems to be a rather severe incompatibility. Please correct me if I'm wrong.

**Comment by C-Otto** [comment]
Thanks a lot for the explanation. I think the discussion in https://github.com/lightning/bolts/issues/728 is really helpful, and @Roasbeef's comment above puts this into the context of lnd's code. Personally, I think that this issue could be closed (see below), as it's a weird edge case without an obvious solution.

The only two things missing:
* Why can I send out payments myself, if routing is forbidden? I'm using SendToRoute where the first hop (the problematic one to @U-got-IT) is fixed. I just sent out 10,000sat, which worked out just fine. Yesterday it worked with 50,000sat.
* I'll add an INFO log message to describe this edge case, so that future me doesn't need to raise yet another issue.

@U-got-IT please switch to anchor channels, if possible. If not, please campaign for it to be supported.

**Comment by C-Otto** [comment]
I now have the same issue with another peer. This time, it's an anchor channel, though!

**Comment by Roasbeef** [comment]
> I just sent out 10,000sat, which worked out just fine. Yesterday it worked with 50,000sat. I'd be happy to raise a follow-up issue.

Your ability to send is a function of the fee rate on the commitment transaction, which is controlled by the initiator. If the fees are low, you might be able to send, otherwise you might not be able to. I think the scenario laid about abov ei spretty clear, and also the work around as well (trickle payments to unstuck the channel).

**Comment by C-Otto** [comment]
Isn't that fee rate the same for forwarded transactions? I don't see why forwards are blocked, while payments initiated by me are OK.

**Comment by Roasbeef** [comment]
Were the forwards and the initiated payment of the same amount? 

Re the fee rate I mean if they were done at different times, then the applied fee rate would differ. 

On the code level, both forwards and local adds go through pretty much the same code pathway: https://github.com/lightningnetwork/lnd/blob/f6ae63fd7b53e366f50a96216fb056dd8fb8f4a7/htlcswitch/switch.go#L538-L558

Which ends up calling `AvailableBandwidth`, which'll reject conditionally based on the rules mentioned above.

**Comment by C-Otto** [comment]
The forwards had larger amounts, my initiated payments (rebalances) had 5k or 10k sat. 

I just did a test just two minutes after an observed failure:
Failure at 01:53:17 (requested 17k sat).
At 01:55: Remote balance 53sat + reserve. Successfully sent payment (5k sat).

I don't think network conditions changed a lot in this timeframe (although one new block got mined in between). I'll try to do another test with less delay (no new block), and using a similar/higher amount.

FYI, here's a list of remote-initiated channels that have less than 500sat on the remote side (updated every 30min): https://c-otto.de/lnd/low-remote.txt

**Comment by fotongit** [comment]
Hello, foton node here. I am having the same behavior described here on v0.15.4, I noticed it with one node (Mushi) but reviewing in detail this is happening with some others. I get HTLC errors with Insufficient Balance but liquidity is on my side. Weird is I get this messages (I received in the last 24h, 55 HTLC errors to Mushi) but I had 8 successful transactions as well with this node.

All the problematic channels have all the liquidity on my side.

Best,

**Comment by nayuta-ueno** [comment]
I have same issue.
HTLC manager is logging bandwidth when LND starts up, and it suddenly becomes a small value.

```
[INF] HSWC: ChannelLink(0be39eb940989bf68726d08e57adc1b80124b4df6691db9494df691e1a718c95:0): HTLC manager started, bandwidth=353999 mSAT
```

It has occurred several times, usually at "353999 mSAT".

**Comment by C-Otto** [comment]
Superseeded by #7721.

**Comment by dskvr** [comment]
~10% of my channels are presently unusable by this bug, or in other terms 60% of my local liquidity (outgoing) is frozen and cannot be rebalanced, forwarded or sent.
