### ISSUE TITLE
[feature]: Signing/Verify Messages with a  single addresses of the lnd wallet

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#7202]
**Is your feature request related to a problem? Please describe.**
Signing messages with a address related privkey is sometimes necessary to "Stack Sats" directly to the lightning node. 

**Describe the solution you'd like**
This request should act as a placeholder because I am currently working on it.

**Comment by massmux** [comment]
This feature would be really great, in order to get sats directly to a lightning node, for any situation in which the message signature is needed!

**Comment by ziggie1984** [comment]
will also include `verifymessagewithaddress`

**Comment by ziggie1984** [comment]
So was wrapping my head around this feature request and want to make sure we actually want this feature in lnd.

**Background:**
Currently LND has the ability to sign a message with the node's private key, which uses zbase32 encoding and is used for example in Thunderhub to login to their service. It might be useful to also integrate message signing with a specific address and in addition also provide signature verification with regards to a specific message. A use-case I encountered was the signing of a message with the private key of the address to acquire sats from services which allow you to buy bitcoin without a full kyc process ([pocket-bitcoin.com](http://www.pocket-bitcoin.com/)). In addition signing messages with lnd-owned addresses could have potential other use-cases where it is necessary to proof that the address is in control of the node-runner.

Signing a message with a bitcoin address seems not to be standardized in the bitcoin-ecosystem, though many applications including electrum, bitcoin-core and btcd seem to adhere to a standard. This quasi-standard uses base64 as signature encoding (compact signatures with pubkey recoverable) and the double-hash for the message digest. Therefore I propose to follow the same standard for lnd if we want to integrate it.

Bitcoin-core/btcd only allows signing with legacy addresses, however this function should allow signing messages with all supported address types of lnd (P2WKH, NP2WKH, P2TR)

**Current Direction**

signing and verifying a signature comes hand in hand so I propose adding these two functionalities in the same PR.

The idea was to pack these two commands `signmessagewithaddr` and `verifymessagewithaddr` into the walletrpc package. 
Regarding lncli I would group those two commands as followed:

```
lncli wallet addresses signmessagewithaddr
lncli wallet addresses verifymessagewithaddr

``` 

- Detailed description for `signmessagewithaddr`:
The functionality for this function is straight forward: You input a message and an address you want to use for signing and the base64 signature is returned. The lnd wallet should hold the privkeys for this address otherwise signing will fail.


- Detailed description for `verifymessagewithaddr`:
This function is a bit more complicated depending on how  much functionality we want to integrate. It should not only verify if the signature is valid but should have a strict requirement that the signature corresponds to the provided address. We could either restrict the verification to owned addresses but I would also like to have the ability to verify any message signed with any address, so that I can perform verification for signatures I am not in control of (which might come handy some time)
So this function would first check if the address is owned by the node then verification is straight forward. 
If the address is not controlled by us it should try to find the address by using the recovered pubkey of the signature and compare the resulting address types with the address provided. Allowed message types could range from address types (raw pubkey, legacy addresses, P2PKH, P2WPKH, NP2WPKH).

I would appreciate any feedback before continuing my work on it.

**Comment by Bitcoinite** [comment]
This sounds like a good idea that could solve some real world use cases.

**Comment by ziggie1984** [comment]
Just to prevent any confusion:
```
lncli signmessage => signs a message with the node key of your lnd node (which is a single key of the root key)
lncli signmessagewithaddr => signs a message with any address you own (generated with lncli newaddress for example)
```

**Comment by guggero** [comment]
I do think these RPCs and commands would be useful. The main concern here is obviously security, since you can build this in an insecure way in which you could trick a user to sign a sighash of a transaction and steal funds.
In Bitcoin Core there are two measures preventing this (or maybe just one measure with two steps):
1. You can only sign a message (pre-image) and not a hash (meaning that whatever you give to the RPC is always double hashed).
2. A prefix is added (see [message.cpp](https://github.com/bitcoin/bitcoin/blob/01e1627e25bc5477c40f51da03c3c31b609a85c9/src/util/message.cpp#L25)) in order to make it an invalid TX signature even if you trick the user into signing the full sighash pre-image.

The second step then poses the question: What should the prefix string be? Should it be the exact same as Bitcoin Core to achieve full compatibility? Should it be something Lightning or LND specific (for example we use `lightning:` as a prefix in the `signmessage` RPC). If we do the Bitcoin Core compatibility we probably also need to make sure we have the correct prefixes for the different networks (regtest, signet, testnet3, mainnet, Litecoin?).

**Comment by ziggie1984** [comment]
Thanks a lot for your feedback:

> You can only sign a message (pre-image) and not a hash (meaning that whatever you give to the RPC is always double hashed).

Could you elaborate how a double hash is better than a single hash, because regarding the signmessage command with the node_id lnd also provides the ability to  single hash the message and sign it ?

Regarding the Prefix of the message, I would favour the approach of having full compatibility with bitcoin-core (thats the main use case I build this command for, stacking with pocket into my lnd wallet and they use bitcoin-core standard afaict). 

Regarding the Prefix, I think including a prefix for the different networks would destroy compatibility? Right now seems like bitcoin core does not have any prefix set for a specific network in the signing rpc. I would also go that far and not implement this signing method for litecoin, because its not really standardized. Or should we  add `Litecoin Signed Message:\n` for the lightning case, I am not sure whether this is used somewhere ? Are there examples of rpc commands which did not support litecoin or does lnd try to always synchronize both?

But I am open for other ways. Maybe I publish a PR which tries to mimic the behaviour of bitcoin-core and btcd and then we go form there ? My first glance at the code showed me that the keychain package seems to be restricted regarding the keyscope to 1017, but there is a mark to add the scope to make the signmessage command more abstract ?

https://github.com/lightningnetwork/lnd/blob/master/keychain/derivation.go#L154

**Comment by ziggie1984** [comment]
**Info**
Currently lnd does use a prefix for node-key signed messages:

`Lightning Signed Message:`
I am wondering why no newline character as in bitcoin-core is used ? 
https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L1566

Though as said before, that would mean that all services requiring bitcoin-core signatures would fail verifying the lnd signature. It seems not an easy task regarding standardization to find the right way how to implement this.

**Comment by Roasbeef** [comment]
> I am wondering why no newline character as in bitcoin-core is used ?

What do you perceive to be the benefit or purpose of adding the new line character?

**Comment by guggero** [comment]
> Could you elaborate how a double hash is better than a single hash

The reason is not that double hashing necessarily adds more security in itself (I think) but that the sighash algorithm always uses double hashing. So if this RPC only did one round of hashing, then an attacker could let the user sign a TX sighash that was only hashed once in order to produce a full, double-signed sighash. Though the added prefix fixes that, I'm sure there was a deeper cryptographic reason to do it that way (something something length extension attack? not sure, I'm not a cryptographer).

> I would favour the approach of having full compatibility with bitcoin-core

Yes, me too.

> I think including a prefix for the different networks would destroy compatibility?

I only meant that we should mirror Bitcoin Core as closely as possible. Only after writing my message did I realize that the linked prefix is a constant in the code base and therefore is not network dependent. So we'd only need a single constant. As for Litecoin, I don't think `lnd` currently even still fully supports Litecoin so I think we can also ignore that for now.

> regarding the signmessage command with the node_id lnd also provides the ability to single hash the message and sign it

That's mainly a hack to get the message signing to work with a remote signing setup. Unfortunately we used single hashing in some places in the protocol so we need to be able to switch between single and double hashing. But that's only on the LN layer and we shouldn't add that flag to any new RPCs.

**Comment by ziggie1984** [comment]
`What do you perceive to be the benefit or purpose of adding the new line character?`

Was just thinking in regards of standardization meaning that hopefully not other lightning implementations just copy the approach from core and add the new line, but I guess as long as there is no real standard for it it does not matter.

**Comment by guggero** [comment]
You sign a message with a private key. The private key for a P2TR address isn't different from any other private key. So as long as the signature isn't expected to be a Schnorr signature for P2TR addresses, nothing special would need to be done. Or am I missing something?

**Comment by ziggie1984** [comment]
You are right, signing is not a problem, but I am also including the 

`lncli wallet addresses verifymessage --message ... --signature ... --address` command. 
The command should be compatible with bitcoin core/btcd, and in core  signature verification is done by checking for a compact signature. This compact signature format is not available for Taproot afaict. Therefore I was asking if we should just create Non-compact signatures when signing with a Taproot addresses, and also verifying it normally without requiring a compact signature. 
Another option would be that we add the compact singing for Taproot as well in the btcd package, I think it should be possible because taproot also is secp256k1?

**Comment by ziggie1984** [comment]
Ahh now I see what you mean, your idea is to sign the message for every address with an ECDSA signature hmm, I would not do that honestly, I would stick to ECDSA for "ecdsa addresses" and either exclude P2TR addresses or sign for P2TR addresses with a schnorr signature.

**Comment by guggero** [comment]
Yes, since as far as I know there isn't a "pubkey recoverable signature format" for Schnorr signatures we'd also use ECDSA for P2TR addresses. We need a way to recover the pubkey from the signature, otherwise we wouldn't be able to verify that the public corresponding to the signing key is actually the key used to create an address.
But I guess since Bitcoin Core won't sign for a P2TR address either (haven't verified this but assuming it is from your earlier comment), we can't be compatible with `bitcoind` anyway.

**Comment by ziggie1984** [comment]
Ok I just realized that the public key for P2Tr addresses does not need to be recoverable in case we are using Taproot without TapScript (its in the output script no hasing involved there). Therefore I think its also possible to use normal Schnorr Signing and verify it against the address which is provided via the grpc call ?

**Comment by guggero** [comment]
The Taproot output key is still a tweaked key, even when using BIP86. Or do you suggest to sign with the tweaked private key instead of the internal key?

**Comment by guggero** [comment]
Another option would be to see if there's already a solution out there that verifies p2tr addresses (couldn't find anything on pocket-bitcoin.com at a very quick glance) and what format they expect?

And I guess another argument against using a tweaked key for the signature would be that it breaks supplying an xpub to an external verifier to avoid address re-use. So yes, as long as we don't have any other examples that do something different, I'd suggest using ECDSA with the internal key for P2TR as well.
