### ISSUE TITLE
[bug]: Change in min_htlc_msat not reflected in getchannels output

### ISSUE THREAD

**Issue by eliotcougar** [lightningnetwork/lnd#7203]
### Background

I wanted to adjust one of my channels that has been sending a lot of very small transactions every 20-30 seconds, exhausting the channel, putting it in an unusable state as described recently again in #7199 ...

### Your environment

LND 0.15.4 on Windows 10

### Steps to reproduce

Try to use the lncli command:
`lncli updatechanpolicy --chan_point [funding_txid:output_index] --min_htlc_msat 10000000 --base_fee_msat 50 --fee_rate 0.000100 --time_lock_delta 40`
The command reports no failed updates, base_fee and fee_rate changes…

It's not the issue with lncli... I also set up charge-lnd to set min_htlc_msat for that channel, and it doesn't work as well (through gRPC)...

I tried it with both local-initiated and remote-initiated channels…

### Expected behaviour

Local policy min_htlc_msat value in getchannels output changes…

### Actual behaviour

The value does not change…

### UPDATE: 
After I changed min_htlc_msat I couldn't send small payments through the channel, which is correct, but the getchannels command still showed min_htlc_msat 1... Routed payments, however, seemed to ignore the minimum limit...

**Comment by bitromortac** [comment]
If I understand your situation correctly:
You have a channel which was opened by the peer, the channel gets pushed in a state where local balance is high, remote balance is low and you run into the commitment fee issue that the peer would not be able to pay for onchain fees if an HTLC would be added. You are able to push micropayments to increase the remote balance, which makes the channel operational again. Now you would like to keep this state by changing `minHTLCMsat` to avoid the micropayments that lead to the stuck state. Because those HTLCs flow into your node, the policy that controls this is the one set by your peer, so you setting `minHTLC` won't affect the size of the incoming HTLCs. Currently I think the only way to prevent this would be to use the HTLC interceptor to cancel those forwardings.

Things I tested:
* `updatechanpolicy` with `minHTLCMsat`: I can see the new policy with `getchaninfo` on the local and another node, LN explorers reflect this as well
* `listchannels` seems to not to reflect `min_htlc_msat` in constraints (but this should be a different issue and needs more investigation)

**Comment by eliotcougar** [comment]
> If I understand your situation correctly: 
Yes. Thank you for the detailed answer... That's exactly what my issue is...
So, in order to prevent routing micropayments through that channel I need to ask the counterparty to set the `min_htlc` limit, right?.. Or does the policy apply only to payments originated from the node that set the policy?..

Indeed, `getchaninfo` shows correct `min_htlc` value, but `listchannels` does not... (which also means that charge-lnd and Zeus mobile wallet use different ways of getting channel info)

So, we have two issues here:
1. possible bug in listchannels output
2. application of min/max htlc policy to routed transactions

**Comment by bitromortac** [comment]
> So, in order to prevent routing micropayments through that channel I need to ask the counterparty to set the `min_htlc` limit, right?

Yes, that's right

> application of min/max htlc policy to routed transactions

It works like designed, but what you would like to achieve represents a new feature and there's already related discussion going on around inbound fees (see https://github.com/lightning/blips/pull/18). Not sure about the current state, but `minHTLCMsat` could be added there.

**Comment by bitromortac** [comment]
The value in `listchannels` is a different `minHTLCMsat`, which is only set on channel opening but can't be changed afterwards (AFAIK) and it does what you'd like to have, but it's static. You can confligure this in your `lnd.conf` (for accepted channels).

**Comment by eliotcougar** [comment]
> The value in `listchannels` is a different `minHTLCMsat`, which is only set on channel opening but can't be changed afterwards (AFAIK) and it does what you'd like to have, but it's static. You can confligure this in your `lnd.conf` (for accepted channels).

This is very confusing and should probably be revised in the future to be less confusing...

In charge-lnd, for example, every time the script tries to adjust `min_htlc_msat` it says it's trying to change it from 1 to 10000000, even though it's already at 10000000, according to `getchaninfo`... It clearly gets the current value from `listchannels` for all channels in bulk, instead of each channel individually via `getchaninfo`... If I'm not lazy I'll re-check and report that to the author there later...

**Comment by bitromortac** [comment]
As a workaround you could also apply a `minHTLCMsat` on all channels, this way you would reject payments of that size entirely, including the incoming channel. The other options as mentioned would be to to ask your peer to set a value, decide a higher (static) `minHTLCMsat` value at channel opening time, or to use the HTLC interceptor to dynamically reject those forwardings. I close the issue, because we can't set `minHTLCMsat` size for our peer and this policy update actually gets reflected in `getchannels` output. Thank you for raising this.
