### ISSUE TITLE
[feature]: additional command to verify aezeed backup - lncli verify seedphrase

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#7224]
It happens, that node-runners need to verify whether their 24 seed-backup is correct to be sure that they can restore the SCB in case of a node failure. Currently people use chantools to do that, but it would come very handy to include this command into lncli/lnd directly. Therefore I propose a command `lncli verifyseed` which takes the 24 words and returns the validity. It could also return the birthday of the wallet, making exporting of the rootkey to other wallets way faster. 

What do you think, or is it overkill and the fact that it is available in chantools is enough?

Feedback Welcome :)

**Comment by guggero** [comment]
We started adding a bunch of wallet provisioning commands to [`lndinit`](https://github.com/lightninglabs/lndinit) and I'm in the process of moving some `chantools` commands over to that. We don't know yet how to integrate `lndinit` into our releases, but it could well be that the binary will ship together with `lnd` and `lncli` in the same archive in the future. So maybe that's a viable option? Since I would think that in a cluster environment you'd probably also want to verify your seed from time to time (in an automated fashion).

**Comment by ziggie1984** [comment]
Yes I think that's a good way to go, have not looked into lndinit yet so will definitely check that out. Having the verifying seed command there sounds reasonable. So I guess I will close the issue and see how lndinit evolves potentially moving the issue over there?

**Comment by Roasbeef** [comment]
Here's a sample program I wrote a while back that lets you input your seed phrase, and it'll return things like the node pubkey and first addr: https://go.dev/play/p/6bB0-pM5O9s

Can be used in an offline setting to verify a seed against public information.

**Comment by ziggie1984** [comment]
This feature will potentially be part of the lndinit lib, so closing it here.
