### ISSUE TITLE
[bug]: QueryProbability deprecated method already not reporting probability

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#7258]
### Background

On docker daily-testing-20221214 the method QueryProbability is not returning a probability score for a known good hop

### Your environment

* lnd daily-testing-20221214

### Steps to reproduce

- Make a channel between A and B and C nodes, large liquidity on A to B and small liquidity on B to C
- Attempt a payment larger than B to C can handle
- Query the probability of paying from A to B

### Expected behavior

- Probability of paying should be returned as a high confidence since that hop just succeeded

### Actual behavior

- Probability of paying is returned as 0

**Comment by bitromortac** [comment]
I can't reproduce this so far. I tried this setup:
- `A -[5/5 Msat]- B -[0/5 Msat]- C`
- create 10 sat invoice
- pay invoice from A, get temporary channel failure

The probability is 0.95 before and after sending for `lncli_A queryprob pubkey_A pubkey_B 10`:
```
{
    "probability": 0.95,
    "history": {
        "fail_time": "0",
        "fail_amt_sat": "0",
        "fail_amt_msat": "0",
        "success_time": "1672836235",
        "success_amt_sat": "11",
        "success_amt_msat": "11000"
    }
}
```
Did I understand the scenario correctly, does A pay the invoice or is there a sender connected to A? It could be helpful if you could add numbers like the capacity, balances and the payment amount. The only way `queryprob` should return a zero probability is when the amount is larger than the channel capacity (within 1%).

**Comment by alexbosworth** [comment]
here is a repro scenario on regtest: https://github.com/alexbosworth/ln-service/blob/master/test/routerrpc-integration/test_get_forwarding_confidence.js - npm install and then run node test_get_forwarding_confidence.js to run the scenario

**Comment by bitromortac** [comment]
I think the problem is that in the test the `QueryProbability` API is invoked with 1msat. In the capacity-PR we needed to fetch a sanitized capacity for the pair in order to estimate a probability. The capacity is not available if the amount is below the lowest `minHTLC` size of all channels, which leads to the correct result of expecting a zero probability. Changing the probe amount to 1sat should fix it.

https://github.com/lightningnetwork/lnd/blob/ef8cf73d4ce4b485d47ded5fa219992574c928c1/lnrpc/routerrpc/router_server_deprecated.go#L148-L155

**Comment by alexbosworth** [comment]
Cool ok
