### ISSUE TITLE
[feature]: wtclient: multiplex clients for different commitment types

### ISSUE THREAD

**Issue by ellemouton** [lightningnetwork/lnd#7540]
Currently, two separate watchtower client instance are created: one for legacy channels and one for anchor channels. These are separately created & managed in the lnd server which exposes complexity that should be managed in the client itself. To add to the current complexity, when we eventually want to start backing up taproot channel updates, with the current design we will then need to start managing three separate tower clients. 

This complexity should instead be managed within the tower client. We should only have to instantiate one client in lnd and then the client should handle the complexity of sending updates to sessions of the correct commitment type.

**Comment by Chinwendu20** [comment]
Hi, I would like to attempt a PR at this issue, please

**Comment by ellemouton** [comment]
Hi @Chinwendu20  - feel free to give it a go. I think it could be quite a challenge though so perhaps giving an outline of how you plan on approaching it first would be a good idea.

**Comment by Chinwendu20** [comment]
Thank you @ellemouton. From what I understand:
https://github.com/lightningnetwork/lnd/blob/f22b25a1bf0382e18003db1eef8b5b803b578562/server.go#L1514-L1554
This block of code highlights the problem referred to in this issue. Two wtclients are being instantiated.

I would like to know if going through the route of including an option in lnd configuration where one can indicate if they would like to use legacy or anchor would be a good solution to this problem.

**Comment by ellemouton** [comment]
> I would like to know if going through the route of including an option in lnd configuration where one can indicate if they would like to use legacy or anchor would be a good solution to this problem.

no that would not work because perhaps the user has both legacy and anchor channels. Then they would want to still back both up with a tower and so both clients will still be needed

**Comment by Chinwendu20** [comment]
Okay thank you from what I understand from your last statement, this would not be a good solution because a user could have BOTH legacy and anchor channel they would like to backup.

Naively, I would say then they could indicate both, and the would-be instantiated

**Comment by ellemouton** [comment]
> Or is it the issue, that two should not be instantiated in any case in the newserver function. Logic in wtclient itself should take care of that?

yes exactly

**Comment by Chinwendu20** [comment]
Hi @ellemouton .From my understanding of the codebase we are initiating two tower clients, so as to compare tower client configuration's policy with existing session's policy and while creating new sessions the policy assigned to a session is same as that of the tower client configuration. How about if we remove the blob field in the Policy field in clientSession:

https://github.com/lightningnetwork/lnd/blob/dc16f5df53128a8726942100831f9adce43febc3/watchtower/wtpolicy/policy.go#L82-L102

From here:

https://github.com/lightningnetwork/lnd/blob/f22b25a1bf0382e18003db1eef8b5b803b578562/server.go#L1534-L1536
I can see that is the only difference between an anchor policy and legacy policy


stateUpdate could have an additional boolean field indicating whether the backup task it was crafted from was anchor or legacy. In that way while crafting a state update here:

https://github.com/lightningnetwork/lnd/blob/55b53555e93d30ad1c1ef5a841650287f99aea44/watchtower/wtclient/session_queue.go#L455-L462

there would be an extra field with say .chanType.HasAnchors()
So any task that requires clarification if anchor or legacy we can access it directly from the field in the stated update instead of the session

**Comment by ellemouton** [comment]
it is a bit more complicated that that: at the point that you have the `sessionQueue` you have already negotiated the session type with the tower. So it doesnt help to add the commitment type in the `CommittedUpdate` since at that point it has already been bound to a specific session.

This feature would be pretty complex to implement and would require quiet a big architecture change.

**Comment by Chinwendu20** [comment]
I guess so. I would be happy to learn from whoever goes on to submit the PR. Thanks for indulging me.
