### ISSUE TITLE
[feature]: udpate `sample-lnd.conf` to show default values AND example values

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#7612]
The `sample-lnd.conf` file in the root directory of the project provides sample values for all existing configuration options of `lnd`.

Often those values are mistaken for the _default_ values, which is not necessarily the case. Because many of the default values are empty, an explicit example is provided to show what an expected value would look like.
A random example would be:

```
; A list of domains for lnd to periodically resolve, and advertise the resolved
; IPs for the backing node. This is useful for users that only have a dynamic IP,
; or want to expose the node at a domain.
; externalhosts=my-node-domain.com
```

It would be great if we could show both the default value (and make an effort to keep those updated) and an example to remove the confusion.
So the example from above would now look like this:

```
; A list of domains for lnd to periodically resolve, and advertise the resolved
; IPs for the backing node. This is useful for users that only have a dynamic IP,
; or want to expose the node at a domain.
; Default:
;   externalhosts=
; Example (option can be specified multiple times):
;   externalhosts=my-node-domain.com
;   externalhosts=my-second-domain.com
```

For simple values (for example boolean values) where the default value is example enough, we would still keep this format to keep things compact:

```
; If set, then all certs will automatically be refreshed if they're close to
; expiring, or if any parameters related to extra IPs or domains in the cert
; change.
; tlsautorefresh=true
```

IMPORTANT: The library that `lnd` uses for command line and config file option parsing does not allow setting boolean values to `false` explicitly. So the default value of ALL boolean flags is always `false` and you can toggle them to `true` with a command line flag (e.g. `--tlsautorefresh`). This is not necessarily obvious from the config file alone and should also be mentioned.

So the steps to complete this task are:

- [ ] Describe the format (default values vs. example values) of the config file at the top, including mentioning the specifics around boolean values as described in the paragraph above.
- [ ] Update all values in the file to represent the default values (they can be obtained by running `lnd --help`).
- [ ] Where the default value is empty, add an appropriate example value.
- [ ] (bonus/optional): Add a shell script that can compare the default values in the config file vs. the default values in `lnd --help` so we can add an automated step in the CI to catch changes in default values. See the `sample-conf-check` step in the `Makefile` for some inspiration.

**Comment by feelancer21** [comment]
I will give it a shot.

**Comment by feelancer21** [comment]
I took a look once and wrote a conversion script of `sampel-lnd.conf`. But since there are still some manual interventions necessary afterwards, I would like to discuss a few points before I start with the PR.

1) For many options the set default and the current example do not match. Below you will find a table with discrepancies. In these cases I would leave only the current default in `sample-lnd.conf` and discard the previous example. 

2) In cases where the current example has a recommendation character, we should discuss about the amount of the default at another place, like e.g. `bitcoin.maxlocaldelay=10000`, which I personally think is too high. I would just mention the default there as well.

3) I would always specify defaults, also the simple ones and the booleans, in two lines (as suggested above). This makes it easier for newcomers to understand the file and also facilitates the plausibility check between `lnd --help` and `sample-lnd.conf`.

4) At Booleans there are currently also quite a few examples with value of `true`. I would always consistently set a value of `false` because of guggero's comment.


|Option|Default|Current Example|
|-----|-------|---------------|
|coop-close-target-confs|6|10|
|channel-commit-interval|50ms|1h|
|pending-commit-interval|1m0s|5m|
|chan-enable-timeout|19m0s|22m|
|chan-disable-timeout|20m0s|22m|
|chan-status-sample-interval|1m0s|2m|
|historicalsyncinterval|1h0m0s|2h|
|max-channel-fee-allocation|0.5|0.9|
|max-commit-fee-rate-anchors|10|5|
|dust-threshold|500000|1000000|
|trickledelay|90000|180000|
|numgraphsyncpeers|3|9|
|bitcoin.maxlocaldelay|10000|2016|
|neutrino.useragentversion|0.12.0-beta|0.11.0-beta|
|litecoin.maxlocaldelay|10000|2016|
|autopilot.maxchansize|16777215|20000|
|autopilot.minconfs|1|2|
|autopilot.conftarget|3|2|
|tor.control|localhost:9051|localhost:9091|
|healthcheck.chainbackend.timeout|30s|10s|
|healthcheck.chainbackend.backoff|2m0s|30s|
|healthcheck.diskspace.interval|12h0m0s|6h|
|healthcheck.torconnection.backoff|1m0s|30s|
|routerrpc.minrtprob|0.01|1|
|routerrpc.maxmchistory|1000|900|
|routerrpc.mcflushinterval|1s|1m|
|routerrpc.attemptcost|100|90|
|routerrpc.attemptcostppm|1000|900|
|routerrpc.apriori.hopprob|0.6|0.2|
|routerrpc.apriori.weight|0.5|0.3|
|routerrpc.apriori.penaltyhalflife|1h0m0s|2h|
|routerrpc.apriori.capacityfraction|0.9999|0.9|
|routerrpc.bimodal.scale|300000000|1000000000|
|routerrpc.bimodal.nodeweight|0.2|0.1|
|routerrpc.bimodal.decaytime|168h0m0s|72h                                         |
|workers.read|100|200|
|workers.sig|8|4|
|caches.reject-cache-size|50000|900000|
|caches.channel-cache-size|20000|9000000|
|db.sqlite.maxconnections|2|0|
|db.sqlite.busytimeout|5s|10s|
|cluster.leader-session-ttl|60|30|
|invoices.holdexpirydelta|12|15|

**Comment by guggero** [comment]
@feelancer21 thanks a lot for picking this up and kudos for taking a scripted approach! That will give a high probability of not introducing small mistakes due to the repetitiveness of the task at hand.

> For many options the set default and the current example do not match. Below you will find a table with discrepancies. In these cases I would leave only the current default in `sample-lnd.conf` and discard the previous example.

Great table, thanks a lot for that! I looked over the values and I agree that we should just revert all of those to the default values.

> In cases where the current example has a recommendation character, we should discuss about the amount of the default at another place, like e.g. `bitcoin.maxlocaldelay=10000`, which I personally think is too high. I would just mention the default there as well.

Out of curiosity, where did you find that value of 10k? I'm looking at `master` which has the default (and recommended) value of 2016. But I agree that our defaults should reflect recommended values. And I also agree that a discussion about changing a default value should be held in its separate PR. So for now I would say that if the sample file contains an example that is recommended and different from the default, we should probably keep it as an example but change the wording to reflect that (same could be true if the recommended values are different for different user requirements):

```
; The maximum number of blocks we will limit the wait that our own funds are
; encumbered by in the case when our node unilaterally closes. If a remote peer
; proposes a channel with a delay above this amount, lnd will reject the
; channel.
; Default:
;   bitcoin.maxlocaldelay=2016
; Recommended value for users that require XYZ:
;   bitcoin.maxlocaldelay=10000
```

> I would always specify defaults, also the simple ones and the booleans, in two lines (as suggested above). This makes it easier for newcomers to understand the file and also facilitates the plausibility check between `lnd --help` and `sample-lnd.conf`.

You mean just adding the `Default:` text and indenting the default value? I thought about that too but was worried about making the already long file even longer. But it's probably a good idea to make the file as uniform as possible. Let's see how big the diff looks and decide then?

> At Booleans there are currently also quite a few examples with value of true. I would always consistently set a value of false because of guggero's comment.

Yes, I agree.

> I'd like to delete all defaults mentioned in the text, e.g. "(default: apriori)".

Yes, I agree. Those were probably just added from copy/pasting the CLI output.
