### ISSUE TITLE
[feature]: allow user-specified label when opening channels

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#7639]
When opening channels, a user may want to specify a `label` field that says what the channel was for or to store some other channel-related information. This could likely just be a TLV field that is size-constrained to prevent accidentally storing a large hunk of data. 

The flow in my head to implement this would look something like this:
- `OpenChannel` (cli + RPC) call would take a hex-encoded string and passes this in the `lnrpc.OpenChannelRequest` struct
- `funding.InitFundingMsg` would be modified to accept a hex-encoded string. This would be set in `rpcserver.go` here https://github.com/lightningnetwork/lnd/blob/fdc1ae9d57326cc82899e4c76d5069b14a764b96/rpcserver.go#L2213
- In `handleInitFundingMsg`, the `InitFundingReserveMsg` would take this hex-encoded string before being passed to `InitChannelReservation`: https://github.com/lightningnetwork/lnd/blob/fdc1ae9d57326cc82899e4c76d5069b14a764b96/funding/manager.go#L4141
- Then in `NewChannelReservation`, the created `OpenChannel` struct would store the hex-decoded raw `[]byte`.
- The `OpenChannel` would have routines to persist the data in `putOpenChannel`. This shouldn't require a migration since the data can be stored within the tlv stream here: https://github.com/lightningnetwork/lnd/blob/f9f08079d0a0ffefabb99e210708a4733825ebef/channeldb/channel.go#L3632
- There should also be routines on `OpenChannel` for fetching the data in `fetchOpenChannel`.

Then when `listchannels` is called, the raw `[]byte` can be surfaced either as a tlv stream or a string.

**Comment by shaurya947** [comment]
Hey @Crypt-iQ this seems like a handy feature and I can see myself using this for short notes when opening channels. I'd love to attempt this, seems it would be a good exercise for me to get familiar with the end-to-end work involved in modifying a command to accept a new flag.

I'm not familiar with how tlv streams operate though. I searched around for old PRs that did something similar and found this: https://github.com/lightningnetwork/lnd/pull/6551/files
Would this be a good example to follow? I'd have to create a new `tlv.Type` inside of `channel.go` and then build a new record and append it to the tlv stream?

As for the data type (and for limiting the size), would [64]byte be good? Or should it be a variable byte slice with an enforced upper bound?

**Comment by Crypt-iQ** [comment]
> Would this be a good example to follow? I'd have to create a new tlv.Type inside of channel.go and then build a new record and append it to the tlv stream?

Yup

> As for the data type (and for limiting the size), would [64]byte be good? Or should it be a variable byte slice with an enforced upper bound?

Limiting size can be done at the rpc-layer (so reject the `openchannel` if the size is too large). That way we can just store a `[]byte` in `channeldb/channel.go`

**Comment by shaurya947** [comment]
Sounds good! I'll aim to have a PR up mid-next week :)

Apr 28, 2023 3:33:11 p.m. Eugene ***@***.***>:

**Comment by shaurya947** [comment]
Hey @Crypt-iQ I started working on this today. Pushed some commits here: https://github.com/shaurya947/lnd/commits/open-channel-memo

I was hoping to get your feedback on the following:
- I decided to name the argument `memo` instead of `label` to not conflict with the `label` argument already present on the `BatchOpenChannel` CLI/RPC command. Thoughts?
- This may be a dumb question, but what makes it preferable to store a hex-encoded version as opposed to the plain string? Are there considerable size savings typically?
- I am enforcing a string length of 500 characters in the RPC layer for the time being. Does that seem reasonable?
- When adding fields for persistence, how do we determine whether we add them to the [`WriteElements` call](https://github.com/shaurya947/lnd/commit/3f025673bc6e365a0240c2f836b1b16f842d5b3b#diff-793204e241c4f89dc7184266600f1aca57cb8e3970ab714f0c65fba1a6826066R3610) or whether we add them as a new tlv record? I assume the former requires a DB migration whereas the latter does not? Is that the only reason? Would there be cases where DB migration is desirable when adding a field (and hence we'd use `WriteElements`)?

**Comment by Crypt-iQ** [comment]
> I decided to name the argument memo instead of label to not conflict with the label argument already present on the BatchOpenChannel CLI/RPC command. Thoughts?

sounds good

> This may be a dumb question, but what makes it preferable to store a hex-encoded version as opposed to the plain string? Are there considerable size savings typically?

can be `[]byte` so that if you want to store data that is not `string`, you can. just allowing the possibility, not entirely sure of all the use-cases here

> I am enforcing a string length of 500 characters in the RPC layer for the time being. Does that seem reasonable?

sounds good

> Would there be cases where DB migration is desirable when adding a field (and hence we'd use WriteElements)?

yeah we want to avoid DB migrations where possible and using `WriteElements` would require a migration
