### ISSUE TITLE
`peer_alias` output of listchannels shouldn't include error message

### ISSUE THREAD

**Issue by Crypt-iQ** [lightningnetwork/lnd#7858]
It contains a string rather than an empty value
```
{
    "channels":  [
        {
            <truncated>
            "peer_alias":  "unable to lookup peer alias: alias for node not found",
            "peer_scid_alias":  "0",
            "memo":  ""
        }
    ]
}
```

**Comment by guggero** [comment]
See discussion in https://github.com/lightningnetwork/lnd/pull/7471. This was on purpose. The options were:
1. Fail `listchannels` lookup because of incomplete graph data (very bad UX and can happen on regtest or even mainnet a lot)
2. Silently not return an alias, which wouldn't let the user distinguish between an alias not being set and an error having occurred
3. Only log the error. That's likely to spam the log and go unnoticed still
4. Put the error in the actual alias.
