### ISSUE TITLE
[CHANNEL DONT CLOSE]: 

### ISSUE THREAD

**Issue by amtexugo** [lightningnetwork/lnd#7912]
### Background MY NODE
https://amboss.space/node/022db2e3a531bb8f85d258c134ba013b7d17bc04d6984efebf9c1f0f63e9c0f596

Hello friends!

I'm getting in touch with you guys because of a channel (channel id: 875883057335566337) opened with you that has been closing for two weeks but has not completed closing. Could you let me know what the procedure is? If something is wrong? Here's the id and the print...

### Your environment
https://user-images.githubusercontent.com/127704297/262739039-c972c335-ee56-4908-8f13-582ad8b0d607.jpg

* LNDg v1.7.0`
* RASPIOS 4 UMBREL 
* Bitcoin Core 25.0.0
* LND 0.16.4-beta 
 
THANKS

**Comment by guggero** [comment]
The closing transaction doesn't have enough fees. And because it is the old channel type that doesn't have an anchor output for CPFPing, you can't really do anything other than wait. Or ask your peer to sweep their part of the funds to confirm the closing transaction (you can't do that on your end because your funds are time locked).

Closing the issue as everything looks normal and should resolve eventually (if/when the mempool clears). The issue itself is resolved by using anchor channels for new channels.
