### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by Rothschildiuk** [lightningnetwork/lnd#7987]
### Background

I tried to open a channel and specified a low fee (6.00 sat/vB) when I realized that the commission was too low, I increased it with the bumpfee command
`./lncli wallet bumpfee --sat_per_byte 11 4c39ca1008d700055e20597e83a385599fd123de20c138bc3696981fd9a18449:1`

open chanel tx id with 6.00 sat/vB
https://mempool.space/tx/4c39ca1008d700055e20597e83a385599fd123de20c138bc3696981fd9a18449

CPFP tx id
https://mempool.space/tx/a58c37cc10f0ee64acfbf7c468442d762b7e48916afede6a9d88d06e738fc09f

After that, my bitcoins were sent to the address where they are still located today: bc1prgv7kdd32lqexyuw4yp0umynxrcxgykaxqe24gzvg70eapqkzxzsw69y34, but for some unknown reason, another transaction was created to another address where the commission was too low (1.011 sat/vByte), so this transaction got stuck.

I can only see this transaction on blockchain.com (I also don't know why)
(https://www.blockchain.com/explorer/transactions/btc/75cb20efb06e0ff8b27ffbcb8130b05004ec84a9f147ee4e19d281c03525938e)

It's been stuck there for almost 30 days and I can't do anything about it, because I can only see the incoming  pennding transaction, but not the outgoing one.

Since this is my incoming and outgoing transaction, I can increase the commission for it using RBF, but how to do it when I don't see the outgoing transaction

<img width="991" alt="image" src="https://github.com/lightningnetwork/lnd/assets/15833131/d738dfc6-122f-4366-a285-d80f806dfc84">

umbrel@umbrel:~/umbrel $ ./bin/lncli wallet pendingsweeps
`
{
	"pending_sweeps": [
		{
			"outpoint": "75cb20efb06e0ff8b27ffbcb8130b05004ec84a9f147ee4e19d281c03525938e:0",
			"witness_type": "TAPROOT_PUB_KEY_SPEND",
			"amount_sat": 1097029,
			"sat_per_vbyte": 50,
			"broadcast_attempts": 6,
			"next_broadcast_height": 807707,
			"requested_sat_per_vbyte": 50,
			"requested_conf_target": 0,
			"force": false
		}
	]
}`

### Your environment

* LND 0.16.4-beta
* linux (umbrel node)

**Comment by ybaidiuk** [comment]
I have the same issue. 
Does somebody know how to export private key from LND ?
How long the transaction can be in the mempool, or it can be a recognize as unconfirmed by LND ?

**Comment by Rothschildiuk** [comment]
I found something similar to my problem, but I don't have enough knowledge to figure it out. There are also 330 satoshis like mine (Ghost UTXO)
https://github.com/lightningnetwork/lnd/discussions/7420

**Comment by ViktorTigerstrom** [comment]
Hi @Rothschildiuk!

What has likely happened, is that your node has dropped the tx from it's mempool as it was published some time ago and is therefore unable to bump the fee again with the `lncli wallet bumpfee` command.

What you likely need to do is to first run the `lncli wallet publishtx` command to republish the transaction (for the `75cb20efb06e0ff8b27ffbcb8130b05004ec84a9f147ee4e19d281c03525938e` txid), and then your node will be able to bump the fee once more.

1. In order to run the `publishtx` we first need to grab the raw transaction hex for the transaction. Can you still see the transaction for `75cb20efb06e0ff8b27ffbcb8130b05004ec84a9f147ee4e19d281c03525938e` if you run `lncli listchaintxns`? If you can, copy the value for the field `raw_tx_hex` for that transaction.

2. Once you have the `raw_tx_hex`, run the following command: `lncli wallet publishtx VALUE_FOR_RAW_TX_HEX`

3. Now, let's retry to bump the fee with the following command: `lncli wallet bumpfee --sat_per_vbyte APPROPRIATE_SAT_VALUE 75cb20efb06e0ff8b27ffbcb8130b05004ec84a9f147ee4e19d281c03525938e:0`. You could also run the command with a `conf_target` instead of a `sat_per_vbyte` if you prefer to do so. 

Let me know if that helps!

**Comment by ViktorTigerstrom** [comment]
Hi @Rothschildiuk!

Great to hear that the issue was fixed! It's expected behaviour that lnd will include these 330 satoshi inputs in transactions, those are called anchor outputs and can only be claimed by you for a given amount of days, and can after that be claimed by anyone else.
This is why the anchor output was included as an input to your transaction. When the transaction was initially created, only you (your node wallet) could claim the anchor output, and the wallet therefore includes it as an input.

The issue was that as your initial transaction was never confirmed, the number of days until anyone can spend the anchor output passed, and therefore someone else spent the anchor output which now made your transaction invalid as it included the anchor output as an input.

**Comment by ViktorTigerstrom** [comment]
Closing this as the issue has been resolved by @Rothschildiuk. Let me know if you'd like me reopen it!

**Comment by guggero** [comment]
The behavior around minimum fee rates and the sweeper were fixed in 0.17, so this scenario shouldn't happen anymore AFAIK.
