### ISSUE TITLE
Can't unlock: "segwit address exists in wallet"

### ISSUE THREAD

**Issue by Stadicus** [lightningnetwork/lnd#837]
After upgrading to Bitcoin Core 0.16.0 LND was running fine at first. A few days later, I get the following error:
```
$ lncli unlock
Input wallet password:
[lncli] rpc error: code = Unknown desc = segwit address exists in wallet, can't upgrade from v4 to v5: well, we tried  ¯\_(ツ)_/¯
```

The bitcoind wallet has never been used, balance is zero.
```
$  bitcoin-cli getaddressesbyaccount 0
[
]
$ bitcoin /home/admin ฿ bitcoin-cli getbalance
0.00000000
```

Is this related to the bitcoind version & wallet at all, or is it referencing to the LND internal "wallet"?

**Comment by Roasbeef** [comment]
`lnd` doesn't use the Bitcoin Core wallet. Instead, it has its own internal wallet. 

It looks like you're running an older version of `lnd`, and some breaking changes have landed in master since then. If you want to proceed, you should close out all your prior channels, then start with a clean data directory, and finally update to the latest commits. You can use `git reflog` to find the commit you were at before you checked out master.
