### ISSUE TITLE
healthcheck: make sure chain backend has enough outbound peers

### ISSUE THREAD

**Issue by yyforyongyu** [lightningnetwork/lnd#8487]
Resulted from a discussion in #8418, we should have a health check on the number of outbound peers to make sure `bitcoind` maintains a healthy connection to the network, which is straight forward,
- use `GetPeerInfo` to get the peers info and count the outbounds.
- if the number is below 6, log warnings.
- if the number is below 2, maybe stop `lnd`?

**Comment by Crypt-iQ** [comment]
I don't think we should stop lnd if we have below two outbound peers. bitcoind should recover from this automatically and this would make lnd stop in some benign situations

**Comment by srikanth-iyengar** [comment]
I would like to work on this issue,
So just to confirm we don't have to stop the `lnd` if the out bound peers drop below 2 right ?

**Comment by Crypt-iQ** [comment]
I don't think this issue has any actual use other than logging for something that we're not going to fix? If they're using bitcoind then bitcoind will solve this automatically.

**Comment by srikanth-iyengar** [comment]
Oh....then we are just going to log, will go ahead then

**Comment by srikanth-iyengar** [comment]
I have a question,
I was planning to create a separate method for getting the peerCounts which will have the following signature in `healthcheck/peercheck.go`
```go
func GetOutboundPeers(bitcoinNode string, bitcoind *lncfg.Bitcoind, neutrino *lncfg.Neutrino, btcd *lncfg.Btcd) {
    // prepare a rpcConfig using a simple switch
    client, err := rpcclient.New(&rcpconfig, nil)
    if err != nil {
        return fmt.Errorf("Error creating rpcclient %w", err)
    }
    // return the number of peers
}
```
But the problem is healthcheck is completely a different module and I cannot simply import lncfg,

If we cannot have lncfg in healthcheck how should I proceed further ?

One way I could think of  is, Create a simple utils class which will take the *Config as param and will return the outbound peers somewhere within the lnd module, then I will simply call that method and log according to the number of peers

should I proceed with my proposed idea or am I like, totally messing up here?
