### ISSUE TITLE
[bug]: Watchtower Servers Cannot be Removed

### ISSUE THREAD

**Issue by zapomatic** [lightningnetwork/lnd#8547]
This may be all fixed up in the 0.18 release items since I see there are some watchtower management fixes there.
I have a case where I have added 3 watchtower services. Two of them are regularly failing to connect and have varying levels of unacked updates queued--they aren't totally dead because they have many acked updates and occasionally work but the amount of failures has me wanting to remove them in exchange for others that are consistently working--especially because my lnd logs are filling up with `unable to dial tower at any available Addresses` errors. However, the active queue of unacked updates is preventing me from removing these towers.

[As previous issues suggested](https://github.com/lightningnetwork/lnd/issues/4420#issuecomment-1315067772), I have tried disabling wtclient.active, deleting watchower.db, restarting, which loads up lnd without watchtowers fine, but when I re-enable wtclient.active, and restart, all the previous towers are back and I'm still unable to remove the towers that have unacked updates. Are these not stored in watchtower.db?

* version of `lnd` - lnd 0.17.4-beta

**Comment by ellemouton** [comment]
hi @zapomatic  - yes this should be fixed in 0.18 with the new `Deactivate Tower` call. It will allow you to instruct LND to keep all previous data that was backedup with that tower but to stop trying to connect to it etc. 

Im going to close this for now since it should be fixed in the next release but feel free to open it again if after the release you run into similar issues :)
