### ISSUE TITLE
[feature]: Make 12-word mnemonic phrase possible

### ISSUE THREAD

**Issue by ffrediani** [lightningnetwork/lnd#8787]
**Is your feature request related to a problem? Please describe.**
When installing LND it forces the usage of 24-word mnemonic phrase as the only option.
As I understand it correctly it is due to aezeed cipher seed scheme that encodes only using 24-word (https://github.com/lightningnetwork/lnd/blob/master/aezeed/README.md)
People are used and may prefer to have the simpler 12-word mnemonic phrase which already provides enough security in not being decrypted with its 128 bits.

Can another scheme be added in order to allow user choose to create its seed phrase with either 12 or 24-word instead of just 24 as it is now ?

**Describe the solution you'd like**
Another method that allows the use to choose which size of mnemonic phrase to create.

**Describe alternatives you've considered**
Keep storing the longer 24-word

Ref: https://www.exodus.com/support/en/articles/8598627-everything-you-need-to-know-about-your-12-word-secret-recovery-phrase

**Comment by guggero** [comment]
If you look at the linked README, you see that the aezeed actually only encodes 16 bytes of real entropy/randomness, which is equivalent to 12 words of a BIP-39 seed. The rest is a version number, the birth date of the seed and a salt/checksum for the encryption. So making the aezeed shorter would mean we would use an insecure amount of entropy.

You can, however, create an `lnd` wallet from an xprv, which you can derive from a normal 12 word BIP-39 seed.

**Comment by Roasbeef** [comment]
The 24 word phrase has just about the same amount of entropy as the 12 word phrase, but also includes a birthday (so you know when to start a rescan) and also a version. Unlike BIP 39, it can be used with any langauge/encoding as well. So you don't have an English specific seed phrase, then a Spanish specific one, etc.

**Comment by ffrediani** [comment]
@Roasbeef why did you simply close it before it was resolved ?

Why limit it to only 24-word and not give the user to choose either ? 
What is the risk for the user to be able to choose 12-word if someone wishes to ?

**Comment by guggero** [comment]
You don't seem to understand our responses.

> why did you simply close it before it was resolved ?

Because using a 12 words only `aezeed` would NOT be secure.

Let me try to break it down for you one more time.
The current 24 word `aezeed` scheme (because it encodes more information than just the entropy/seed bytes) has the same security as a 12 word BIP-39 seed.
If you wanted to cut that in half, then a 12 word `aezeed` would only have the same security as a 6 word BIP-39 seed, which doesn't exist, because it is not secure.

Perhaps what you want instead is the ability to create a `lnd` wallet by directly entering a 12 word BIP-39 seed in `lncli create` instead of needing to convert to xprv?

**Comment by guggero** [comment]
`lnd` will never allow you to create a seed other than `aezeed` with 24 words. Because we precisely want all the benefits you get with `aezeed` (a wallet birthday to know when to re-scan from and the ability to change the seed passphrase).

But if you want to be able to use a 12 word seed created outside of `lnd` to initialize the wallet, then I think the issue title should be: "lncli: allow wallet to be created from BIP-39 seed directly".

Then you have 4 options in the `lncli create` command:
1. Create a new seed (will always be 24 word `aezeed`)
2. Use an existing 24 word `aezeed`
3. Use an `xprv`
4. Use a BIP-39 seed (<-- this would be new)

If you agree with that and change the title, I'll re-open.

**Comment by ffrediani** [comment]
Right, but do we need all these benefits or do they need to be mandatory ? Cannot these be optional to those who don't want to store a 24-word seed phrase ?
Can't an alternative solution be developed that gives whatever is needed for Lightning and doesn't necessarily impose a 24-word seed phrase as a minimum ?

Yeah, pretty much that is the request, for the user to be able to create a BIP-39 seed for Lightning keeping enough security as it is in several other scenarios with its 128-bits.

Thanks for clarifying and detailing it.
