### ISSUE TITLE
[feature]: Make Fees optional for FundPsbt with Raw template

### ISSUE THREAD

**Issue by Impa10r** [lightningnetwork/lnd#9008]
**Is your feature request related to a problem? Please describe.**
LND takes integer sat/vb fee rate as an input, but creates transactions paying slightly higher or slightly lower fee rate in the end. For example, if I want to completely spend 1000 sats p2wkh UTXO paying 1 sat/vb fee from the amount, FundPsbt with CoinSelect gives me these fee rates in the final tx, depending on destination address type:

p2sh: 0.99 sat/vb (tx size 111, fee 110)
p2wkh: 0.99 sat/vb (tx size 110, fee 109)
p2tr: 1.01 sat/vb (tx size 121, fee 122)

Lower than 1 cannot be posted, of course, but higher than what I request also creates a problem: if I want to RBF my transaction paying 1.01, I must choose 3 and not 2 sat/vb as a replacement fee. I want to be exact and not waste sats.

[This example](https://mempool.space/testnet/tx/0d36fce5831da633f5f0b29a10d3f4837fbf43830f62d63694f8e5847e4f786b) was supposed to pay 51 sat/vb from p2tr to p2tr with change. It paid 51.3.

**Describe the solution you'd like**
I can catch the discrepancy before the tx gets posted, but I cannot find a way to adjust the outputs in the PSBT. I wish Raw template could be just that: I provide exact inputs and outputs, and the fee is calculated as the difference. Fees field in` walletrpc.FundPsbtRequest` should be optional (indicated by `Fees: &walletrpc.FundPsbtRequest_SatPerVbyte{SatPerVbyte: 0}`, for example).

**Describe alternatives you've considered**
I guess fixing FundPsbt to give correct results in all scenarios is too much to ask.

**Additional context**
For some reason SignPsbt and FinalizePsbt refuses a PSBT produced by Bitcoin Core's `createpsbt` API. I get error "input (index=0) doesn't specify any UTXO info" when PSBT looks like this:

```
$ bcli decodepsbt cHNidP8BAFMCAAAAAX/t1h8ZB4oXpsN9PkH0PxNXx3WZm19935GPmZjThgq4AAAAAAD9////AXkDAAAAAAAAF6kUVJMUMexBAfpouB3rbaqlivs8XPGHAAAAAAAAAA==
{
  "tx": {
    "txid": "a1b6bd7e47877ff6e7a1bb08e7265cca2734d1fd1b7f3d426e39dc0f28c64a92",
    "hash": "a1b6bd7e47877ff6e7a1bb08e7265cca2734d1fd1b7f3d426e39dc0f28c64a92",
    "version": 2,
    "size": 83,
    "vsize": 83,
    "weight": 332,
    "locktime": 0,
    "vin": [
      {
        "txid": "b80a86d398998f91df7d5f9b9975c757133ff4413e7dc3a6178a07191fd6ed7f",
        "vout": 0,
        "scriptSig": {
          "asm": "",
          "hex": ""
        },
        "sequence": 4294967293
      }
    ],
    "vout": [
      {
        "value": 0.00000889,
        "n": 0,
        "scriptPubKey": {
          "asm": "OP_HASH160 54931431ec4101fa68b81deb6daaa58afb3c5cf1 OP_EQUAL",
          "desc": "addr(2MzxQwcnvFLqAw6Xf9ZgmkmNUvcPuG2c7cb)#caacrhz8",
          "hex": "a91454931431ec4101fa68b81deb6daaa58afb3c5cf187",
          "address": "2MzxQwcnvFLqAw6Xf9ZgmkmNUvcPuG2c7cb",
          "type": "scripthash"
        }
      }
    ]
  },
  "global_xpubs": [
  ],
  "psbt_version": 0,
  "proprietary": [
  ],
  "unknown": {
  },
  "inputs": [
    {
    }
  ],
  "outputs": [
    {
    }
  ]
}
```

**Comment by guggero** [comment]
Thanks for the feature request.

The inaccuracy of the actual fee vs. the specified unfortunately cannot be fixed, unless you switch over to P2TR completely. The problem is that any ECDSA signature (so affecting p2wkh and p2sh/np2wkh **inputs**) is [variable](https://bitcoin.stackexchange.com/questions/77191/what-is-the-maximum-size-of-a-der-encoded-ecdsa-signature/77192#77192), so it cannot be estimated precisely.
This is the nice thing about P2TR **inputs**, they are constant in size and fee estimation is precise down to the virtual byte.

For the issue of not being able to specify the fee rate more precisely: I think here we could just add a third option, to allow you to specify in `sat/kWU`, which is way more precise (e.g. `1 sat/vByte = 250 sat/kWU, 1.5 sat/vByte = 375 sat/kWU`.
But that would require a change and you'd need to wait for the next release.

Maybe you could also use the new third option, `coin_select` (https://lightning.engineering/api-docs/api/lnd/wallet-kit/fund-psbt#walletrpcpsbtcoinselect) for specifying the template (that was introduced with `lnd v0.18`.

It allows you to specify the exact inputs and outputs and specify if a new change output should be added or the change be given to an existing (specified) output. If you say "add a new change output" but the change amount is **below dust**, then the value is added to fees.

With that I think you could create very accurate RBF transactions.
Let's look at an example.

```
TX 1:
-------
Input:       p2tr, 1000 sats
Tx size:     100 vBytes
Fee rate:    1 sat/vByte
Output:      900 sats
Actual fee:  100 vBytes (1.00 sat/vByte)


TX 2:
-------
Input:       p2tr, 1000 sats
Tx size:     100 vBytes
Fee rate:    1 sat/vByte
Output:      880 sats
Actual fee:  120 vBytes (1.20 sat/vByte)

TX 3:
-------
Input:       p2tr, 1000 sats
Tx size:     100 vBytes
Fee rate:    1 sat/vByte
Output:      850 sats
Actual fee:  150 vBytes (1.50 sat/vByte)
```

**Comment by Impa10r** [comment]
@guggero Thanks. I do use [CoinSelect template](https://github.com/Impa10r/peerswap-web/blob/4614aeec39b5a56c289abe84df3104a4f891797a/cmd/psweb/ln/lnd.go#L516). FundPsbt still requires Fees object along with this template, but you're right, p2tr to p2tr seems to be spot on, while p2wkh inputs give random witness size: 
https://mempool.space/testnet/tx/e9d76d2aa85500e030ec9f2a3d9d602256c6568113c7fd6e0c19fff301f49caf
https://mempool.space/testnet/tx/4fd1c284acc7ac8562215c176e6cd5d5987aa98fe61a740459166a55ba7753fe

Your suggestion to add sat/kWU fee option is good and welcome.

In the meantime, I learned to use btcd/btcutil/psbt to manipulate p.UnsignedTx.TxOut[outputIndex].Value and achieve the exact desired fee (finalize, look at vsize, release outputs, amend psbt, finalize again).
