### ISSUE TITLE
[bug]: min_relay fee estimation issue when running with Bitcoin Knots

### ISSUE THREAD

**Issue by feelancer21** [lightningnetwork/lnd#9048]
It's not my node. But it looks like the guy used Ind. There are force closures with other Lnd nodes (e.g. Garlic, Tatooine) that cost a couple million sats. No idea how that could have happened. Maybe there is a big issue. 

It looks like there are 100,000 sats as pending HTLC and a balance of 2.8 MSats. I suspect the second balance output is missing in the commitment and was spent as a fee.

https://mempool.space/tx/f6a0e105bd2fc24ff9d7ddd19f239fdcd4da657a9d3b0fd15341a1bf434e1791

**Comment by silenzara** [comment]
My channel also force closed but the closing tx looks normal: https://mempool.space/tx/cc2a26e162a2f901831ba7f7906d1b036cf7a8ad7e21b7b656838fea8e54a8b8

I was the channel opener and I'm running 0.18.3.rc1 with Libre Relay v0.27.1 (bitcoind with replace-by-feerate patch by Peter Todd).

**Comment by Roasbeef** [comment]
Updated the issue a bit, IIUC the user was running Bitcoin Knots, so it's possible some RPC call uses diff units for fees, or has different behavior from normal Bitcoin Core.

**Comment by Roasbeef** [comment]
So far it looks like the `min_relay_fee` returned from the node was extremely high, which by passes other sanity checks.

**Comment by ziggie1984** [comment]
So the reason for the problem:

User was running LND 18.0 with knots, so far so good, but we should probably not allow this because the fee estimation what lnd thinks and what the knots node thinks are different. So we should block running LND with Knots or at least create a safety switch so the user knows that when he is doing to that this is not recommended by the LND software.

Now the user updated to a newer version of Knots on start9 this one:
https://github.com/Retropex/knots-startos/releases/tag/v27.1.knots20240801-1

This unfortunately has a bug in it because it sets the default config for minrelayfee to 1000 BTC/KvB see:

https://github.com/Retropex/knots-startos/commit/4e6af47a71f683d60b3068d0e0178f7d8db20ab5#diff-d281556d8b6d8db507c837ceb687972c21fca88055be42e7a0d99e937b9b643fR65-R74

This will cause the min_relay_fee and we in LND do not limit the `min_relay_fee` when its that high and reported as a valid value by the backend. A PR will be created to change this.

**Comment by Retropex** [comment]
hello guys, there is no problem with lnd and Bitcoin Knots, the user was running on warper of Bitcoin Knots for start9 and unfortunately I have mistaken with default value. That's entirely my fault, sorry about that.

I'm in touch with the user to eventually contact the pool to get his funds back.

The package is now fixed with this commit [3701667](https://github.com/Retropex/knots-startos/commit/3701667a6a5dbe6ed414ef2e20aa63d48d7fceb4)

**Comment by Roasbeef** [comment]
Closing based on the comment above. We're also looking into ways to add additional protection into `lnd` to protect users against such config issues in the future.
