### ISSUE TITLE
LND crashed

### ISSUE THREAD

**Issue by ghanavati27** [lightningnetwork/lnd#988]
last night my lnd crashed. i trying to start it again but failed.
i updated my lnd source code few minutes ago from github and rebuild lnd.exe again.
here is my console log when i trying to start it.
console log: 
[console.txt](https://github.com/lightningnetwork/lnd/files/1865576/console.txt)

lnd log: 
[lnd.log](https://github.com/lightningnetwork/lnd/files/1865574/lnd.log)

**Comment by Roasbeef** [comment]
It looks like your fee estimation was too low, so `bitcoind` didn't accept the transaction. You can try simply re-publishing the transaction manually, or perhaps try to use a `btcd` backend to propagate the transaction. 

As an side, you seem to have a few channels which created commitment transaction which aren't easily able to propagate. A recent commit that landed in master fixed that particular issue.

**Comment by ghanavati27** [comment]
I used btcd backend to publish the transaction. but still same problem.
New lnd log: [lnd.log](https://github.com/lightningnetwork/lnd/files/1866036/lnd.log)
How i can find my raw transaction in wallet.db ? for deleting or publishing it manually...

**Comment by Jasonhcwong** [comment]
try stop bitcoind and start with "minrelaytxfee=0.00000001"  to set a smaller minrelayfee

**Comment by Roasbeef** [comment]
Any update on this? (after updating the min relay fee)

**Comment by ghanavati27** [comment]
@Roasbeef sorry for delay.
I changed minrelaytxfee to minimum but lnd could not recover wallet and resend that transaction to bitcoin network . then i deleted whole my lnd directory. you need to check lnd source code , why lnd created a transaction with low fee less than minrelaytxfee.
With this bug i afraid to run lnd on mainnet. maybe you must reopen this issue and take a deep look in source code.

**Comment by Roasbeef** [comment]
Why did you delete the data directory? Do you still have your seed?

On Apr 15, 2018 2:36 AM, "ghanavati27" <notifications@github.com> wrote:

@Roasbeef <https://github.com/Roasbeef> sorry for delay.
I changed minrelaytxfee to minimum but lnd could not recover wallet and
resend that transaction to bitcoin network . then i deleted whole my lnd
directory. you need to check lnd source code , why lnd created a
transaction with low fee less than minrelaytxfee.
With this bug i afraid to run lnd on mainnet. maybe you must reopen this
issue and take a deep look in source code.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/988#issuecomment-381393034>,
or mute the thread

**Comment by ghanavati27** [comment]
Fortunately, i kept that. zipped file is 54MB and github does not allow me to upload it.
Download it from here: http://lnd.fun/lnd_old.zip

**Comment by Roasbeef** [comment]
I don't want your `lnd` data, as I don't want your coins. The option you should set it `mintxfee` that should allow the transaction to be re-broadcast, and your `lnd` to start again.
