### ISSUE TITLE
identify offender in log

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#995]
### Background

would be nice to see which peer this comes from. ip:port or nodeid or something
not even `debuglevel --level CMGR=trace` helps

```
2018-04-01 10:29:46.020 [ERR] CMGR: Can't accept connection: chacha20poly1305: message authentication failed
2018-04-01 10:29:51.027 [ERR] CMGR: Can't accept connection: chacha20poly1305: message authentication failed
2018-04-01 10:29:56.031 [ERR] CMGR: Can't accept connection: chacha20poly1305: message authentication failed
```

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
This is due to a node trying to connect to you using a _stale_ pubkey. With the way the crypto handshake works, if the remote node doesn't know our pubkey, then we'll disconnect from them. Additionally, at this point in the `brontide` handshake we haven't progressed far enough to learn of the identity of the remote peer. 

What we _can_ do though is to print the IP which would require a small modification in the `brontide` package.

**Comment by robtex** [comment]
that would be awesome. don't know why you would need to modify brontide. isn't the error passed to the main code and logged from there? then it would know the IP

**Comment by Roasbeef** [comment]
Brontide would need to be modified to print the `RemoteAddr()` if a MAC check fails. Due to the abstraction, the outer program doesn't yet have a stable connection object to grab the address from.

**Comment by Fr4nZ82** [comment]
I have the same problem since I reset the node. It seems that many nodes that were connected to mine still try to reconnect with the old pubkey, a few days have passed but I continue to receive connections with error chacha20poly1305: message authentication failed... there are news to solve this problem? I can not change ip... I think this issue can be solved banning the old pubkey if a new pubkey is found with same ip of the old one.

**Comment by Roasbeef** [comment]
> with error chacha20poly1305: message authentication failed

This is usually due to either: you've changed your pubkey, and the remote still has your pubkey, or it's someone trying to do port scanning or the like, attempting to see if it's actually an http server. In either case, it's benign.
